#include "stdafx.h"
#include "ProtectedType_new.cpp"
#include"CheckHackTool.cpp"
#include"Controls.cpp"
#include"CurseFilter.cpp"
#include"d3dapp.cpp"
#include"d3dutil.cpp"
#include"Dsutil.cpp"
#include"dxutil.cpp"
#include"EmotionItem.cpp"
#include"EnchantStrong.cpp"
#include"FindSpecificationFilters.cpp"
#include"GCCameraOrtho.cpp"

//#include"FixWin10.cpp"

#include"GCCollisionRect.cpp"
#include"GCCoupleSystem.cpp"

#include"GCDirectionArrow.cpp"
#include"GCDoor.cpp"
#include"GCDrawCharacter.cpp"
#include"GCDropItem.cpp"
#include"GCDropItemBox.cpp"
#include"GCEffectsSword.cpp"

#include"GCGameObject.cpp"
#include"GCGameResult.cpp"
#include"GCGlobal.cpp"
#include"GCGlobalFunction.cpp"
#include"GCGraphicsHelper.cpp"

#include"GCGuildMark.cpp"
#include"GCIronDoor.cpp"
#include"GCItem.cpp"
#include"GCJumpZone.cpp"
#include"GCMonsterLink.cpp"
#include"GCNetwork.cpp"
#include"GCObject.cpp"
#include"GCObjectAndMotion.cpp"
#include"GCPairPlaySystem.cpp"
#include"GCPortal.cpp"
#include"GCRanking.cpp"
#include"GCShortCutItemDefine.cpp"
#include"GCShortCutSlot.cpp"
#include"GCSkill.cpp"
#include"GCSkillResource.cpp"
#include"GCSKT.cpp"
#include"GCSKTDebug.cpp"
#include"GCTeleporter.cpp"
#include"GCUnitMonster.cpp"
#include"GCUserCollectionMission.cpp"
#include"GCUserMission.cpp"
#include"GlobalVariables.cpp"
#include"HackShield.cpp"
#include"Headup Display.cpp"
#include"KBrowserWrapper.cpp"
#include"KDInput.cpp"
#include"KDlgPrivateInfo.cpp"
#include"KDSound.cpp"
#include"KGC2DObject.cpp"
#include"KGC3DObject.cpp"
#include"KGC3DObjectMgr.cpp"
#include"KGCAI.cpp"
#include"KGCAngelsEgg.cpp"
#include"KGCAnnounceMgr.cpp"
#include"KGCCastleDoor.cpp"
#include"KGCCrafting.cpp"
#include"KGCDeathMatch.cpp"
#include"KGCElvis.cpp"
#include"KGCEmoticon.cpp"
#include"KGCFormMDan.cpp"
#include"KGCFormNephilim.cpp"
#include"KGCFormWolf.cpp"
#include"KGCGameBoard.cpp"
#include"KGCGameModeInterface.cpp"
#include"KGCGuildMatch_CapTain.cpp"
#include"KGCGuildWar.cpp"
#include"KGCIndigo.cpp"
#include"KGCLuabinder.cpp"
#include"KInfoBox.cpp"
#include"KMailSender.cpp"
#include"KMci.cpp"
#include"KMsgBox.cpp"
#include"KRgnMsgBox.cpp"
#include"KNeonSign.cpp"
#include"KPCHWebBrowser.cpp"
#include"KPlayer.cpp"
#include"KShow.cpp"
#include"Registry.cpp"
#include"Replay.cpp"
#include"SkillTest.cpp"
#include"SlangFilter.cpp"
#include"Spark.cpp"
#include"SSOClient.cpp"
#include"UseSkillTest.cpp"
#include"Wave.cpp"
#include "KGCThaiLib.cpp"
#include "KGCObj.cpp"
#include "KGCWeatherSystem.cpp"
//---------BackGround Downloader

#include "./BackgroundDownloadSystem/HttpWrapper.cpp"
#include "./BackgroundDownloadSystem/FileDownloadManager.cpp"
#include "./BackgroundDownloadSystem/kFileDownloadThread.cpp"

//----File Dialog Manager
#include "kDXFileDialog.cpp"

