#include "stdafx.h"

#include "./animation/KGCAnimManager.cpp"
#include "./animation/KTDGAnim.cpp"

#include "./BuddySystem/KBuddy.cpp"
#include "./BuddySystem/KBuddyGroup.cpp"
#include "./BuddySystem/KFriendShip.cpp"

#include "./Drama/KGCDrama.cpp"

#include "./MapSystem/GCFantasticMap.cpp"
#include "./MapSystem/GCFootHold.cpp"
#include "./MapSystem/KGCLayer.cpp"
#include "./MapSystem/KGCLayerManager.cpp"
#include "./MapSystem/KGCLayerPart.cpp"
#include "./MapSystem/GCWall.cpp"
#include "./MapSystem/GCWallManager.cpp"

#include "./mission/GCCondition.cpp"
#include "./mission/GCCTMissionManager.cpp"
#include "./mission/GCMission.cpp"
#include "./mission/GCMissionManager.cpp"
#include "./mission/GCSubMission.cpp"
#include "./mission/KGCMissionString.cpp"

#include "./Particle/KGCParticleManager.cpp"
#include "./Particle/KTDGParticleSystem.cpp"

#include "./PrimeSearch/CRandom.cpp"
#include "./PrimeSearch/PrimeSearch.cpp"

#include "./SystemAnalysis/cpu_info.cpp"
#include "./SystemAnalysis/getdxver.cpp"
#include "./SystemAnalysis/VidMemViaWMI.cpp"
#include "./SystemAnalysis/VidMemViaDxDiag.cpp"
#include "./SystemAnalysis/VidMemViaDDraw.cpp"
#include "./SystemAnalysis/VidMemViaD3D9.cpp"
#include "./SystemAnalysis/SoundDeviceWMI.cpp"
#include "./SystemAnalysis/SystemAnalysis.cpp"

#include "./UnitTest/Win32/TimeHelpers.cpp"
#include "./UnitTest/AssertException.cpp"
#include "./UnitTest/Checks.cpp"
#include "./UnitTest/DebugOutputReporter.cpp"
#include "./UnitTest/DeferredTestReporter.cpp"
#include "./UnitTest/DeferredTestResult.cpp"
#include "./UnitTest/MemoryOutStream.cpp"
#include "./UnitTest/ReportAssert.cpp"
#include "./UnitTest/Test.cpp"
#include "./UnitTest/TestDetails.cpp"
#include "./UnitTest/TestList.cpp"
#include "./UnitTest/TestReporter.cpp"
#include "./UnitTest/TestReporterStdout.cpp"
#include "./UnitTest/TestResults.cpp"
#include "./UnitTest/TestRunner.cpp"
#include "./UnitTest/TimeConstraint.cpp"
#include "./UnitTest/XmlTestReporter.cpp"

#include "./UnitTest.cpp"
#include "./Zip/IElement.cpp"
#include "./Zip/zip.cpp"
#include "./Zip/Zipper.cpp"

#include "./KTLib/KTDGFrustum.cpp"
#include "./KTLib/KTDXTimer.cpp"
#include "./KGCObjectEgo.cpp"
#include "KGCMultipleLanguages.cpp"
#include "GCAgitObject.cpp"
#include "GCAgitObjectContainer.cpp"
#include "GCAgitObjectList.cpp"
#include "./HardAI/HardAI_Dota.cpp"
#include "KGCPartyManager.cpp"

#include "KGCAgitGameManager.cpp" 

#include "GCExtraMesh.cpp"

#include "KGCSocialMotionManager.cpp"
#include "GCForgeManager.cpp"
#include "GCAgitObjectAction.cpp"
#include "GCAgitJumpAction.cpp"
#include "GCAgitDiceAction.cpp"
#include "GCAgitFlagAction.cpp"
#include "GCJustInTime.cpp"
#include "KGCPostLetterManager.cpp"
#include "GCHeroDungeonManager.cpp"
#include "GCMonsterCardManager.cpp"
#include "GCEclipseEventManager.cpp"
#include "DragManager.cpp"
#include "KGCDepotManager.cpp"
#include "KGCDungeonInfoManager.cpp"
#include "KGCSyncObject.cpp"
#include "GCEventAlarmManager.cpp"
#include "GCSongkranEventManager.cpp"
#include "GCAdventureManager.cpp"
#include "GCLevelResetEventManager.cpp"
#include "MonsterManager.cpp"
#include "KGCFaceLift.cpp"
#include "GCOlympicManager.cpp"
#include "KGCRoomListManager.cpp"
#include "GCTextColorManager.cpp"
#include "GCItemCombinationManager.cpp"
#include "GCFaceOffManager.cpp"
#include "KGCQALogManager.cpp"
#include "GCClientErrorManager.cpp"
#include "KGCMatchManager.cpp"
#include "GCRitasChrismasManager.cpp"
#include "GCAutoMatchManager.cpp"
#include "GCProfileManager.cpp"
#include "profile.cpp"
#include "KGCEmbarkObject.cpp"
#include "KGCEmbarkManager.cpp"
#include "GCBuffDonationManager.cpp"
#include "GCAttendanceStampManager.cpp"
#include "GCChallengeErrandManager.cpp"
#include "GCUpdatePlanManager.cpp"
#include "KGCSubject.cpp"
#include "KGCSubjectManager.cpp"
#include "KGCPrivateDungeonManager.cpp"
#include "KGCJumpingCharManager.cpp"

#include "GCGuideMgr.cpp"
#include "KGCGiftBoxManager.cpp"
#include "KGCNetworkStatManager.cpp"
#include "GCGrowingSkillManager.cpp"


#include "KGCVirtualDepotManager.cpp"
#include "GCSocialCommerceManager.cpp"
