//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by WOGMapTOol.rc
//
#define IDR_MAINFRAME                   101
#define IDD_FORMVIEW                    102
#define IDD_CREATELAYERPART             201
#define IDD_NEW_CATEGORY                203
#define IDD_CHECK_CATEGORY              204
#define IDC_MOVE_CURSOR                 205
#define IDD_LAYER_RESIZING              207
#define IDR_ACCELERATOR1                208
#define IDD_DIALOG1                     209
#define IDD_NEW_MAP                     209
#define IDD_DIALOG2                     210
#define IDD_RESIZING_MAP                210
#define IDD_OBJECT_MOVE                 211
#define IDD_LAYER_CHANGE                212
#define IDD_DIALOG3                     212
#define IDD_USER_PROP                   213
#define IDD_PARTLIST                    214
#define IDD_LAYERLIST                   215
#define IDD_EFFECT_PROP                 216
#define IDD_LAYER_SIZE                  217
#define IDD_MOVE_PROP                   218
#define IDD_FHVALUE                     219
#define IDR_RT_MANIFEST1                220
#define IDR_ACCELERATOR2                222
#define IDC_V_GRID                      223
#define IDC_H_GRID                      224
#define IDD_CHANGE_GRIDGUIDE_TERM       225
#define IDD_PARTICLE_LIST_DLG           226
#define IDC_RENDERVIEW                  2002
#define IDC_COMBO_SRCBLEND              2005
#define IDC_COMBO_DESTBLEND             2006
#define IDC_PART_PREVIEW                2008
#define IDC_PART_NAME                   2009
#define IDC_CHECK_DUPLICATE             2010
#define IDC_SELECT_TEXTURE              2011
#define IDC_PART_X                      2012
#define IDC_PART_Y                      2013
#define IDC_PART_WIDTH                  2014
#define IDC_PART_HEIGHT                 2015
#define IDC_PART_CATEGORY               2016
#define IDC_CATEGORY_LIST               2017
#define IDC_NEW_NAME_VERIFY             2019
#define IDC_ADD_PART                    2020
#define IDC_DEL_PART                    2021
#define IDC_DEL_CATEGORY                2022
#define IDC_CHECK_CATEGORY_LIST         2023
#define IDC_ADD_CATEGORY                2026
#define IDC_MODIFY_PART                 2027
#define IDC_LAYER_LIST                  2029
#define IDC_CATEGORY                    2030
#define IDC_PARTS                       2031
#define IDC_OBJECT_LIST                 2032
#define IDC_LAYER_RESIZE                2033
#define IDC_LAYER_ADD                   2034
#define IDC_LAYER_DEL                   2035
#define IDC_EDIT1                       2035
#define IDC_EDIT2                       2036
#define IDC_Z_ORDER_UP                  2036
#define IDC_Z_ORDER_DOWN                2037
#define IDC_OBJECT_DEL                  2039
#define IDC_LAYER_X                     2040
#define IDC_LAYER_Y                     2041
#define IDC_LAYER_WIDTH                 2042
#define IDC_LAYER_HEIGHT                2043
#define IDC_MOVEABLE_TRUE               2044
#define IDC_X_SPEED                     2045
#define IDC_MOVEABLE_FALSE              2046
#define IDC_Y_SPEED                     2047
#define IDC_POSITIONRESET_X             2048
#define IDC_POSITIONRESET_Y             2049
#define IDC_EFFECT_NAME                 2050
#define IDC_USE_EFFECT_YES              2051
#define IDC_USE_EFFECT_NO               2052
#define IDC_EFFECT_TERM_X               2053
#define IDC_EFFECT_TERM_Y               2054
#define IDC_Q_MOVEABLE                  2055
#define IDC_Q_USE_EFFECT                2056
#define IDC_OBJECT_UNIQUE_NAME          2057
#define IDC_OBJECT_NAME_VERIFY          2058
#define IDC_WORLD_WIDTH                 2059
#define IDC_WORLD_HEIGHT                2060
#define IDC_OBJECT_CLONE                2061
#define IDC_REVERSE_LEFTRIGHT           2062
#define IDC_REVERSE_UPDOWN              2063
#define IDC_OBJECT_MOVE                 2064
#define IDC_LAYER_NUMBER                2065
#define IDC_WANT_MOVE                   2066
#define IDC_CHANGE_LAYER                2067
#define IDC_WANT_CHANGE                 2068
#define IDC_CURRENT_LAYER               2069
#define IDC_USERVALUE                   2070
#define IDC_USERVALUE_APPLY             2071
#define IDC_EDIT3                       2072
#define IDC_USERSTRING                  2072
#define IDC_APPLY                       2081
#define IDC_FHVALUE                     2082
#define IDC_CLONE                       2085
#define IDC_FH_WIDTH                    2087
#define IDC_FH_HEIGHT                   2088
#define IDC_APPLY_LAYER                 2090
#define IDC_APPLY_TEXTURE               2091
#define IDC_LOG_LIST                    2092
#define IDC_SHOW_PARTICLE_LIST          2094
#define IDC_CHANGE_TERM                 2098
#define IDC_WANT_CHANGE_TERM            2099
#define IDC_H_GUIDELINE                 2100
#define IDC_V_GUIDELINE                 2101
#define IDC_CHECK1                      2102
#define IDC_CHECK_ALL                   2102
#define IDC_SCROOLX                     2103
#define IDC_CHECK3                      2104
#define IDC_SCROOLY                     2104
#define IDC_BUTTON_DELETE_PARTICLE      2105
#define IDC_BUTTON_ADD_PARTICLE         2106
#define IDC_LIST_PARTICLE               2108
#define IDC_PROGRESS1                   2109
#define IDC_STATIC_PARTICLE_NUM         2110
#define IDC_BTN_TEXUV                   2111
#define IDC_NEW_CATEGORYNAME            11009
#define IDM_LAYERMANAGER_CREATELAYERPART 40021
#define ID_LAYERMANAGER_EDITLAYER       40023
#define ID_ACCEL_FILE_LOAD              40025
#define ID_ACCEL_EXIT                   40026
#define ID_FILE_LOAD                    40028
#define ID_ACCEL_RESETVIEW              40029
#define ID_ACCEL_FILE_SAVE              40032
#define ID_ACCEL_FILE_NEW               40036
#define ID_40038                        40038
#define ID_MODE_FH                      40041
#define ID_MODE_LAYER                   40042
#define ID_ACCEL_MODE_FH                40043
#define ID_ACCEL_MODE_LAYER             40044
#define ID_ACCEL_FILE_CLOSE             40046
#define ID_WORLDRESIZE                  40049
#define ID_ACCEL_WORLD_RESIZE           40050
#define ID_DEBUG_ZORDERSORTING          40052
#define ID_ACCEL_FILE_SAVE_AS           40053
#define ID_ACCEL_RESET                  40062
#define ID_ACCEL_UNDO                   40064
#define ID_ACCEL_REDO                   40065
#define ID_GRIDGUIDELINE_CHANGE_TERM    40068
#define ID_GRID_ADD_VERTICAL_GUIDE      40071
#define ID_GRID_ADD_HORIZON_GUIDE       40073
#define ID_FORCEDEBUG_MAKEFOOTHOLDIMAGE 40074
#define ID_ACCEL_F                      40075
#define ID_ACCEL_FOOT_HOLD              40075

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        227
#define _APS_NEXT_COMMAND_VALUE         40077
#define _APS_NEXT_CONTROL_VALUE         2112
#define _APS_NEXT_SYMED_VALUE           301
#endif
#endif
