#pragma once

enum PLAYER_COMMON_MOTION
{
    ATK1,
    ATKEND,
    WAIT,
    FATAL_WAIT,
    WALK,
    SPECIAL1_W,
    SPECIAL2_W,
    SPECIAL3_W,
    SPECIAL1_B,
    SPECIAL2_B,
    SPECIAL3_B,
    ORIGINAL1_W,
    ORIGINAL2_W,
    ORIGINAL3_W,
    ORIGINAL1_B,
    ORIGINAL2_B,
    ORIGINAL3_B,
    DASH,
    DASH_ATK,
    WIN,
    START,
    SELECT,
    RESULT_WIN,
    RESULT_LOSE,
    JOKE,
    RUN,
    JUMP_DASH_ATK,
    ATK1_FASTINPUT,
    JUMP,
    JUMP_ATK,
    JUMP_DASH,
    JUMP_READY,
    DOUBLE_JUMP,
    DOUBLE_JUMP_ATK,
    DOUBLE_JUMP_LAND,
    CRITICAL_ATK,
    DOUBLE_ATK,
    NUM_OF_MOTION
};

enum TG_TYPE { TG_TYPE_EACTION = 0, TG_TYPE_CONDITION };
enum TG_EACTION { TG_EACTION_DEFAULT, TG_EACTION_POSITIONPARTICLE, TG_EACTION_WIN, TG_EACTION_LOSE, TG_EACTION_MON_GENNER
, TG_EACTION_UNITMOVEMENT, TG_EACTION_SOUND_ONOFF, TG_EACTION_LOADING, TG_EACTION_CLEAROFSTAGE, TG_EACTION_TRIGGERONOFF
, TG_EACTION_REWARD, TG_EACTION_NEXTSTAGE, TG_EACTION_SUPERPLAYER, TG_EACTION_PLAYERPOSITION, TG_EACTION_OBJECTGENERATER
, TG_EACTION_OPEN_DGATE, TG_EACTION_TITLETEXT, TG_EACTION_TRIGGERREADY, TG_EACTION_DIALOGUE, TG_EACTION_DELETEMONSTER
, TG_EACTION_FADE_INOUT, TG_EACTION_HP, TG_EACTION_MP, TG_EACTION_PLAYERMOTION, TG_EACTION_UNIT_PARTICLE
, TG_EACTION_PLAYERMOVINGTOAREA, TG_EACTION_CHANGE_OBJ_STATE, TG_EACTION_GATE_OBJECT_GEN, TG_EACTION_ADD_DAMAGE, TG_EACTION_WATER
, TG_EACTION_WEATHER, TG_EACTION_EMBARK, TG_EACTION_WALL, TG_EACTION_SUBJECT, TG_EACTION_INFINITY_MON_GEN
};
enum TG_CONDITION { TG_CONDITION_DEFAULT, TG_CONDITION_KILLMASTER, TG_CONDITION_TIMER, TG_CONDITION_POSITION, TG_CONDITION_OBJ_DESTROY, TG_CONDITION_DIALOGUE_STATE, TG_CONDITION_HP_CHANGE, TG_CONDITION_WALL, TG_CONDITION_KILLALLMONSTER };
