#pragma once

enum OBJECT_TYPE_EACTION { OBJECTTYPE_EACTION_PLAYER = 0, OBJECTTYPE_EACTION_MON, OBJECTTYPE_EACTION_OBJECT, OBJECTTYPE_EACTION_DOOR, OBJECTTYPE_EACTION_DAMAGE, OBJECTTYPE_EACTION_EMBARK, OBJECTTYPE_EACTION_MAXNUM };
enum OBJECT_TYPE_CONDITION { OBJECTTYPE_CONDITION_SELECT_MON = 0, OBJECTTYPE_CONDITION_SELECT_AREA, OBJECTTYPE_CONDITION_SELECT_POS, OBJECTTYPE_CONDITION_MAXNUM };

#define START_POS_X 10
#define START_POS_Y 50
