//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by QuestScripter.rc
//
#define IDD_QUESTSCRIPTER_DIALOG        102
#define IDR_HTML_M_DLG_QUEST_SEQUENCE   103
#define IDR_HTML_DLGSTAGEMONSTER        104
#define IDD_DLGMAPTOOBJECT              105
#define IDR_HTML_DLGTGPLAYERMOVINGTOAREA 109
#define IDR_HTML_DLGTGOPTIONJUMPZONE    110
#define IDR_HTML_DLGOPTIONJUMPZONE      111
#define IDR_MAINFRAME                   128
#define IDR_POPUP_MENU                  130
#define IDB_TREE                        132
#define IDR_MYTYPE                      133
#define IDR_POPUP_MYTREE                134
#define IDR_POPUP_TRIGGER               135
#define IDR_POPUP_TG_CONTENT            137
#define IDR_TOOLBAR_MENU                142
#define IDR_TOOLBAR1                    144
#define IDD_DIALOG_QUEST                146
#define IDD_DIALOG_STAGE                147
#define IDD_DIALOG_QUEST_SEQUENCE       152
#define IDD_DIALOG_HELP                 152
#define IDC_DROP_COPY_ABOVE             153
#define IDC_DROP_COPY_ROOT              154
#define IDC_DROP_COPY_SON               155
#define IDC_DROP_MOVE_ABOVE             156
#define IDC_DROP_MOVE_ROOT              157
#define IDC_NODROP                      158
#define IDC_DROP_MOVE_SON               159
#define IDD_DIALOG_STRUCT               160
#define IDD_DIALOG_POPUP_BOARD          161
#define IDR_ACCELERATOR_MAIN_DLG        162
#define IDD_DIALOG_TOOL_PALETTE         163
#define IDR_ACCELERATOR_TG_CONTENT      163
#define IDD_DIALOG1                     164
#define IDR_ACCELERATOR_TGGER           164
#define IDR_ACCELERATOR_TRIGGER         164
#define IDD_DIALOG_STAGE_OBJECT_POPUP   165
#define IDD_DIALOG_OBJECTGENERATE_POPUP 165
#define IDD_DIALOG_CHANGE_SEQUENCE      166
#define IDD_DIALOG_TRIGGER              167
#define IDD_DIALOG_TRIGGER_CONTENT      168
#define IDD_DIALOG_TG_CHILD_GENNER      169
#define IDD_DIALOG_TILE_ROW_COL         172
#define IDD_DIALOG_TILE_TYPE_SELECT     173
#define IDD_DIALOG_TILE_BG              174
#define IDD_DIALOG_DEFAULT_DIRECTION    175
#define IDD_DIALOG_TG_ADDDAMAGE_OPTION_WATERPOLE 177
#define IDD_DIALOG_TG_KILLMASTER        178
#define IDD_DIALOG_TG_CHECK_HP          179
#define IDD_DIALOG_CLEAROFSTAGE         180
#define IDD_DIALOG_TG_LOADING           181
#define IDD_DIALOG_TG_LOSE              182
#define IDD_DIALOG_TG_MONSTERGENERATER  183
#define IDD_DIALOG_TG_WEATHER           184
#define IDD_DIALOG_TG_SOUNDONOFF        185
#define IDD_DIALOG_TG_WIN               187
#define IDD_DIALOG_TG_TIMER             188
#define IDD_DIALOG_TG_CLEAROFSTAGE      189
#define IDD_DIALOG_TG_TGONOFF           190
#define IDD_DIALOG_TG_REWARD            191
#define IDD_DIALOG_TG_NEXTSTAGE         192
#define IDD_DIALOG_TG_SUPER_PLAYER      193
#define IDD_DIALOG_TG_PLAYERPOSITION    195
#define IDD_DIALOG_TG_PLAYERPOSITION_POPUP 196
#define IDD_DIALOG_TG_COMMON            198
#define IDD_DIALOG_TRIGGER_CONTENT1     199
#define IDD_DIALOG_TG_POSITION          199
#define IDD_DIALOG_TG_OBJECTGENERATER   202
#define IDD_DIALOG_STAGE_MONSTER2_POPUP 203
#define IDD_DIALOG_STAGE_MONSTER_POPUP  203
#define IDD_DIALOG_TG_OPEN_DGATE        204
#define IDD_DIALOG_TILE_INFO            205
#define IDD_DIALOG_TG_TITLETEXT         206
#define IDD_DIALOG_DIRECTORY            207
#define IDD_DIALOG_TG_TGREADY           208
#define IDD_DIALOG_BASE_PALETTE_CONTENT 209
#define IDD_DIALOG_PALETTE_CONTENT      209
#define IDD_DIALOG_TG_DIALOGUE          210
#define IDD_DIALOG_TG_DELETE_MONSTER    211
#define IDD_DIALOG_TG_PLAYER_MOTION     212
#define IDD_DIALOG_TG_HP                213
#define IDD_DIALOG_TG_MP                214
#define IDD_DIALOG_TG_UNIT_PARTICLE     215
#define IDD_DIALOG_TG_POSITION_PARTICLE 216
#define IDD_DIALOG_TG_FADE_IN_OUT       217
#define IDD_DIALOG_TG_UNIT_MOVEMENT     218
#define IDD_DIALOG_TG_MOVING_TO_AREA    219
#define IDD_DIALOG_TG_PLAYER_MOVING_TO_AREA 219
#define IDD_DIALOG_TG_IS_DESTROYED_OBJECT 220
#define IDD_DIALOG_TG_CHANGE_OBJ_STATE  221
#define IDD_DIALOG_TG_GATEOBJECTGENERATER 222
#define IDD_DIALOG_GATEOBJECTGENERATE_POPUP 223
#define IDD_DIALOG_FILE_LIST            224
#define IDD_DIALOG_TG_ADD_DAMAGE        225
#define IDD_DIALOG_TG_WATER             226
#define IDD_DIALOG_ADDDAMAGE_POPUP      227
#define IDD_DIALOG_TG_DIALOGUE_STATE    228
#define IDD_DIALOG_TG_EMBARK            229
#define IDD_DIALOG_TG_WALL              230
#define IDD_DIALOG_TG_CHECK_WALL        231
#define IDD_DIALOG_TG_SUBJECT           232
#define IDD_DIALOG_TG_INFINITY_MON_GEN  233
#define IDD_DIALOG_TG_INFINITY_MON_GEN1 234
#define IDD_DIALOG_TG_KILL_ALL_MONSTER  234
#define IDC_TREE_SCRIPT                 1000
#define IDC_EDIT1                       1002
#define IDC_EDIT_STAGEMAP               1003
#define IDC_EDIT_HELP                   1004
#define IDC_EDIT_TG_COMMENT             1005
#define IDC_EDIT_LOAD_FILENAME          1006
#define IDC_EDIT_TGONOFF_NAME           1007
#define IDC_EDIT_TEXTURE                1008
#define IDC_EDIT2                       1009
#define IDC_EDIT_BGM                    1010
#define IDC_EDIT_MONSTER_Y              1011
#define IDC_EDIT_TEXOBJECT_NAME         1012
#define IDC_EDIT3                       1013
#define IDC_EDIT_TOP                    1014
#define IDC_EDIT4                       1015
#define IDC_EDIT_BOTTOM                 1016
#define IDC_EDIT5                       1017
#define IDC_EDIT_ENTRANCEX              1018
#define IDC_EDIT_QUESTSCRIPT            1019
#define IDC_EDIT6                       1020
#define IDC_EDIT_MAPSUBFILE             1020
#define IDC_EDIT_ENTRANCEY              1021
#define IDC_COMBO1                      1022
#define IDC_COMBO_TG_PLAYERPOSITION_RIGHT 1022
#define IDC_COMBO_TG_FADE_IN_OUT        1022
#define IDC_COMBO_TG_DIALOGUE           1022
#define IDC_COMBO_TIMER                 1022
#define IDC_COMBO_TIMER_ONOFF           1022
#define IDC_COMBO_CRASHABLE             1022
#define IDC_EDIT_DELAY                  1022
#define IDC_COMBO_ONOF                  1022
#define IDC_EDIT_RECYCLETIME            1022
#define IDC_COMBO_SEQUENCE              1023
#define IDC_COMBO_TGONOFF_ONOFF         1024
#define IDC_COMBO_LOAD_ENUM             1025
#define IDC_COMBO_TGONOFF_ONOFF2        1025
#define IDC_COMBO_TGONOFF_CHAR          1025
#define IDC_COMBO_SUPER_PLAYER          1026
#define IDC_COMBO_STAGEMAP              1027
#define IDC_COMBO_MUSIC_FILENAME        1028
#define IDC_COMBO_TYPE                  1029
#define IDC_COMBO_ONOFF                 1030
#define IDC_COMBO_HALF_MORE             1031
#define IDC_COMBO_TYPE_EACTION          1032
#define IDC_COMBO_Direction             1033
#define IDC_COMBO_DIRECTION             1034
#define IDC_COMBO_TYPE_CONDITION        1035
#define IDC_COMBO2                      1036
#define IDC_COMBO_TG_ONOFF              1036
#define IDC_COMBO_SLOT_TYPE             1036
#define IDC_STATIC_MAIN                 1037
#define IDC_COMBO_DIRECTION2            1038
#define IDC_COMBO_PLAYER_OR_MONSTER     1039
#define IDC_COMBO_TGONOFF_NAME          1040
#define IDC_COMBO_STRUCT                1041
#define IDC_COMBO_ACTIVE2               1042
#define IDC_COMBO_MONSTER_RIGHT         1043
#define IDC_COMBO_GENERATE              1044
#define IDC_COMBO_MUSIC_ONOFF           1045
#define IDC_COMBO_BOSS                  1046
#define IDC_EDIT_EXP                    1047
#define IDC_EDIT_GP                     1048
#define IDC_EDIT_DOORNAME               1049
#define IDC_EDIT_STAGE                  1050
#define IDC_EDIT_STAGE_PERCENT          1051
#define IDC_BUTTON1                     1052
#define IDC_EDIT_DOORNAME2              1053
#define IDC_EDIT_REMAIN_PERCENT         1054
#define IDC_COMBO_ID                    1055
#define IDC_BUTTON_SOUND                1056
#define IDC_COMBO_PROPERTY              1057
#define IDC_BUTTON_QUESTSCRIPT          1058
#define IDC_STATIC_SCREEN               1059
#define IDC_BUTTON_MAPSUBFILE           1059
#define IDC_BUTTON_MON_ADD              1060
#define IDC_BUTTON_STAGEMAP             1061
#define IDC_BUTTON_BGM                  1062
#define IDC_DELETE                      1063
#define IDC_STATIC_INFO                 1064
#define IDC_LIST_STAGE                  1065
#define IDC_BUTTON_STAGE                1066
#define IDC_BUTTON_STAGE2               1067
#define IDC_BUTTON_STAGE_DEL            1068
#define IDC_LIST_STAGE_N_PERCENT        1069
#define IDC_STATIC_SPLITTER             1070
#define IDC_TREE_TRIGGER                1071
#define IDC_STATIC_SPLITTER2            1072
#define IDC_STATIC_COMMENT              1073
#define IDC_STATIC_TRIGGER              1074
#define IDC_TREE_TG                     1075
#define IDC_LIST_TYPE                   1076
#define IDC_STATIC_TYPE                 1077
#define IDC_SPIN_TIMER                  1078
#define IDC_EDIT_STAGE_FILENAME         1079
#define IDC_EDIT_TIMER                  1080
#define IDC_EDIT_MUSIC_FILENAME         1081
#define IDC_COMBO_MON_SLOT              1082
#define IDC_COMBO_MONSTER_TYPE          1083
#define IDC_BUTTON_SELECT_FROM_MAP      1084
#define IDC_COMBO_MONSTER_TYPE2         1084
#define IDC_BUTTON_SELECT_FROM_MAP_SEL_MON 1085
#define IDC_EDIT_LEFT                   1086
#define IDC_BUTTON_SELECT_FROM_MAP_AREA 1087
#define IDC_EDIT_RIGHT                  1088
#define IDC_COMBO_PLAYER_SLOT           1089
#define IDC_EDIT_RECYCLE                1089
#define IDC_COMBO_GATE_STATE            1090
#define IDC_EDIT_STARTLIFE              1090
#define IDC_BUTTON_SELECT_FROM_MAP_SEL_AREA 1091
#define IDC_EDIT_CRASHSTART             1091
#define IDC_COMBO_MONSTER_SLOT          1092
#define IDC_EDIT_MYSPEED                1092
#define IDC_COMBO_GATE_NAME             1093
#define IDC_EDIT_RECYCLE5               1093
#define IDC_EDIT_JUMPFRAME              1093
#define IDC_EDIT_LEFT2                  1094
#define IDC_COMBO_MONSTER_BOSS          1095
#define IDC_EDIT_MONSTER_X              1096
#define IDC_COMBO_LOADING_ONOFF         1097
#define IDC_STATIC_KILLMASTER_1         1098
#define IDC_STATIC_KILLMASTER_2         1099
#define IDC_STATIC_LOADING_1            1100
#define IDC_STATIC_LOADING_2            1101
#define IDC_STATIC_LOADING_3            1102
#define IDC_STATIC_LOSE_1               1103
#define IDC_STATIC_MONGEN_1             1104
#define IDC_STATIC_MONGEN_2             1105
#define IDC_STATIC_MONGEN_3             1106
#define IDC_STATIC_MONGEN_4             1107
#define IDC_STATIC_MONGEN_5             1108
#define IDC_STATIC_PLAYERGEN_1          1109
#define IDC_STATIC_MONGEN_6             1109
#define IDC_STATIC_POSITION_1           1110
#define IDC_STATIC_MONGEN_7             1110
#define IDC_STATIC_PLAYERGEN_2          1111
#define IDC_STATIC_POSITION_2           1112
#define IDC_STATIC_POSITION_3           1113
#define IDC_STATIC_POSITION_PARTICLE_2  1113
#define IDC_STATIC_SOUNDONOFF_1         1114
#define IDC_STATIC_SOUNDONOFF_2         1115
#define IDC_STATIC_STAGECHANGER_1       1116
#define IDC_STATIC_TIMER_1              1117
#define IDC_STATIC_WIN_1                1118
#define IDC_STATIC_TRIGGER_ONOFF        1119
#define IDC_STATIC_TRIGGER_ONOFF_1      1120
#define IDC_BUTTON_OPEN_TGEDITOR        1121
#define IDC_BUTTON_MUSIC_FILE           1122
#define IDC_STATIC_TRIGGER_ONOFF_2      1122
#define IDC_STATIC_REWARD_1             1123
#define IDC_STATIC_REWARD_2             1124
#define IDC_STATIC_REWARD_3             1125
#define IDC_STATIC_REWARD_4             1126
#define IDC_STATIC_TG_NEXTSTAGE_2       1127
#define IDC_STATIC_TG_NEXTSTAGE_1       1128
#define IDC_EDIT_Level                  1129
#define IDC_EDIT_MONSTER_LEVEL          1129
#define IDC_EDIT_                       1129
#define IDC_EDIT_LV                     1129
#define IDC_EDIT_CONTINUEANCE           1129
#define IDC_EDIT_GANE_LV                1130
#define IDC_STATIC_STAGEOFCLEAR_1       1131
#define IDC_CHECK_USE                   1132
#define IDC_CHECK2                      1133
#define IDC_CHECK_ACTIVE                1134
#define IDC_COMBO_EACTION               1135
#define IDC_STATIC_PLAYERPOSITION_1     1136
#define IDC_COMBO_STATE                 1136
#define IDC_EDIT_PLAYER_Y               1137
#define IDC_EDIT_PLAYER_X               1138
#define IDC_STATIC_PLAYERPOSITION_2     1139
#define IDC_COMBO_PLAYERINDEX           1140
#define IDC_STATIC_PLAYERPOSITION_3     1140
#define IDC_CHECK_REPEAT                1141
#define IDC_STATIC_DELETE_MONSTER_2     1141
#define IDC_STATIC_STAGEGATE_1          1142
#define IDC_STATIC_DELETE_MONSTER_1     1142
#define IDC_STATIC_STAGEGATE_2          1143
#define IDC_STATIC_STAGEGATE_3          1144
#define IDC_STATIC_PLAYER_MOTION_2      1144
#define IDC_COMBO_GATE_TYPE             1145
#define IDC_STATIC_PLAYER_MOTION_1      1145
#define IDC_STATIC_STAGEGATE_4          1146
#define IDC_COMBO_SLOT                  1147
#define IDC_BUTTON_SELECT_FROM_MAP_MONSTER 1148
#define IDC_STATIC_TEXOBJECT_1          1149
#define IDC_STATIC_TEXOBJECT_2          1150
#define IDC_STATIC_OBJGEN_1             1151
#define IDC_STATIC_OBJGEN_2             1152
#define IDC_COMBO_POSITION_PARTICLE     1152
#define IDC_STATIC_TEXOBJECT_3          1153
#define IDC_STATIC_POSITION_PARTICLE_1  1153
#define IDC_STATIC_OBJGEN_5             1153
#define IDC_STATIC_OBJGEN_4             1154
#define IDC_STATIC_UNIT_PARTICLE_2      1154
#define IDC_STATIC_OBJGEN_8             1154
#define IDC_STATIC_OBJGEN_3             1155
#define IDC_STATIC_UNIT_PARTICLE_1      1155
#define IDC_STATIC_OBJGEN_9             1155
#define IDC_COMBO_OBJ_SLOT              1156
#define IDC_COMBO_UNIT_PARTICLE         1156
#define IDC_STATIC_OBJGEN_10            1156
#define IDC_COMBO_OBJ_TYPE              1157
#define IDC_STATIC_UNIT_MOVEMENT_2      1157
#define IDC_STATIC_OBJGEN_11            1157
#define IDC_COMBO_OBJ_RIGHT             1158
#define IDC_STATIC_UNIT_MOVEMENT_1      1158
#define IDC_STATIC_OBJGEN_12            1158
#define IDC_EDIT_OBJ_X                  1159
#define IDC_STATIC_UNIT_HP_1            1159
#define IDC_STATIC_OBJGEN_13            1159
#define IDC_EDIT_OBJ_Y                  1160
#define IDC_STATIC_UNIT_MP_2            1160
#define IDC_STATIC_OBJGEN_14            1160
#define IDC_COMBO_OBJ_GEN               1161
#define IDC_STATIC_UNIT_MP_1            1161
#define IDC_STATIC_WIND_X               1161
#define IDC_BUTTON_RESIZE               1162
#define IDC_EDIT_TG_MP                  1162
#define IDC_EDIT_OBJ_Jump               1162
#define IDC_EDIT_USE_SELECT             1162
#define IDC_STATIC_WIND_Y               1162
#define IDC_STATIC_OPEN_GATELEFT_1      1163
#define IDC_STATIC_UNIT_HP_2            1163
#define IDC_STATIC_OBJGEN_6             1163
#define IDC_EDIT_DOTA_STAGE             1163
#define IDC_STATIC_WIND_JUMPRADIO       1163
#define IDC_STATIC_ROW_COL_GROUP        1164
#define IDC_EDIT_TG_HP                  1164
#define IDC_STATIC_OBJGEN_7             1164
#define IDC_STATIC_ROW_COL              1165
#define IDC_STATIC_PLAYER_MOVING_TO_AREA_2 1165
#define IDC_BUTTON_SEL                  1166
#define IDC_STATIC_PLAYER_MOVING_TO_AREA_1 1166
#define IDC_SPIN1                       1167
#define IDC_COMBO_STAGE                 1168
#define IDC_LIST1                       1168
#define IDC_LIST_FILE_LIST              1168
#define IDC_LIST_EFF                    1168
#define IDC_LIST_SUBJECT_CHARTYPE       1168
#define IDC_RADIO1                      1169
#define IDC_RADIO_DEL                   1169
#define IDC_LIST_SUBJECT_LEVEL          1169
#define IDC_RADIO_DIRECTION             1170
#define IDC_COMBO_OBJ_DESTROYED         1170
#define IDC_COMBO_OBJ_DESTROYED_TYPE    1170
#define IDC_RADIO2                      1170
#define IDC_RADIO_MONGEN2               1170
#define IDC_LIST_SUBJECT_JOBLEVEL       1170
#define IDC_RADIO_STAGE                 1171
#define IDC_COMBO_OBJ                   1171
#define IDC_BUTTON1_INIT                1172
#define IDC_STATIC_OBJ_DESTROYED_1      1172
#define IDC_CHECK_OBJECT                1173
#define IDC_STATIC_OBJ_DESTROYED_2      1173
#define IDC_COMBO_CHANGE_OBJ_STATE_SLOT 1173
#define IDC_CHECK_PLAYER                1174
#define IDC_STATIC_CHANGE_OBJ_STATE_1   1174
#define IDC_EDIT_TITLETEXT              1175
#define IDC_COMBO_CHANGE_OBJ_STATE      1175
#define IDC_CHECK_MONSTER               1176
#define IDC_STATIC_CHANGE_OBJ_STATE_2   1176
#define IDC_STATIC_TITLETEXT1           1177
#define IDC_COMBO_CHANGE_OBJ_STATE_OBJ  1177
#define IDC_CHECK1                      1177
#define IDC_CHECK_FORCE_DIRECTION       1177
#define IDC_CHECK_SORT_DIRECTION_STAGE  1177
#define IDC_CHECK_RIGHT                 1177
#define IDC_CHECK_NEW                   1177
#define IDC_CHECK_DELETE_ALL            1177
#define IDC_CHECK_DAMAGE                1177
#define IDC_CHECK_CHAMPION              1177
#define IDC_STATIC_TITLETEXT_1          1178
#define IDC_BUTTON_TG_EDITOR            1178
#define IDC_CHECK_DOWN                  1178
#define IDC_COMBO_CHANGE_OBJ_STATE_OBJ2 1178
#define IDC_EDIT_MAP                    1179
#define IDC_STATIC_TITLETEXT_2          1179
#define IDC_STATIC_CHANGE_OBJ_STATE_3   1179
#define IDC_EDIT_SOUND                  1180
#define IDC_BUTTON_MAP                  1181
#define IDC_BUTTON_FILE_ADD             1181
#define IDC_COMBO_IN_OUT                1182
#define IDC_RADIO_TOP                   1182
#define IDC_BUTTON_DELETE               1182
#define IDC_COMBO_TGREADY_NAME          1183
#define IDC_CHECK_LEFT                  1183
#define IDC_BUTTON_CLEAR_LIST           1183
#define IDC_STATIC_TRIGGER_READY_1      1184
#define IDC_CHECK_UP                    1184
#define IDC_BUTTON_LOAD                 1184
#define IDC_BUTTON_CLOSE                1185
#define IDC_BUTTON_FOLDER_ADD           1186
#define IDC_BUTTON_LOAD2                1187
#define IDC_BUTTON_SAVE                 1187
#define IDC_BUTTON_SAVE_TO_SSCRIPT      1188
#define IDC_BUTTON_SAVE_TO_SERVER_SCRIPT 1188
#define IDC_EDIT_Y                      1188
#define IDC_EDIT_X                      1189
#define IDC_COMBO_DAMAGEID              1190
#define IDC_STATIC_ADD_DAMAGE_1         1191
#define IDC_STATIC_ADD_DAMAGE_2         1192
#define IDC_BUTTON_MAP_ON_HEIGHT        1193
#define IDC_STATIC_ADD_DAMAGE_3         1193
#define IDC_STATIC_RecycleTime          1194
#define IDC_STATIC_RECYCLETIME          1194
#define IDC_EDIT_LIFE                   1195
#define IDC_COMBO_DIALOGUE_STATE        1197
#define IDC_COMBO_DAMAGE_DIRECTION2     1199
#define IDC_EDIT_STARTTIME              1200
#define IDC_EDIT_STARTTIME2             1200
#define IDC_EDIT_PERCENT                1201
#define IDC_STATIC_CHECKHP1             1202
#define IDC_STATIC_CHECKHP2             1203
#define IDC_STATIC_CHECKHP3             1204
#define IDC_COMBO_STATE_SORTING         1205
#define IDC_EDIT_MONGEN_PERCENT         1206
#define IDC_RADIO_MONGEN1               1207
#define IDC_COMBO_WEATHERTYPE           1208
#define IDC_EDIT_WEATHER_POS_X          1209
#define IDC_EDIT_WEATHER_POS_Y          1210
#define IDC_EDIT_WEATHER_POS_WIDTH      1211
#define IDC_EDIT_WEATHER_POS_HEIGHT     1212
#define IDC_EDIT_WEATHER_EFF_SEQ        1213
#define IDC_EDIT_WEATHER_EFF_X          1214
#define IDC_EDIT_WEATHER_EFF_Y          1215
#define IDC_BUTTON_ADD_EFF              1216
#define IDC_EDIT_WEATHER_WIND_SPEED_X   1217
#define IDC_GROUP_WIND                  1218
#define IDC_EDIT_CHAR                   1219
#define IDC_EDIT_WEATHER_WIND_SPEED_Y   1220
#define IDC_EDIT_WEATHER_WIND_JUMPRADIO 1221
#define IDC_BUTTON_ALL_DEL              1223
#define IDC_COMBO_EMBARK_TYPE           1224
#define IDC_COMBO_EMBARK_RIGHT          1225
#define IDC_EDIT_EMBARK_X               1226
#define IDC_EDIT_EMBARK_Y               1227
#define IDC_COMBO_EMBARK_CHAR_SLOT      1228
#define IDC_EDIT_EMBARK_SLOT            1229
#define IDC_EDIT_WALL_TYPE              1230
#define IDC_EDIT_WALL_SLOT              1231
#define IDC_EDIT_WALL_POS_X             1232
#define IDC_COMBO_WALL_IS_DESTROY       1233
#define IDC_COMBO_WALL_IS_CHECK_INBOUND 1234
#define IDC_EDIT_CHECK_WALL_SLOT        1234
#define IDC_COMBO_CHECK_WALL_LIVE       1235
#define IDC_EDIT_SUBJECT_CHARTYPE       1236
#define IDC_BUTTON_SUBJECT_CHARTYPE     1237
#define IDC_EDIT_SUBJECT_LEVEL          1238
#define IDC_BUTTON_SUBJECT_LEVEL        1239
#define IDC_EDIT_SUBJECT_JOBLEVEL       1240
#define IDC_BUTTON_SUBJECT_JOBLEVEL     1241
#define IDC_EDIT_SUBJECT_TYPE           1242
#define IDC_EDIT_SUBJECT_RADIO          1243
#define IDC_LIST_SUBJECT                1244
#define IDC_BUTTON_SUBJECT              1245
#define IDC_EDIT_TG_TG_ADDCHARTYPE      1245
#define IDC_BUTTON_TG_TG_ADDCHAR        1246
#define IDC_LIST_TG_TG_CHARTYPE         1247
#define IDC_STATIC_INFINITY_MON         1248
#define IDC_STATIC_KILL_ALL_MONSTER     1249
#define ID_Menu                         32771
#define IDC_EXPAND_ALL_TREE             32772
#define ID_COLLAPSE_ALL_ENTIRE_TREE     32773
#define ID_ADD_CHILD                    32774
#define ID_ADD_SIBLING                  32775
#define ID_RENAME                       32776
#define ID_DELETE_ITEM                  32777
#define ID_DELETE_ALL_ITEMS             32778
#define ID_SORT_SUBTREE_ALPHABETIC      32779
#define ID_SORT_SUBTREE_NUMERIC         32780
#define IDC_COUNT_SUBTREE               32781
#define IDC_COUNT_ENTIRE_TREE           32782
#define ID_CALCULATE_LEVEL              32783
#define ID_ZOOM                         32784
#define ID_HOMEPAGE                     32785
#define ID_BUTTON32786                  32786
#define ID_BUTTON32787                  32787
#define ID_BUTTON32788                  32788
#define ID_BUTTON32789                  32789
#define ID_BUTTON32790                  32790
#define ID_BUTTON32791                  32791
#define ID_BUTTON32792                  32792
#define ID_BUTTON32793                  32793
#define ID_BUTTON32794                  32794
#define ID_BUTTON32796                  32796
#define ID_BUTTON32797                  32797
#define ID_BUTTON32798                  32798
#define ID_BUTTON32801                  32801
#define ID_BUTTON32802                  32802
#define ID_BUTTON32803                  32803
#define ID_BUTTON32804                  32804
#define ID_ADDCHILD_Q                   32805
#define ID_SIBLINGCHILD_Q               32806
#define ID_REMARK_Q                     32807
#define ID_DELETESUBTREE_Q              32808
#define ID_DELETEENTIRETREE_Q           32809
#define Info                            32810
#define ID_INFO_STRUCT                  32812
#define ID_SAVE_TO_FILE                 32814
#define ID_LOAD_FROM_FILE               32819
#define ID_LOAD_FROM_FILE_FULL          32821
#define ID_TREE_CUT                     32822
#define ID_TREE_COPY                    32823
#define ID_TREE_PASTE                   32824
#define ID_TREE_INFO                    32825
#define ID_TREE_REDRAW                  32826
#define ID_TREE_OPEN_CLOSE              32827
#define ID_SVAE_TO_FILE_FULL            32829
#define ID_TREE_NEW                     32832
#define ID_EDIT_REFRESH                 32834
#define ID_CHANGE_SEQUENCE              32838
#define ID_DELETE_ID                    32841
#define ID_TG_CUT                       32855
#define ID_TG_DELETE                    32856
#define ID_TG_ADD_EVENT                 32857
#define ID_TG_ADD_CONDITION             32858
#define ID_TG_ADD_ACTION                32859
#define ID_TG_COPY                      32860
#define ID_TG_PASTE                     32861
#define ID__ADD                         32862
#define ID_USE                          32864
#define ID_TGCT_CUT                     32873
#define ID_TGCT_COPY                    32874
#define ID_TGCT_DELETE                  32875
#define ID_TGCT_PASTE                   32876
#define ID_TGCT_USE                     32877
#define ID_TG_ADD_CATEGORY              32879
#define ID_TG_ADD_TRIGGER               32880
#define ID_TG_USE                       32881
#define ID_TG_START_WITH_USE            32882
#define ID_TGCT_START_WITH_USE          32883
#define ID_CUSTOM_DIRECTORY             32889
#define ID_TGCT_ADD_POPUP_ACTION        -32643
#define ID_TGCT_ADD_POPUP_CONDITION     -32642
#define ID_TGCT_ADD_POPUP_EVENT         -32641
#define ID_FILE_RECENT                  32897
#define ID_FILELIST                     32899
#define ID_FILE_SAVETOSERVERSCRIPT_BY_QUESTSIGN 32902
#define ID_SVAE_TO_SAME_FILE_FULL       32904
#define ID_FILE_AUTOSAVE                32907
#define ID_FILE_SAVETOSERVERSCRIPT      32908
#define ID_FILE_SAVETOSERVERSCRIPT_BY_SUBJECT 32909

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        187
#define _APS_NEXT_COMMAND_VALUE         32910
#define _APS_NEXT_CONTROL_VALUE         1250
#define _APS_NEXT_SYMED_VALUE           112
#endif
#endif
