_ENUM( EVENT_HEART_BIT = 0 )        // 사용안함
_ENUM( EVENT_ACCEPT_CONNECTION_NOT = 1 )

_ENUM( EVENT_VERSION_CHECK_REQ )
_ENUM( EVENT_VERSION_CHECK_ACK )
_ENUM( EVENT_VERIFY_OPERATOR_REQ )
_ENUM( EVENT_VERIFY_OPERATOR_ACK )
_ENUM( EVENT_KICK_USER_REQ )            // 5

_ENUM( EVENT_KICK_USER_ACK )            
_ENUM( EVENT_GET_USER_NUM_REQ )
_ENUM( EVENT_GET_USER_NUM_ACK )
_ENUM( EVENT_NOTIFY_MSG_NOT )
_ENUM( EVENT_WHERE_USER_REQ )           // 10

_ENUM( EVENT_WHERE_USER_ACK )
_ENUM( EVENT_MODIFY_USER_INFO_REQ )
_ENUM( EVENT_MODIFY_USER_INFO_ACK )
_ENUM( EVENT_COMFIRM_USER_INFO_REQ )
_ENUM( EVENT_COMFIRM_USER_INFO_ACK )    // 15

_ENUM( EVENT_CLOSE_CONNECTION_NOT )

_ENUM( EVENT_EVENTID_SENTINEL )
