/* soapClient.c
   Generated by gSOAP 2.8.11 from GCSoap.h

Copyright(C) 2000-2012, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) soapClient.c ver 2.8.11 2012-11-06 07:34:50 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__AuthenticateUser(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__AuthenticateUser *ns1__AuthenticateUser, struct _ns1__AuthenticateUserResponse *ns1__AuthenticateUserResponse)
{	struct __ns1__AuthenticateUser soap_tmp___ns1__AuthenticateUser;
	if (!soap_endpoint)
		soap_endpoint = "http://auth.axeso5.com/webservice/axeso5WSv3.asmx";
	if (!soap_action)
		soap_action = "http://www.axeso5.com/webservice/AuthenticateUser";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__AuthenticateUser.ns1__AuthenticateUser = ns1__AuthenticateUser;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__AuthenticateUser(soap, &soap_tmp___ns1__AuthenticateUser);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__AuthenticateUser(soap, &soap_tmp___ns1__AuthenticateUser, "-ns1:AuthenticateUser", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__AuthenticateUser(soap, &soap_tmp___ns1__AuthenticateUser, "-ns1:AuthenticateUser", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__AuthenticateUserResponse)
		return soap_closesock(soap);
	soap_default__ns1__AuthenticateUserResponse(soap, ns1__AuthenticateUserResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__AuthenticateUserResponse(soap, ns1__AuthenticateUserResponse, "ns1:AuthenticateUserResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__AuthenticateUser_(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__AuthenticateUser *ns1__AuthenticateUser, struct _ns1__AuthenticateUserResponse *ns1__AuthenticateUserResponse)
{	struct __ns1__AuthenticateUser_ soap_tmp___ns1__AuthenticateUser_;
	if (!soap_endpoint)
		soap_endpoint = "http://auth.axeso5.com/webservice/axeso5WSv3.asmx";
	if (!soap_action)
		soap_action = "http://www.axeso5.com/webservice/AuthenticateUser";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__AuthenticateUser_.ns1__AuthenticateUser = ns1__AuthenticateUser;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__AuthenticateUser_(soap, &soap_tmp___ns1__AuthenticateUser_);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__AuthenticateUser_(soap, &soap_tmp___ns1__AuthenticateUser_, "-ns1:AuthenticateUser", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__AuthenticateUser_(soap, &soap_tmp___ns1__AuthenticateUser_, "-ns1:AuthenticateUser", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__AuthenticateUserResponse)
		return soap_closesock(soap);
	soap_default__ns1__AuthenticateUserResponse(soap, ns1__AuthenticateUserResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__AuthenticateUserResponse(soap, ns1__AuthenticateUserResponse, "ns1:AuthenticateUserResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

#ifdef __cplusplus
}
#endif

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapClient.c */
