SetEnchantAction( KGSDBLayer.FIRE, KGSDBLayer.Level1, 100,  0, 0 )
SetEnchantAction( KGSDBLayer.FIRE, KGSDBLayer.Level2,  50,  0, 0 )
SetEnchantAction( KGSDBLayer.FIRE, KGSDBLayer.Level3,  40,  0, 0 )
SetEnchantAction( KGSDBLayer.FIRE, KGSDBLayer.Level4,  30,  0, 0 )
SetEnchantAction( KGSDBLayer.FIRE, KGSDBLayer.Level5,  30, 20, 0 )
SetEnchantAction( KGSDBLayer.FIRE, KGSDBLayer.Level6,  30, 20, 0 )
SetEnchantAction( KGSDBLayer.FIRE, KGSDBLayer.Level7,  13,  0, 0 )
SetEnchantAction( KGSDBLayer.FIRE, KGSDBLayer.Level8,   7, 30, 0 )
SetEnchantAction( KGSDBLayer.FIRE, KGSDBLayer.Level9,   2, 30, 0 )

SetEnchantAction( KGSDBLayer.ICE,  KGSDBLayer.Level1, 100,  0, 0 )
SetEnchantAction( KGSDBLayer.ICE,  KGSDBLayer.Level2,  50,  0, 0 )
SetEnchantAction( KGSDBLayer.ICE,  KGSDBLayer.Level3,  40,  0, 0 )
SetEnchantAction( KGSDBLayer.ICE,  KGSDBLayer.Level4,  30,  0, 0 )
SetEnchantAction( KGSDBLayer.ICE,  KGSDBLayer.Level5,  30, 20, 0 )
SetEnchantAction( KGSDBLayer.ICE,  KGSDBLayer.Level6,  30, 20, 0 )
SetEnchantAction( KGSDBLayer.ICE,  KGSDBLayer.Level7,  13,  0, 0 )
SetEnchantAction( KGSDBLayer.ICE,  KGSDBLayer.Level8,   7, 30, 0 )
SetEnchantAction( KGSDBLayer.ICE,  KGSDBLayer.Level9,   2, 30, 0 )

SetEnchantAction( KGSDBLayer.LIGHT,  KGSDBLayer.Level1, 100,  0, 0 )
SetEnchantAction( KGSDBLayer.LIGHT,  KGSDBLayer.Level2,  50,  0, 0 )
SetEnchantAction( KGSDBLayer.LIGHT,  KGSDBLayer.Level3,  40,  0, 0 )
SetEnchantAction( KGSDBLayer.LIGHT,  KGSDBLayer.Level4,  30,  0, 0 )
SetEnchantAction( KGSDBLayer.LIGHT,  KGSDBLayer.Level5,  30, 30, 0 )
SetEnchantAction( KGSDBLayer.LIGHT,  KGSDBLayer.Level6,  30, 30, 0 )
SetEnchantAction( KGSDBLayer.LIGHT,  KGSDBLayer.Level7,  20,  0, 0 )
SetEnchantAction( KGSDBLayer.LIGHT,  KGSDBLayer.Level8,  10, 30, 0 )
SetEnchantAction( KGSDBLayer.LIGHT,  KGSDBLayer.Level9,   2, 30, 0 )

SetEnchantAction( KGSDBLayer.DARK,  KGSDBLayer.Level1, 100,  0, 0 )
SetEnchantAction( KGSDBLayer.DARK,  KGSDBLayer.Level2,  50,  0, 0 )
SetEnchantAction( KGSDBLayer.DARK,  KGSDBLayer.Level3,  40,  0, 0 )
SetEnchantAction( KGSDBLayer.DARK,  KGSDBLayer.Level4,  30,  0, 0 )
SetEnchantAction( KGSDBLayer.DARK,  KGSDBLayer.Level5,  30, 30, 0 )
SetEnchantAction( KGSDBLayer.DARK,  KGSDBLayer.Level6,  30, 30, 0 )
SetEnchantAction( KGSDBLayer.DARK,  KGSDBLayer.Level7,  20,  0, 0 )
SetEnchantAction( KGSDBLayer.DARK,  KGSDBLayer.Level8,  10, 30, 0 )
SetEnchantAction( KGSDBLayer.DARK,  KGSDBLayer.Level9,   2, 30, 0 )

SetEnchantAction( KGSDBLayer.WIND,  KGSDBLayer.Level1, 100,  0,  0 )
SetEnchantAction( KGSDBLayer.WIND,  KGSDBLayer.Level2,  50,  0,  0 )
SetEnchantAction( KGSDBLayer.WIND,  KGSDBLayer.Level3,  40,  0,  0 )
SetEnchantAction( KGSDBLayer.WIND,  KGSDBLayer.Level4,  30,  0,  0 )
SetEnchantAction( KGSDBLayer.WIND,  KGSDBLayer.Level5,  30, 30,  0 )
SetEnchantAction( KGSDBLayer.WIND,  KGSDBLayer.Level6,  30, 30,  0 )
SetEnchantAction( KGSDBLayer.WIND,  KGSDBLayer.Level7,  20,  0, 15 )
SetEnchantAction( KGSDBLayer.WIND,  KGSDBLayer.Level8,  10,  0, 15 )
SetEnchantAction( KGSDBLayer.WIND,  KGSDBLayer.Level9,  10,  0, 20 )

SetEnchantAction( KGSDBLayer.CASH_SHIELD,  KGSDBLayer.Level1, 100,  0,  0 )
SetEnchantAction( KGSDBLayer.CASH_SHIELD,  KGSDBLayer.Level2,  50,  0,  0 )
SetEnchantAction( KGSDBLayer.CASH_SHIELD,  KGSDBLayer.Level3,  40,  0,  0 )
SetEnchantAction( KGSDBLayer.CASH_SHIELD,  KGSDBLayer.Level4,  30,  0,  0 )
SetEnchantAction( KGSDBLayer.CASH_SHIELD,  KGSDBLayer.Level5,  30, 30,  0 )
SetEnchantAction( KGSDBLayer.CASH_SHIELD,  KGSDBLayer.Level6,  30, 30,  0 )
SetEnchantAction( KGSDBLayer.CASH_SHIELD,  KGSDBLayer.Level7,  20,  0,  0 )
SetEnchantAction( KGSDBLayer.CASH_SHIELD,  KGSDBLayer.Level8,  10, 30,  0 )
SetEnchantAction( KGSDBLayer.CASH_SHIELD,  KGSDBLayer.Level9,   2, 30,  0 )

SetEnchantAction( KGSDBLayer.GP_SHIELD,  KGSDBLayer.Level1, 100,  0,  0 )
SetEnchantAction( KGSDBLayer.GP_SHIELD,  KGSDBLayer.Level2,  50,  0,  0 )
SetEnchantAction( KGSDBLayer.GP_SHIELD,  KGSDBLayer.Level3,  40,  0,  0 )
SetEnchantAction( KGSDBLayer.GP_SHIELD,  KGSDBLayer.Level4,  30,  0,  0 )
SetEnchantAction( KGSDBLayer.GP_SHIELD,  KGSDBLayer.Level5,  30, 30,  0 )
SetEnchantAction( KGSDBLayer.GP_SHIELD,  KGSDBLayer.Level6,  30, 30,  0 )
SetEnchantAction( KGSDBLayer.GP_SHIELD,  KGSDBLayer.Level7,  20,  0, 15 )
SetEnchantAction( KGSDBLayer.GP_SHIELD,  KGSDBLayer.Level8,  10,  0, 15 )
SetEnchantAction( KGSDBLayer.GP_SHIELD,  KGSDBLayer.Level9,  10,  0, 20 )

SetEnchantGemCount{ 1, 2, 2, 2, 2, 3, 3, 3, 3, }		-- 강화에 필요한 젬 수량
