TRUE = 1
FALSE = 0
True = 1
False = 0
Condition = {	{
		ID = 0,
		Win = True,
		Time = -1,
		DifficultRange = {3,-1},
		MonsterKill = -1,
		Mode = 9,
		Stage = -1,
		ScoreRange = {-1,-1},
		IsSolo = False,
		MapID = -1,
		Kill = -1,
		Die = -1,
		ExLife = -1,
		ConditionActiveRatio = 1,
	},
	{
		ID = 1,
		Win = True,
		Time = -1,
		DifficultRange = {3,-1},
		MonsterKill = -1,
		Mode = 10,
		Stage = -1,
		ScoreRange = {-1,-1},
		IsSolo = False,
		MapID = -1,
		Kill = -1,
		Die = -1,
		ExLife = -1,
		ConditionActiveRatio = 1,
	},
	{
		ID = 2,
		Win = True,
		Time = -1,
		DifficultRange = {3,-1},
		MonsterKill = -1,
		Mode = 11,
		Stage = -1,
		ScoreRange = {-1,-1},
		IsSolo = False,
		MapID = -1,
		Kill = -1,
		Die = -1,
		ExLife = -1,
		ConditionActiveRatio = 1,
	},
	{
		ID = 3,
		Win = True,
		Time = -1,
		DifficultRange = {3,-1},
		MonsterKill = -1,
		Mode = 12,
		Stage = -1,
		ScoreRange = {-1,-1},
		IsSolo = False,
		MapID = -1,
		Kill = -1,
		Die = -1,
		ExLife = -1,
		ConditionActiveRatio = 1,
	},
	{
		ID = 4,
		Win = True,
		Time = -1,
		DifficultRange = {3,-1},
		MonsterKill = -1,
		Mode = 13,
		Stage = -1,
		ScoreRange = {-1,-1},
		IsSolo = False,
		MapID = -1,
		Kill = -1,
		Die = -1,
		ExLife = -1,
		ConditionActiveRatio = 1,
	},
	{
		ID = 5,
		Win = True,
		Time = -1,
		DifficultRange = {3,-1},
		MonsterKill = -1,
		Mode = 14,
		Stage = -1,
		ScoreRange = {-1,-1},
		IsSolo = False,
		MapID = -1,
		Kill = -1,
		Die = -1,
		ExLife = -1,
		ConditionActiveRatio = 1,
	},
	{
		ID = 6,
		Win = True,
		Time = -1,
		DifficultRange = {3,-1},
		MonsterKill = -1,
		Mode = 15,
		Stage = -1,
		ScoreRange = {-1,-1},
		IsSolo = False,
		MapID = -1,
		Kill = -1,
		Die = -1,
		ExLife = -1,
		ConditionActiveRatio = 1,
	},
	{
		ID = 7,
		Win = True,
		Time = -1,
		DifficultRange = {3,-1},
		MonsterKill = -1,
		Mode = 16,
		Stage = -1,
		ScoreRange = {-1,-1},
		IsSolo = False,
		MapID = -1,
		Kill = -1,
		Die = -1,
		ExLife = -1,
		ConditionActiveRatio = 1,
	},
	{
		ID = 8,
		Win = True,
		Time = -1,
		DifficultRange = {3,-1},
		MonsterKill = -1,
		Mode = 17,
		Stage = -1,
		ScoreRange = {-1,-1},
		IsSolo = False,
		MapID = -1,
		Kill = -1,
		Die = -1,
		ExLife = -1,
		ConditionActiveRatio = 1,
	},
	{
		ID = 9,
		Win = True,
		Time = -1,
		DifficultRange = {3,-1},
		MonsterKill = -1,
		Mode = 18,
		Stage = -1,
		ScoreRange = {-1,-1},
		IsSolo = False,
		MapID = -1,
		Kill = -1,
		Die = -1,
		ExLife = -1,
		ConditionActiveRatio = 1,
	},
	{
		ID = 10,
		Win = True,
		Time = -1,
		DifficultRange = {3,-1},
		MonsterKill = -1,
		Mode = 19,
		Stage = -1,
		ScoreRange = {-1,-1},
		IsSolo = False,
		MapID = -1,
		Kill = -1,
		Die = -1,
		ExLife = -1,
		ConditionActiveRatio = 1,
	},
	{
		ID = 11,
		Win = True,
		Time = -1,
		DifficultRange = {3,-1},
		MonsterKill = -1,
		Mode = 20,
		Stage = -1,
		ScoreRange = {-1,-1},
		IsSolo = False,
		MapID = -1,
		Kill = -1,
		Die = -1,
		ExLife = -1,
		ConditionActiveRatio = 1,
	},
	{
		ID = 12,
		Win = True,
		Time = -1,
		DifficultRange = {3,-1},
		MonsterKill = -1,
		Mode = 21,
		Stage = -1,
		ScoreRange = {-1,-1},
		IsSolo = False,
		MapID = -1,
		Kill = -1,
		Die = -1,
		ExLife = -1,
		ConditionActiveRatio = 1,
	},
	{
		ID = 13,
		Win = True,
		Time = -1,
		DifficultRange = {3,-1},
		MonsterKill = -1,
		Mode = 22,
		Stage = -1,
		ScoreRange = {-1,-1},
		IsSolo = False,
		MapID = -1,
		Kill = -1,
		Die = -1,
		ExLife = -1,
		ConditionActiveRatio = 1,
	},
	{
		ID = 14,
		Win = True,
		Time = -1,
		DifficultRange = {3,-1},
		MonsterKill = -1,
		Mode = 23,
		Stage = -1,
		ScoreRange = {-1,-1},
		IsSolo = False,
		MapID = -1,
		Kill = -1,
		Die = -1,
		ExLife = -1,
		ConditionActiveRatio = 1,
	},
	{
		ID = 15,
		Win = True,
		Time = -1,
		DifficultRange = {3,-1},
		MonsterKill = -1,
		Mode = 24,
		Stage = -1,
		ScoreRange = {-1,-1},
		IsSolo = False,
		MapID = -1,
		Kill = -1,
		Die = -1,
		ExLife = -1,
		ConditionActiveRatio = 1,
	},
	{
		ID = 16,
		Win = True,
		Time = -1,
		DifficultRange = {3,-1},
		MonsterKill = -1,
		Mode = 25,
		Stage = -1,
		ScoreRange = {-1,-1},
		IsSolo = False,
		MapID = -1,
		Kill = -1,
		Die = -1,
		ExLife = -1,
		ConditionActiveRatio = 1,
	},
	{
		ID = 17,
		Win = True,
		Time = -1,
		DifficultRange = {3,-1},
		MonsterKill = -1,
		Mode = 26,
		Stage = -1,
		ScoreRange = {-1,-1},
		IsSolo = False,
		MapID = -1,
		Kill = -1,
		Die = -1,
		ExLife = -1,
		ConditionActiveRatio = 1,
	},
	{
		ID = 18,
		Win = True,
		Time = -1,
		DifficultRange = {3,-1},
		MonsterKill = -1,
		Mode = 27,
		Stage = -1,
		ScoreRange = {-1,-1},
		IsSolo = False,
		MapID = -1,
		Kill = -1,
		Die = -1,
		ExLife = -1,
		ConditionActiveRatio = 1,
	},
	{
		ID = 19,
		Win = True,
		Time = -1,
		DifficultRange = {3,-1},
		MonsterKill = -1,
		Mode = 30,
		Stage = -1,
		ScoreRange = {-1,-1},
		IsSolo = False,
		MapID = -1,
		Kill = -1,
		Die = -1,
		ExLife = -1,
		ConditionActiveRatio = 1,
	},
	{
		ID = 20,
		Win = True,
		Time = -1,
		DifficultRange = {3,-1},
		MonsterKill = -1,
		Mode = 9,
		Stage = -1,
		ScoreRange = {-1,-1},
		IsSolo = False,
		MapID = -1,
		Kill = -1,
		Die = -1,
		ExLife = -1,
		ConditionActiveRatio = 1,
	},
	{
		ID = 21,
		Win = True,
		Time = -1,
		DifficultRange = {3,-1},
		MonsterKill = -1,
		Mode = 10,
		Stage = -1,
		ScoreRange = {-1,-1},
		IsSolo = False,
		MapID = -1,
		Kill = -1,
		Die = -1,
		ExLife = -1,
		ConditionActiveRatio = 1,
	},
	{
		ID = 22,
		Win = True,
		Time = -1,
		DifficultRange = {2,-1},
		MonsterKill = -1,
		Mode = 9,
		Stage = -1,
		ScoreRange = {-1,-1},
		IsSolo = False,
		MapID = -1,
		Kill = -1,
		Die = -1,
		ExLife = -1,
		ConditionActiveRatio = 1,
	},
	{
		ID = 23,
		Win = True,
		Time = -1,
		DifficultRange = {2,-1},
		MonsterKill = -1,
		Mode = 10,
		Stage = -1,
		ScoreRange = {-1,-1},
		IsSolo = False,
		MapID = -1,
		Kill = -1,
		Die = -1,
		ExLife = -1,
		ConditionActiveRatio = 1,
	},
	{
		ID = 24,
		Win = True,
		Time = -1,
		DifficultRange = {2,-1},
		MonsterKill = -1,
		Mode = 11,
		Stage = -1,
		ScoreRange = {-1,-1},
		IsSolo = False,
		MapID = -1,
		Kill = -1,
		Die = -1,
		ExLife = -1,
		ConditionActiveRatio = 1,
	},
	{
		ID = 25,
		Win = True,
		Time = -1,
		DifficultRange = {2,-1},
		MonsterKill = -1,
		Mode = 12,
		Stage = -1,
		ScoreRange = {-1,-1},
		IsSolo = False,
		MapID = -1,
		Kill = -1,
		Die = -1,
		ExLife = -1,
		ConditionActiveRatio = 1,
	},
	{
		ID = 26,
		Win = True,
		Time = -1,
		DifficultRange = {2,-1},
		MonsterKill = -1,
		Mode = 13,
		Stage = -1,
		ScoreRange = {-1,-1},
		IsSolo = False,
		MapID = -1,
		Kill = -1,
		Die = -1,
		ExLife = -1,
		ConditionActiveRatio = 1,
	},
	{
		ID = 27,
		Win = True,
		Time = -1,
		DifficultRange = {2,-1},
		MonsterKill = -1,
		Mode = 14,
		Stage = -1,
		ScoreRange = {-1,-1},
		IsSolo = False,
		MapID = -1,
		Kill = -1,
		Die = -1,
		ExLife = -1,
		ConditionActiveRatio = 1,
	},
	{
		ID = 28,
		Win = True,
		Time = -1,
		DifficultRange = {2,-1},
		MonsterKill = -1,
		Mode = 15,
		Stage = -1,
		ScoreRange = {-1,-1},
		IsSolo = False,
		MapID = -1,
		Kill = -1,
		Die = -1,
		ExLife = -1,
		ConditionActiveRatio = 1,
	},
	{
		ID = 29,
		Win = True,
		Time = -1,
		DifficultRange = {2,-1},
		MonsterKill = -1,
		Mode = 16,
		Stage = -1,
		ScoreRange = {-1,-1},
		IsSolo = False,
		MapID = -1,
		Kill = -1,
		Die = -1,
		ExLife = -1,
		ConditionActiveRatio = 1,
	},
	{
		ID = 30,
		Win = True,
		Time = -1,
		DifficultRange = {2,-1},
		MonsterKill = -1,
		Mode = 17,
		Stage = -1,
		ScoreRange = {-1,-1},
		IsSolo = False,
		MapID = -1,
		Kill = -1,
		Die = -1,
		ExLife = -1,
		ConditionActiveRatio = 1,
	},
	{
		ID = 31,
		Win = True,
		Time = -1,
		DifficultRange = {2,-1},
		MonsterKill = -1,
		Mode = 18,
		Stage = -1,
		ScoreRange = {-1,-1},
		IsSolo = False,
		MapID = -1,
		Kill = -1,
		Die = -1,
		ExLife = -1,
		ConditionActiveRatio = 1,
	},
	{
		ID = 32,
		Win = True,
		Time = -1,
		DifficultRange = {2,-1},
		MonsterKill = -1,
		Mode = 19,
		Stage = -1,
		ScoreRange = {-1,-1},
		IsSolo = False,
		MapID = -1,
		Kill = -1,
		Die = -1,
		ExLife = -1,
		ConditionActiveRatio = 1,
	},
	{
		ID = 33,
		Win = True,
		Time = -1,
		DifficultRange = {2,-1},
		MonsterKill = -1,
		Mode = 20,
		Stage = -1,
		ScoreRange = {-1,-1},
		IsSolo = False,
		MapID = -1,
		Kill = -1,
		Die = -1,
		ExLife = -1,
		ConditionActiveRatio = 1,
	},
	{
		ID = 34,
		Win = True,
		Time = -1,
		DifficultRange = {2,-1},
		MonsterKill = -1,
		Mode = 21,
		Stage = -1,
		ScoreRange = {-1,-1},
		IsSolo = False,
		MapID = -1,
		Kill = -1,
		Die = -1,
		ExLife = -1,
		ConditionActiveRatio = 1,
	},
	{
		ID = 35,
		Win = True,
		Time = -1,
		DifficultRange = {2,-1},
		MonsterKill = -1,
		Mode = 22,
		Stage = -1,
		ScoreRange = {-1,-1},
		IsSolo = False,
		MapID = -1,
		Kill = -1,
		Die = -1,
		ExLife = -1,
		ConditionActiveRatio = 1,
	},
	{
		ID = 36,
		Win = True,
		Time = -1,
		DifficultRange = {2,-1},
		MonsterKill = -1,
		Mode = 23,
		Stage = -1,
		ScoreRange = {-1,-1},
		IsSolo = False,
		MapID = -1,
		Kill = -1,
		Die = -1,
		ExLife = -1,
		ConditionActiveRatio = 1,
	},
	{
		ID = 37,
		Win = True,
		Time = -1,
		DifficultRange = {2,-1},
		MonsterKill = -1,
		Mode = 24,
		Stage = -1,
		ScoreRange = {-1,-1},
		IsSolo = False,
		MapID = -1,
		Kill = -1,
		Die = -1,
		ExLife = -1,
		ConditionActiveRatio = 1,
	},
	{
		ID = 38,
		Win = True,
		Time = -1,
		DifficultRange = {2,-1},
		MonsterKill = -1,
		Mode = 25,
		Stage = -1,
		ScoreRange = {-1,-1},
		IsSolo = False,
		MapID = -1,
		Kill = -1,
		Die = -1,
		ExLife = -1,
		ConditionActiveRatio = 1,
	},
	{
		ID = 39,
		Win = True,
		Time = -1,
		DifficultRange = {2,-1},
		MonsterKill = -1,
		Mode = 26,
		Stage = -1,
		ScoreRange = {-1,-1},
		IsSolo = False,
		MapID = -1,
		Kill = -1,
		Die = -1,
		ExLife = -1,
		ConditionActiveRatio = 1,
	},
	{
		ID = 40,
		Win = True,
		Time = -1,
		DifficultRange = {2,-1},
		MonsterKill = -1,
		Mode = 27,
		Stage = -1,
		ScoreRange = {-1,-1},
		IsSolo = False,
		MapID = -1,
		Kill = -1,
		Die = -1,
		ExLife = -1,
		ConditionActiveRatio = 1,
	},
	{
		ID = 41,
		Win = True,
		Time = -1,
		DifficultRange = {2,-1},
		MonsterKill = -1,
		Mode = 30,
		Stage = -1,
		ScoreRange = {-1,-1},
		IsSolo = False,
		MapID = -1,
		Kill = -1,
		Die = -1,
		ExLife = -1,
		ConditionActiveRatio = 1,
	},
	{
		ID = 42,
		Win = True,
		Time = -1,
		DifficultRange = {3,-1},
		MonsterKill = 6,
		Mode = 9,
		Stage = -1,
		ScoreRange = {-1,-1},
		IsSolo = False,
		MapID = -1,
		Kill = -1,
		Die = -1,
		ExLife = -1,
		ConditionActiveRatio = 1,
	},
	{
		ID = 43,
		Win = True,
		Time = -1,
		DifficultRange = {3,-1},
		MonsterKill = 28,
		Mode = 10,
		Stage = -1,
		ScoreRange = {-1,-1},
		IsSolo = False,
		MapID = -1,
		Kill = -1,
		Die = -1,
		ExLife = -1,
		ConditionActiveRatio = 1,
	},
	{
		ID = 44,
		Win = True,
		Time = -1,
		DifficultRange = {3,-1},
		MonsterKill = 30,
		Mode = 11,
		Stage = -1,
		ScoreRange = {-1,-1},
		IsSolo = False,
		MapID = -1,
		Kill = -1,
		Die = -1,
		ExLife = -1,
		ConditionActiveRatio = 1,
	},
	{
		ID = 45,
		Win = True,
		Time = -1,
		DifficultRange = {3,-1},
		MonsterKill = 34,
		Mode = 12,
		Stage = -1,
		ScoreRange = {-1,-1},
		IsSolo = False,
		MapID = -1,
		Kill = -1,
		Die = -1,
		ExLife = -1,
		ConditionActiveRatio = 1,
	},
	{
		ID = 46,
		Win = True,
		Time = -1,
		DifficultRange = {3,-1},
		MonsterKill = 31,
		Mode = 13,
		Stage = -1,
		ScoreRange = {-1,-1},
		IsSolo = False,
		MapID = -1,
		Kill = -1,
		Die = -1,
		ExLife = -1,
		ConditionActiveRatio = 1,
	},
	{
		ID = 47,
		Win = True,
		Time = -1,
		DifficultRange = {3,-1},
		MonsterKill = 36,
		Mode = 14,
		Stage = -1,
		ScoreRange = {-1,-1},
		IsSolo = False,
		MapID = -1,
		Kill = -1,
		Die = -1,
		ExLife = -1,
		ConditionActiveRatio = 1,
	},
	{
		ID = 48,
		Win = True,
		Time = -1,
		DifficultRange = {3,-1},
		MonsterKill = 54,
		Mode = 15,
		Stage = -1,
		ScoreRange = {-1,-1},
		IsSolo = False,
		MapID = -1,
		Kill = -1,
		Die = -1,
		ExLife = -1,
		ConditionActiveRatio = 1,
	},
	{
		ID = 49,
		Win = True,
		Time = -1,
		DifficultRange = {3,-1},
		MonsterKill = 55,
		Mode = 16,
		Stage = -1,
		ScoreRange = {-1,-1},
		IsSolo = False,
		MapID = -1,
		Kill = -1,
		Die = -1,
		ExLife = -1,
		ConditionActiveRatio = 1,
	},
	{
		ID = 50,
		Win = True,
		Time = -1,
		DifficultRange = {3,-1},
		MonsterKill = 45,
		Mode = 17,
		Stage = -1,
		ScoreRange = {-1,-1},
		IsSolo = False,
		MapID = -1,
		Kill = -1,
		Die = -1,
		ExLife = -1,
		ConditionActiveRatio = 1,
	},
	{
		ID = 51,
		Win = True,
		Time = -1,
		DifficultRange = {3,-1},
		MonsterKill = 47,
		Mode = 18,
		Stage = -1,
		ScoreRange = {-1,-1},
		IsSolo = False,
		MapID = -1,
		Kill = -1,
		Die = -1,
		ExLife = -1,
		ConditionActiveRatio = 1,
	},
	{
		ID = 52,
		Win = True,
		Time = -1,
		DifficultRange = {3,-1},
		MonsterKill = 14,
		Mode = 19,
		Stage = -1,
		ScoreRange = {-1,-1},
		IsSolo = False,
		MapID = -1,
		Kill = -1,
		Die = -1,
		ExLife = -1,
		ConditionActiveRatio = 1,
	},
	{
		ID = 53,
		Win = True,
		Time = -1,
		DifficultRange = {3,-1},
		MonsterKill = 49,
		Mode = 20,
		Stage = -1,
		ScoreRange = {-1,-1},
		IsSolo = False,
		MapID = -1,
		Kill = -1,
		Die = -1,
		ExLife = -1,
		ConditionActiveRatio = 1,
	},
	{
		ID = 54,
		Win = True,
		Time = -1,
		DifficultRange = {3,-1},
		MonsterKill = 46,
		Mode = 21,
		Stage = -1,
		ScoreRange = {-1,-1},
		IsSolo = False,
		MapID = -1,
		Kill = -1,
		Die = -1,
		ExLife = -1,
		ConditionActiveRatio = 1,
	},
	{
		ID = 55,
		Win = True,
		Time = -1,
		DifficultRange = {3,-1},
		MonsterKill = 58,
		Mode = 22,
		Stage = -1,
		ScoreRange = {-1,-1},
		IsSolo = False,
		MapID = -1,
		Kill = -1,
		Die = -1,
		ExLife = -1,
		ConditionActiveRatio = 1,
	},
	{
		ID = 56,
		Win = True,
		Time = -1,
		DifficultRange = {3,-1},
		MonsterKill = 57,
		Mode = 23,
		Stage = -1,
		ScoreRange = {-1,-1},
		IsSolo = False,
		MapID = -1,
		Kill = -1,
		Die = -1,
		ExLife = -1,
		ConditionActiveRatio = 1,
	},
	{
		ID = 57,
		Win = True,
		Time = -1,
		DifficultRange = {3,-1},
		MonsterKill = 16,
		Mode = 24,
		Stage = -1,
		ScoreRange = {-1,-1},
		IsSolo = False,
		MapID = -1,
		Kill = -1,
		Die = -1,
		ExLife = -1,
		ConditionActiveRatio = 1,
	},
	{
		ID = 58,
		Win = True,
		Time = -1,
		DifficultRange = {3,-1},
		MonsterKill = 18,
		Mode = 25,
		Stage = -1,
		ScoreRange = {-1,-1},
		IsSolo = False,
		MapID = -1,
		Kill = -1,
		Die = -1,
		ExLife = -1,
		ConditionActiveRatio = 1,
	},
	{
		ID = 59,
		Win = True,
		Time = -1,
		DifficultRange = {3,-1},
		MonsterKill = 19,
		Mode = 26,
		Stage = -1,
		ScoreRange = {-1,-1},
		IsSolo = False,
		MapID = -1,
		Kill = -1,
		Die = -1,
		ExLife = -1,
		ConditionActiveRatio = 1,
	},
	{
		ID = 60,
		Win = True,
		Time = -1,
		DifficultRange = {3,-1},
		MonsterKill = 75,
		Mode = 27,
		Stage = -1,
		ScoreRange = {-1,-1},
		IsSolo = False,
		MapID = -1,
		Kill = -1,
		Die = -1,
		ExLife = -1,
		ConditionActiveRatio = 1,
	},
	{
		ID = 61,
		Win = True,
		Time = -1,
		DifficultRange = {3,-1},
		MonsterKill = 76,
		Mode = 27,
		Stage = -1,
		ScoreRange = {-1,-1},
		IsSolo = False,
		MapID = -1,
		Kill = -1,
		Die = -1,
		ExLife = -1,
		ConditionActiveRatio = 1,
	},
	{
		ID = 62,
		Win = True,
		Time = -1,
		DifficultRange = {3,-1},
		MonsterKill = 115,
		Mode = 30,
		Stage = -1,
		ScoreRange = {-1,-1},
		IsSolo = False,
		MapID = -1,
		Kill = -1,
		Die = -1,
		ExLife = -1,
		ConditionActiveRatio = 1,
	},
	{
		ID = 63,
		Win = True,
		Time = -1,
		DifficultRange = {3,-1},
		MonsterKill = -1,
		Mode = 36,
		Stage = -1,
		ScoreRange = {-1,-1},
		IsSolo = False,
		MapID = -1,
		Kill = -1,
		Die = -1,
		ExLife = -1,
		ConditionActiveRatio = 1,
	},
	{
		ID = 64,
		Win = True,
		Time = -1,
		DifficultRange = {3,-1},
		MonsterKill = -1,
		Mode = 39,
		Stage = -1,
		ScoreRange = {-1,-1},
		IsSolo = False,
		MapID = -1,
		Kill = -1,
		Die = -1,
		ExLife = -1,
		ConditionActiveRatio = 1,
	},
	{
		ID = 65,
		Win = True,
		Time = -1,
		DifficultRange = {3,-1},
		MonsterKill = -1,
		Mode = 40,
		Stage = -1,
		ScoreRange = {-1,-1},
		IsSolo = False,
		MapID = -1,
		Kill = -1,
		Die = -1,
		ExLife = -1,
		ConditionActiveRatio = 1,
	},
	{
		ID = 66,
		Win = True,
		Time = -1,
		DifficultRange = {3,-1},
		MonsterKill = -1,
		Mode = 41,
		Stage = -1,
		ScoreRange = {-1,-1},
		IsSolo = False,
		MapID = -1,
		Kill = -1,
		Die = -1,
		ExLife = -1,
		ConditionActiveRatio = 1,
	},
	{
		ID = 67,
		Win = True,
		Time = -1,
		DifficultRange = {3,-1},
		MonsterKill = -1,
		Mode = 42,
		Stage = -1,
		ScoreRange = {-1,-1},
		IsSolo = False,
		MapID = -1,
		Kill = -1,
		Die = -1,
		ExLife = -1,
		ConditionActiveRatio = 1,
	},
	{
		ID = 68,
		Win = True,
		Time = -1,
		DifficultRange = {3,-1},
		MonsterKill = -1,
		Mode = 43,
		Stage = -1,
		ScoreRange = {-1,-1},
		IsSolo = False,
		MapID = -1,
		Kill = -1,
		Die = -1,
		ExLife = -1,
		ConditionActiveRatio = 1,
	},
	{
		ID = 69,
		Win = True,
		Time = -1,
		DifficultRange = {3,-1},
		MonsterKill = -1,
		Mode = 44,
		Stage = -1,
		ScoreRange = {-1,-1},
		IsSolo = False,
		MapID = -1,
		Kill = -1,
		Die = -1,
		ExLife = -1,
		ConditionActiveRatio = 1,
	},
	{
		ID = 70,
		Win = True,
		Time = -1,
		DifficultRange = {3,-1},
		MonsterKill = -1,
		Mode = 47,
		Stage = -1,
		ScoreRange = {-1,-1},
		IsSolo = False,
		MapID = -1,
		Kill = -1,
		Die = -1,
		ExLife = -1,
		ConditionActiveRatio = 1,
	},
	{
		ID = 71,
		Win = True,
		Time = -1,
		DifficultRange = {3,-1},
		MonsterKill = -1,
		Mode = 45,
		Stage = -1,
		ScoreRange = {-1,-1},
		IsSolo = False,
		MapID = -1,
		Kill = -1,
		Die = -1,
		ExLife = -1,
		ConditionActiveRatio = 1,
	},
	{
		ID = 72,
		Win = True,
		Time = -1,
		DifficultRange = {3,-1},
		MonsterKill = -1,
		Mode = 48,
		Stage = -1,
		ScoreRange = {-1,-1},
		IsSolo = False,
		MapID = -1,
		Kill = -1,
		Die = -1,
		ExLife = -1,
		ConditionActiveRatio = 1,
	},
	{
		ID = 73,
		Win = True,
		Time = -1,
		DifficultRange = {3,-1},
		MonsterKill = -1,
		Mode = 46,
		Stage = -1,
		ScoreRange = {-1,-1},
		IsSolo = False,
		MapID = -1,
		Kill = -1,
		Die = -1,
		ExLife = -1,
		ConditionActiveRatio = 1,
	},
	{
		ID = 74,
		Win = True,
		Time = -1,
		DifficultRange = {3,-1},
		MonsterKill = -1,
		Mode = 49,
		Stage = -1,
		ScoreRange = {-1,-1},
		IsSolo = False,
		MapID = -1,
		Kill = -1,
		Die = -1,
		ExLife = -1,
		ConditionActiveRatio = 1,
	},
	{
		ID = 75,
		Win = True,
		Time = -1,
		DifficultRange = {3,-1},
		MonsterKill = -1,
		Mode = 50,
		Stage = -1,
		ScoreRange = {-1,-1},
		IsSolo = False,
		MapID = -1,
		Kill = -1,
		Die = -1,
		ExLife = -1,
		ConditionActiveRatio = 1,
	},
	{
		ID = 76,
		Win = True,
		Time = -1,
		DifficultRange = {3,-1},
		MonsterKill = -1,
		Mode = 55,
		Stage = -1,
		ScoreRange = {-1,-1},
		IsSolo = False,
		MapID = -1,
		Kill = -1,
		Die = -1,
		ExLife = -1,
		ConditionActiveRatio = 1,
	},
	{
		ID = 77,
		Win = True,
		Time = -1,
		DifficultRange = {3,-1},
		MonsterKill = -1,
		Mode = 56,
		Stage = -1,
		ScoreRange = {-1,-1},
		IsSolo = False,
		MapID = -1,
		Kill = -1,
		Die = -1,
		ExLife = -1,
		ConditionActiveRatio = 1,
	},
	{
		ID = 78,
		Win = True,
		Time = -1,
		DifficultRange = {3,-1},
		MonsterKill = -1,
		Mode = 57,
		Stage = -1,
		ScoreRange = {-1,-1},
		IsSolo = False,
		MapID = -1,
		Kill = -1,
		Die = -1,
		ExLife = -1,
		ConditionActiveRatio = 1,
	},
	{
		ID = 79,
		Win = True,
		Time = -1,
		DifficultRange = {3,-1},
		MonsterKill = -1,
		Mode = 58,
		Stage = -1,
		ScoreRange = {-1,-1},
		IsSolo = False,
		MapID = -1,
		Kill = -1,
		Die = -1,
		ExLife = -1,
		ConditionActiveRatio = 1,
	},
	{
		ID = 80,
		Win = True,
		Time = -1,
		DifficultRange = {3,-1},
		MonsterKill = -1,
		Mode = 59,
		Stage = -1,
		ScoreRange = {-1,-1},
		IsSolo = False,
		MapID = -1,
		Kill = -1,
		Die = -1,
		ExLife = -1,
		ConditionActiveRatio = 1,
	},
	{
		ID = 81,
		Win = True,
		Time = -1,
		DifficultRange = {3,-1},
		MonsterKill = -1,
		Mode = 60,
		Stage = -1,
		ScoreRange = {-1,-1},
		IsSolo = False,
		MapID = -1,
		Kill = -1,
		Die = -1,
		ExLife = -1,
		ConditionActiveRatio = 1,
	},
}

Submission = {
	{
		SubmissionID = 0,
		CompletionTitleID = 0,
		CompletionDescID  = 1,
		Condition = {0, },
		Action = {
			bMonDrop = False,
			Item = -1,
			Count = 1,
		},
		Completion = {
			ItemID  = -1,
			Count   = 30,
		},
	},
	{
		SubmissionID = 1,
		CompletionTitleID = 2,
		CompletionDescID  = 3,
		Condition = {1, },
		Action = {
			bMonDrop = False,
			Item = -1,
			Count = 1,
		},
		Completion = {
			ItemID  = -1,
			Count   = 34,
		},
	},
	{
		SubmissionID = 2,
		CompletionTitleID = 4,
		CompletionDescID  = 5,
		Condition = {2, },
		Action = {
			bMonDrop = False,
			Item = -1,
			Count = 1,
		},
		Completion = {
			ItemID  = -1,
			Count   = 38,
		},
	},
	{
		SubmissionID = 3,
		CompletionTitleID = 6,
		CompletionDescID  = 7,
		Condition = {3, },
		Action = {
			bMonDrop = False,
			Item = -1,
			Count = 1,
		},
		Completion = {
			ItemID  = -1,
			Count   = 42,
		},
	},
	{
		SubmissionID = 4,
		CompletionTitleID = 8,
		CompletionDescID  = 9,
		Condition = {4, },
		Action = {
			bMonDrop = False,
			Item = -1,
			Count = 1,
		},
		Completion = {
			ItemID  = -1,
			Count   = 46,
		},
	},
	{
		SubmissionID = 5,
		CompletionTitleID = 10,
		CompletionDescID  = 11,
		Condition = {5, },
		Action = {
			bMonDrop = False,
			Item = -1,
			Count = 1,
		},
		Completion = {
			ItemID  = -1,
			Count   = 50,
		},
	},
	{
		SubmissionID = 6,
		CompletionTitleID = 12,
		CompletionDescID  = 13,
		Condition = {6, },
		Action = {
			bMonDrop = False,
			Item = -1,
			Count = 1,
		},
		Completion = {
			ItemID  = -1,
			Count   = 54,
		},
	},
	{
		SubmissionID = 7,
		CompletionTitleID = 14,
		CompletionDescID  = 15,
		Condition = {7, },
		Action = {
			bMonDrop = False,
			Item = -1,
			Count = 1,
		},
		Completion = {
			ItemID  = -1,
			Count   = 58,
		},
	},
	{
		SubmissionID = 8,
		CompletionTitleID = 16,
		CompletionDescID  = 17,
		Condition = {8, },
		Action = {
			bMonDrop = False,
			Item = -1,
			Count = 1,
		},
		Completion = {
			ItemID  = -1,
			Count   = 62,
		},
	},
	{
		SubmissionID = 9,
		CompletionTitleID = 18,
		CompletionDescID  = 19,
		Condition = {9, },
		Action = {
			bMonDrop = False,
			Item = -1,
			Count = 1,
		},
		Completion = {
			ItemID  = -1,
			Count   = 66,
		},
	},
	{
		SubmissionID = 10,
		CompletionTitleID = 20,
		CompletionDescID  = 21,
		Condition = {10, },
		Action = {
			bMonDrop = False,
			Item = -1,
			Count = 1,
		},
		Completion = {
			ItemID  = -1,
			Count   = 70,
		},
	},
	{
		SubmissionID = 11,
		CompletionTitleID = 22,
		CompletionDescID  = 23,
		Condition = {11, },
		Action = {
			bMonDrop = False,
			Item = -1,
			Count = 1,
		},
		Completion = {
			ItemID  = -1,
			Count   = 75,
		},
	},
	{
		SubmissionID = 12,
		CompletionTitleID = 24,
		CompletionDescID  = 25,
		Condition = {12, },
		Action = {
			bMonDrop = False,
			Item = -1,
			Count = 1,
		},
		Completion = {
			ItemID  = -1,
			Count   = 80,
		},
	},
	{
		SubmissionID = 13,
		CompletionTitleID = 26,
		CompletionDescID  = 27,
		Condition = {13, },
		Action = {
			bMonDrop = False,
			Item = -1,
			Count = 1,
		},
		Completion = {
			ItemID  = -1,
			Count   = 85,
		},
	},
	{
		SubmissionID = 14,
		CompletionTitleID = 28,
		CompletionDescID  = 29,
		Condition = {14, },
		Action = {
			bMonDrop = False,
			Item = -1,
			Count = 1,
		},
		Completion = {
			ItemID  = -1,
			Count   = 90,
		},
	},
	{
		SubmissionID = 15,
		CompletionTitleID = 30,
		CompletionDescID  = 31,
		Condition = {15, },
		Action = {
			bMonDrop = False,
			Item = -1,
			Count = 1,
		},
		Completion = {
			ItemID  = -1,
			Count   = 95,
		},
	},
	{
		SubmissionID = 16,
		CompletionTitleID = 32,
		CompletionDescID  = 33,
		Condition = {16, },
		Action = {
			bMonDrop = False,
			Item = -1,
			Count = 1,
		},
		Completion = {
			ItemID  = -1,
			Count   = 100,
		},
	},
	{
		SubmissionID = 17,
		CompletionTitleID = 34,
		CompletionDescID  = 35,
		Condition = {17, },
		Action = {
			bMonDrop = False,
			Item = -1,
			Count = 1,
		},
		Completion = {
			ItemID  = -1,
			Count   = 105,
		},
	},
	{
		SubmissionID = 18,
		CompletionTitleID = 36,
		CompletionDescID  = 37,
		Condition = {18, },
		Action = {
			bMonDrop = False,
			Item = -1,
			Count = 1,
		},
		Completion = {
			ItemID  = -1,
			Count   = 110,
		},
	},
	{
		SubmissionID = 19,
		CompletionTitleID = 38,
		CompletionDescID  = 39,
		Condition = {19, },
		Action = {
			bMonDrop = False,
			Item = -1,
			Count = 1,
		},
		Completion = {
			ItemID  = -1,
			Count   = 115,
		},
	},
	{
		SubmissionID = 20,
		CompletionTitleID = 40,
		CompletionDescID  = 41,
		Condition = {1, },
		Action = {
			bMonDrop = False,
			Item = -1,
			Count = 1,
		},
		Completion = {
			ItemID  = -1,
			Count   = 17,
		},
	},
	{
		SubmissionID = 21,
		CompletionTitleID = 42,
		CompletionDescID  = 43,
		Condition = {2, },
		Action = {
			bMonDrop = False,
			Item = -1,
			Count = 1,
		},
		Completion = {
			ItemID  = -1,
			Count   = 19,
		},
	},
	{
		SubmissionID = 22,
		CompletionTitleID = 44,
		CompletionDescID  = 45,
		Condition = {3, },
		Action = {
			bMonDrop = False,
			Item = -1,
			Count = 1,
		},
		Completion = {
			ItemID  = -1,
			Count   = 21,
		},
	},
	{
		SubmissionID = 23,
		CompletionTitleID = 46,
		CompletionDescID  = 47,
		Condition = {4, },
		Action = {
			bMonDrop = False,
			Item = -1,
			Count = 1,
		},
		Completion = {
			ItemID  = -1,
			Count   = 23,
		},
	},
	{
		SubmissionID = 24,
		CompletionTitleID = 48,
		CompletionDescID  = 49,
		Condition = {5, },
		Action = {
			bMonDrop = False,
			Item = -1,
			Count = 1,
		},
		Completion = {
			ItemID  = -1,
			Count   = 25,
		},
	},
	{
		SubmissionID = 25,
		CompletionTitleID = 50,
		CompletionDescID  = 51,
		Condition = {6, },
		Action = {
			bMonDrop = False,
			Item = -1,
			Count = 1,
		},
		Completion = {
			ItemID  = -1,
			Count   = 27,
		},
	},
	{
		SubmissionID = 26,
		CompletionTitleID = 52,
		CompletionDescID  = 53,
		Condition = {7, },
		Action = {
			bMonDrop = False,
			Item = -1,
			Count = 1,
		},
		Completion = {
			ItemID  = -1,
			Count   = 29,
		},
	},
	{
		SubmissionID = 27,
		CompletionTitleID = 54,
		CompletionDescID  = 55,
		Condition = {8, },
		Action = {
			bMonDrop = False,
			Item = -1,
			Count = 1,
		},
		Completion = {
			ItemID  = -1,
			Count   = 31,
		},
	},
	{
		SubmissionID = 28,
		CompletionTitleID = 56,
		CompletionDescID  = 57,
		Condition = {9, },
		Action = {
			bMonDrop = False,
			Item = -1,
			Count = 1,
		},
		Completion = {
			ItemID  = -1,
			Count   = 33,
		},
	},
	{
		SubmissionID = 29,
		CompletionTitleID = 58,
		CompletionDescID  = 59,
		Condition = {10, },
		Action = {
			bMonDrop = False,
			Item = -1,
			Count = 1,
		},
		Completion = {
			ItemID  = -1,
			Count   = 35,
		},
	},
	{
		SubmissionID = 30,
		CompletionTitleID = 60,
		CompletionDescID  = 61,
		Condition = {11, },
		Action = {
			bMonDrop = False,
			Item = -1,
			Count = 1,
		},
		Completion = {
			ItemID  = -1,
			Count   = 37,
		},
	},
	{
		SubmissionID = 31,
		CompletionTitleID = 62,
		CompletionDescID  = 63,
		Condition = {12, },
		Action = {
			bMonDrop = False,
			Item = -1,
			Count = 1,
		},
		Completion = {
			ItemID  = -1,
			Count   = 40,
		},
	},
	{
		SubmissionID = 32,
		CompletionTitleID = 64,
		CompletionDescID  = 65,
		Condition = {13, },
		Action = {
			bMonDrop = False,
			Item = -1,
			Count = 1,
		},
		Completion = {
			ItemID  = -1,
			Count   = 42,
		},
	},
	{
		SubmissionID = 33,
		CompletionTitleID = 66,
		CompletionDescID  = 67,
		Condition = {14, },
		Action = {
			bMonDrop = False,
			Item = -1,
			Count = 1,
		},
		Completion = {
			ItemID  = -1,
			Count   = 45,
		},
	},
	{
		SubmissionID = 34,
		CompletionTitleID = 68,
		CompletionDescID  = 69,
		Condition = {15, },
		Action = {
			bMonDrop = False,
			Item = -1,
			Count = 1,
		},
		Completion = {
			ItemID  = -1,
			Count   = 47,
		},
	},
	{
		SubmissionID = 35,
		CompletionTitleID = 70,
		CompletionDescID  = 71,
		Condition = {16, },
		Action = {
			bMonDrop = False,
			Item = -1,
			Count = 1,
		},
		Completion = {
			ItemID  = -1,
			Count   = 50,
		},
	},
	{
		SubmissionID = 36,
		CompletionTitleID = 72,
		CompletionDescID  = 73,
		Condition = {17, },
		Action = {
			bMonDrop = False,
			Item = -1,
			Count = 1,
		},
		Completion = {
			ItemID  = -1,
			Count   = 52,
		},
	},
	{
		SubmissionID = 37,
		CompletionTitleID = 74,
		CompletionDescID  = 75,
		Condition = {18, },
		Action = {
			bMonDrop = False,
			Item = -1,
			Count = 1,
		},
		Completion = {
			ItemID  = -1,
			Count   = 55,
		},
	},
	{
		SubmissionID = 38,
		CompletionTitleID = 76,
		CompletionDescID  = 77,
		Condition = {19, },
		Action = {
			bMonDrop = False,
			Item = -1,
			Count = 1,
		},
		Completion = {
			ItemID  = -1,
			Count   = 57,
		},
	},
	{
		SubmissionID = 39,
		CompletionTitleID = 78,
		CompletionDescID  = 79,
		Condition = {63, },
		Action = {
			bMonDrop = False,
			Item = -1,
			Count = 1,
		},
		Completion = {
			ItemID  = -1,
			Count   = 120,
		},
	},
	{
		SubmissionID = 40,
		CompletionTitleID = 80,
		CompletionDescID  = 81,
		Condition = {63, },
		Action = {
			bMonDrop = False,
			Item = -1,
			Count = 1,
		},
		Completion = {
			ItemID  = -1,
			Count   = 60,
		},
	},
	{
		SubmissionID = 41,
		CompletionTitleID = 82,
		CompletionDescID  = 83,
		Condition = {64, },
		Action = {
			bMonDrop = False,
			Item = -1,
			Count = 1,
		},
		Completion = {
			ItemID  = -1,
			Count   = 38,
		},
	},
	{
		SubmissionID = 42,
		CompletionTitleID = 84,
		CompletionDescID  = 85,
		Condition = {64, },
		Action = {
			bMonDrop = False,
			Item = -1,
			Count = 1,
		},
		Completion = {
			ItemID  = -1,
			Count   = 19,
		},
	},
	{
		SubmissionID = 43,
		CompletionTitleID = 86,
		CompletionDescID  = 87,
		Condition = {65, },
		Action = {
			bMonDrop = False,
			Item = -1,
			Count = 1,
		},
		Completion = {
			ItemID  = -1,
			Count   = 42,
		},
	},
	{
		SubmissionID = 44,
		CompletionTitleID = 88,
		CompletionDescID  = 89,
		Condition = {65, },
		Action = {
			bMonDrop = False,
			Item = -1,
			Count = 1,
		},
		Completion = {
			ItemID  = -1,
			Count   = 21,
		},
	},
	{
		SubmissionID = 45,
		CompletionTitleID = 90,
		CompletionDescID  = 91,
		Condition = {66, },
		Action = {
			bMonDrop = False,
			Item = -1,
			Count = 1,
		},
		Completion = {
			ItemID  = -1,
			Count   = 46,
		},
	},
	{
		SubmissionID = 46,
		CompletionTitleID = 92,
		CompletionDescID  = 93,
		Condition = {66, },
		Action = {
			bMonDrop = False,
			Item = -1,
			Count = 1,
		},
		Completion = {
			ItemID  = -1,
			Count   = 23,
		},
	},
	{
		SubmissionID = 47,
		CompletionTitleID = 94,
		CompletionDescID  = 95,
		Condition = {67, },
		Action = {
			bMonDrop = False,
			Item = -1,
			Count = 1,
		},
		Completion = {
			ItemID  = -1,
			Count   = 125,
		},
	},
	{
		SubmissionID = 48,
		CompletionTitleID = 96,
		CompletionDescID  = 97,
		Condition = {67, },
		Action = {
			bMonDrop = False,
			Item = -1,
			Count = 1,
		},
		Completion = {
			ItemID  = -1,
			Count   = 63,
		},
	},
	{
		SubmissionID = 49,
		CompletionTitleID = 98,
		CompletionDescID  = 99,
		Condition = {68, },
		Action = {
			bMonDrop = False,
			Item = -1,
			Count = 1,
		},
		Completion = {
			ItemID  = -1,
			Count   = 52,
		},
	},
	{
		SubmissionID = 50,
		CompletionTitleID = 100,
		CompletionDescID  = 101,
		Condition = {68, },
		Action = {
			bMonDrop = False,
			Item = -1,
			Count = 1,
		},
		Completion = {
			ItemID  = -1,
			Count   = 26,
		},
	},
	{
		SubmissionID = 51,
		CompletionTitleID = 102,
		CompletionDescID  = 103,
		Condition = {69, },
		Action = {
			bMonDrop = False,
			Item = -1,
			Count = 1,
		},
		Completion = {
			ItemID  = -1,
			Count   = 56,
		},
	},
	{
		SubmissionID = 52,
		CompletionTitleID = 104,
		CompletionDescID  = 105,
		Condition = {69, },
		Action = {
			bMonDrop = False,
			Item = -1,
			Count = 1,
		},
		Completion = {
			ItemID  = -1,
			Count   = 28,
		},
	},
	{
		SubmissionID = 53,
		CompletionTitleID = 106,
		CompletionDescID  = 107,
		Condition = {70, },
		Action = {
			bMonDrop = False,
			Item = -1,
			Count = 1,
		},
		Completion = {
			ItemID  = -1,
			Count   = 130,
		},
	},
	{
		SubmissionID = 54,
		CompletionTitleID = 108,
		CompletionDescID  = 109,
		Condition = {70, },
		Action = {
			bMonDrop = False,
			Item = -1,
			Count = 1,
		},
		Completion = {
			ItemID  = -1,
			Count   = 65,
		},
	},
	{
		SubmissionID = 55,
		CompletionTitleID = 110,
		CompletionDescID  = 111,
		Condition = {71, },
		Action = {
			bMonDrop = False,
			Item = -1,
			Count = 1,
		},
		Completion = {
			ItemID  = -1,
			Count   = 60,
		},
	},
	{
		SubmissionID = 56,
		CompletionTitleID = 112,
		CompletionDescID  = 113,
		Condition = {71, },
		Action = {
			bMonDrop = False,
			Item = -1,
			Count = 1,
		},
		Completion = {
			ItemID  = -1,
			Count   = 30,
		},
	},
	{
		SubmissionID = 57,
		CompletionTitleID = 114,
		CompletionDescID  = 115,
		Condition = {72, },
		Action = {
			bMonDrop = False,
			Item = -1,
			Count = 1,
		},
		Completion = {
			ItemID  = -1,
			Count   = 135,
		},
	},
	{
		SubmissionID = 58,
		CompletionTitleID = 116,
		CompletionDescID  = 117,
		Condition = {72, },
		Action = {
			bMonDrop = False,
			Item = -1,
			Count = 1,
		},
		Completion = {
			ItemID  = -1,
			Count   = 68,
		},
	},
	{
		SubmissionID = 59,
		CompletionTitleID = 118,
		CompletionDescID  = 119,
		Condition = {73, },
		Action = {
			bMonDrop = False,
			Item = -1,
			Count = 1,
		},
		Completion = {
			ItemID  = -1,
			Count   = 64,
		},
	},
	{
		SubmissionID = 60,
		CompletionTitleID = 120,
		CompletionDescID  = 121,
		Condition = {73, },
		Action = {
			bMonDrop = False,
			Item = -1,
			Count = 1,
		},
		Completion = {
			ItemID  = -1,
			Count   = 32,
		},
	},
	{
		SubmissionID = 61,
		CompletionTitleID = 122,
		CompletionDescID  = 123,
		Condition = {74, },
		Action = {
			bMonDrop = False,
			Item = -1,
			Count = 1,
		},
		Completion = {
			ItemID  = -1,
			Count   = 140,
		},
	},
	{
		SubmissionID = 62,
		CompletionTitleID = 124,
		CompletionDescID  = 125,
		Condition = {74, },
		Action = {
			bMonDrop = False,
			Item = -1,
			Count = 1,
		},
		Completion = {
			ItemID  = -1,
			Count   = 70,
		},
	},
	{
		SubmissionID = 63,
		CompletionTitleID = 126,
		CompletionDescID  = 127,
		Condition = {75, },
		Action = {
			bMonDrop = False,
			Item = -1,
			Count = 1,
		},
		Completion = {
			ItemID  = -1,
			Count   = 145,
		},
	},
	{
		SubmissionID = 64,
		CompletionTitleID = 128,
		CompletionDescID  = 129,
		Condition = {75, },
		Action = {
			bMonDrop = False,
			Item = -1,
			Count = 1,
		},
		Completion = {
			ItemID  = -1,
			Count   = 73,
		},
	},
	{
		SubmissionID = 65,
		CompletionTitleID = 130,
		CompletionDescID  = 131,
		Condition = {76, },
		Action = {
			bMonDrop = False,
			Item = -1,
			Count = 1,
		},
		Completion = {
			ItemID  = -1,
			Count   = 66,
		},
	},
	{
		SubmissionID = 66,
		CompletionTitleID = 132,
		CompletionDescID  = 133,
		Condition = {76, },
		Action = {
			bMonDrop = False,
			Item = -1,
			Count = 1,
		},
		Completion = {
			ItemID  = -1,
			Count   = 33,
		},
	},
	{
		SubmissionID = 67,
		CompletionTitleID = 134,
		CompletionDescID  = 135,
		Condition = {77, },
		Action = {
			bMonDrop = False,
			Item = -1,
			Count = 1,
		},
		Completion = {
			ItemID  = -1,
			Count   = 68,
		},
	},
	{
		SubmissionID = 68,
		CompletionTitleID = 136,
		CompletionDescID  = 137,
		Condition = {77, },
		Action = {
			bMonDrop = False,
			Item = -1,
			Count = 1,
		},
		Completion = {
			ItemID  = -1,
			Count   = 34,
		},
	},
	{
		SubmissionID = 69,
		CompletionTitleID = 138,
		CompletionDescID  = 139,
		Condition = {78, },
		Action = {
			bMonDrop = False,
			Item = -1,
			Count = 1,
		},
		Completion = {
			ItemID  = -1,
			Count   = 72,
		},
	},
	{
		SubmissionID = 70,
		CompletionTitleID = 140,
		CompletionDescID  = 141,
		Condition = {78, },
		Action = {
			bMonDrop = False,
			Item = -1,
			Count = 1,
		},
		Completion = {
			ItemID  = -1,
			Count   = 36,
		},
	},
	{
		SubmissionID = 71,
		CompletionTitleID = 142,
		CompletionDescID  = 143,
		Condition = {79, },
		Action = {
			bMonDrop = False,
			Item = -1,
			Count = 1,
		},
		Completion = {
			ItemID  = -1,
			Count   = 150,
		},
	},
	{
		SubmissionID = 72,
		CompletionTitleID = 144,
		CompletionDescID  = 145,
		Condition = {79, },
		Action = {
			bMonDrop = False,
			Item = -1,
			Count = 1,
		},
		Completion = {
			ItemID  = -1,
			Count   = 75,
		},
	},
	{
		SubmissionID = 73,
		CompletionTitleID = 146,
		CompletionDescID  = 147,
		Condition = {80, },
		Action = {
			bMonDrop = False,
			Item = -1,
			Count = 1,
		},
		Completion = {
			ItemID  = -1,
			Count   = 76,
		},
	},
	{
		SubmissionID = 74,
		CompletionTitleID = 148,
		CompletionDescID  = 149,
		Condition = {80, },
		Action = {
			bMonDrop = False,
			Item = -1,
			Count = 1,
		},
		Completion = {
			ItemID  = -1,
			Count   = 38,
		},
	},
	{
		SubmissionID = 75,
		CompletionTitleID = 150,
		CompletionDescID  = 151,
		Condition = {81, },
		Action = {
			bMonDrop = False,
			Item = -1,
			Count = 1,
		},
		Completion = {
			ItemID  = -1,
			Count   = 155,
		},
	},
	{
		SubmissionID = 76,
		CompletionTitleID = 152,
		CompletionDescID  = 153,
		Condition = {81, },
		Action = {
			bMonDrop = False,
			Item = -1,
			Count = 1,
		},
		Completion = {
			ItemID  = -1,
			Count   = 77,
		},
	},
}

Mission = {
	{
		ID = 83340,
		TitleID = 154,
		MissionDescID  = 155,
		CharType  = -1,
		LevelRange  = {-1,-1},
		Promotion  = -1,
		InvalidMission  = {},
		InvalidCompleteMission  = {},
		Unique  = 0,
		Period  = -1,
		Submissions = {0, },
		NewChar  = 0,
		ChangeJob  = -1,
		GP  = 0,
		EXP  = -1,
		RewardItem = {{25960, -1, -1}, {83340, -1, -1}, },
		SelectItem = {},
		ChainMissionID = -1,
		CorrectLevel = -1,
	},
	{
		ID = 83350,
		TitleID = 156,
		MissionDescID  = 157,
		CharType  = -1,
		LevelRange  = {-1,-1},
		Promotion  = -1,
		InvalidMission  = {},
		InvalidCompleteMission  = {},
		Unique  = 0,
		Period  = -1,
		Submissions = {1, },
		NewChar  = 1,
		ChangeJob  = -1,
		GP  = 0,
		EXP  = -1,
		RewardItem = {{83350, -1, -1}, },
		SelectItem = {},
		ChainMissionID = -1,
		CorrectLevel = -1,
	},
	{
		ID = 83360,
		TitleID = 158,
		MissionDescID  = 159,
		CharType  = -1,
		LevelRange  = {-1,-1},
		Promotion  = -1,
		InvalidMission  = {},
		InvalidCompleteMission  = {},
		Unique  = 0,
		Period  = -1,
		Submissions = {2, },
		NewChar  = 2,
		ChangeJob  = -1,
		GP  = 0,
		EXP  = -1,
		RewardItem = {{83360, -1, -1}, },
		SelectItem = {},
		ChainMissionID = -1,
		CorrectLevel = -1,
	},
	{
		ID = 83370,
		TitleID = 160,
		MissionDescID  = 161,
		CharType  = -1,
		LevelRange  = {-1,-1},
		Promotion  = -1,
		InvalidMission  = {},
		InvalidCompleteMission  = {},
		Unique  = 0,
		Period  = -1,
		Submissions = {3, },
		NewChar  = 3,
		ChangeJob  = -1,
		GP  = 0,
		EXP  = -1,
		RewardItem = {{83370, -1, -1}, },
		SelectItem = {},
		ChainMissionID = -1,
		CorrectLevel = -1,
	},
	{
		ID = 83380,
		TitleID = 162,
		MissionDescID  = 163,
		CharType  = -1,
		LevelRange  = {-1,-1},
		Promotion  = -1,
		InvalidMission  = {},
		InvalidCompleteMission  = {},
		Unique  = 0,
		Period  = -1,
		Submissions = {4, },
		NewChar  = 4,
		ChangeJob  = -1,
		GP  = 0,
		EXP  = -1,
		RewardItem = {{83380, -1, -1}, },
		SelectItem = {},
		ChainMissionID = -1,
		CorrectLevel = -1,
	},
	{
		ID = 83390,
		TitleID = 164,
		MissionDescID  = 165,
		CharType  = -1,
		LevelRange  = {-1,-1},
		Promotion  = -1,
		InvalidMission  = {},
		InvalidCompleteMission  = {},
		Unique  = 0,
		Period  = -1,
		Submissions = {5, },
		NewChar  = 5,
		ChangeJob  = -1,
		GP  = 0,
		EXP  = -1,
		RewardItem = {{83390, -1, -1}, },
		SelectItem = {},
		ChainMissionID = -1,
		CorrectLevel = -1,
	},
	{
		ID = 83400,
		TitleID = 166,
		MissionDescID  = 167,
		CharType  = -1,
		LevelRange  = {-1,-1},
		Promotion  = -1,
		InvalidMission  = {},
		InvalidCompleteMission  = {},
		Unique  = 0,
		Period  = -1,
		Submissions = {6, },
		NewChar  = 6,
		ChangeJob  = -1,
		GP  = 0,
		EXP  = -1,
		RewardItem = {{83400, -1, -1}, },
		SelectItem = {},
		ChainMissionID = -1,
		CorrectLevel = -1,
	},
	{
		ID = 83410,
		TitleID = 168,
		MissionDescID  = 169,
		CharType  = -1,
		LevelRange  = {-1,-1},
		Promotion  = -1,
		InvalidMission  = {},
		InvalidCompleteMission  = {},
		Unique  = 0,
		Period  = -1,
		Submissions = {7, },
		NewChar  = 7,
		ChangeJob  = -1,
		GP  = 0,
		EXP  = -1,
		RewardItem = {{83410, -1, -1}, },
		SelectItem = {},
		ChainMissionID = -1,
		CorrectLevel = -1,
	},
	{
		ID = 83420,
		TitleID = 170,
		MissionDescID  = 171,
		CharType  = -1,
		LevelRange  = {-1,-1},
		Promotion  = -1,
		InvalidMission  = {},
		InvalidCompleteMission  = {},
		Unique  = 0,
		Period  = -1,
		Submissions = {8, },
		NewChar  = 8,
		ChangeJob  = -1,
		GP  = 0,
		EXP  = -1,
		RewardItem = {{83420, -1, -1}, },
		SelectItem = {},
		ChainMissionID = -1,
		CorrectLevel = -1,
	},
	{
		ID = 83430,
		TitleID = 172,
		MissionDescID  = 173,
		CharType  = -1,
		LevelRange  = {-1,-1},
		Promotion  = -1,
		InvalidMission  = {},
		InvalidCompleteMission  = {},
		Unique  = 0,
		Period  = -1,
		Submissions = {9, },
		NewChar  = 9,
		ChangeJob  = -1,
		GP  = 0,
		EXP  = -1,
		RewardItem = {{83430, -1, -1}, },
		SelectItem = {},
		ChainMissionID = -1,
		CorrectLevel = -1,
	},
	{
		ID = 83440,
		TitleID = 174,
		MissionDescID  = 175,
		CharType  = -1,
		LevelRange  = {-1,-1},
		Promotion  = -1,
		InvalidMission  = {},
		InvalidCompleteMission  = {},
		Unique  = 0,
		Period  = -1,
		Submissions = {10, },
		NewChar  = 10,
		ChangeJob  = -1,
		GP  = 0,
		EXP  = -1,
		RewardItem = {{83440, -1, -1}, },
		SelectItem = {},
		ChainMissionID = -1,
		CorrectLevel = -1,
	},
	{
		ID = 83450,
		TitleID = 176,
		MissionDescID  = 177,
		CharType  = -1,
		LevelRange  = {-1,-1},
		Promotion  = -1,
		InvalidMission  = {},
		InvalidCompleteMission  = {},
		Unique  = 0,
		Period  = -1,
		Submissions = {11, },
		NewChar  = 11,
		ChangeJob  = -1,
		GP  = 0,
		EXP  = -1,
		RewardItem = {{83450, -1, -1}, },
		SelectItem = {},
		ChainMissionID = -1,
		CorrectLevel = -1,
	},
	{
		ID = 83460,
		TitleID = 178,
		MissionDescID  = 179,
		CharType  = -1,
		LevelRange  = {-1,-1},
		Promotion  = -1,
		InvalidMission  = {},
		InvalidCompleteMission  = {},
		Unique  = 0,
		Period  = -1,
		Submissions = {12, },
		NewChar  = 12,
		ChangeJob  = -1,
		GP  = 0,
		EXP  = -1,
		RewardItem = {{83460, -1, -1}, },
		SelectItem = {},
		ChainMissionID = -1,
		CorrectLevel = -1,
	},
	{
		ID = 83470,
		TitleID = 180,
		MissionDescID  = 181,
		CharType  = -1,
		LevelRange  = {-1,-1},
		Promotion  = -1,
		InvalidMission  = {},
		InvalidCompleteMission  = {},
		Unique  = 0,
		Period  = -1,
		Submissions = {13, },
		NewChar  = 13,
		ChangeJob  = -1,
		GP  = 0,
		EXP  = -1,
		RewardItem = {{83470, -1, -1}, },
		SelectItem = {},
		ChainMissionID = -1,
		CorrectLevel = -1,
	},
	{
		ID = 83480,
		TitleID = 182,
		MissionDescID  = 183,
		CharType  = -1,
		LevelRange  = {-1,-1},
		Promotion  = -1,
		InvalidMission  = {},
		InvalidCompleteMission  = {},
		Unique  = 0,
		Period  = -1,
		Submissions = {14, },
		NewChar  = 14,
		ChangeJob  = -1,
		GP  = 0,
		EXP  = -1,
		RewardItem = {{83480, -1, -1}, },
		SelectItem = {},
		ChainMissionID = -1,
		CorrectLevel = -1,
	},
	{
		ID = 83490,
		TitleID = 184,
		MissionDescID  = 185,
		CharType  = -1,
		LevelRange  = {-1,-1},
		Promotion  = -1,
		InvalidMission  = {},
		InvalidCompleteMission  = {},
		Unique  = 0,
		Period  = -1,
		Submissions = {15, },
		NewChar  = 15,
		ChangeJob  = -1,
		GP  = 0,
		EXP  = -1,
		RewardItem = {{83490, -1, -1}, },
		SelectItem = {},
		ChainMissionID = -1,
		CorrectLevel = -1,
	},
	{
		ID = 83500,
		TitleID = 186,
		MissionDescID  = 187,
		CharType  = -1,
		LevelRange  = {-1,-1},
		Promotion  = -1,
		InvalidMission  = {},
		InvalidCompleteMission  = {},
		Unique  = 0,
		Period  = -1,
		Submissions = {16, },
		NewChar  = 16,
		ChangeJob  = -1,
		GP  = 0,
		EXP  = -1,
		RewardItem = {{83500, -1, -1}, },
		SelectItem = {},
		ChainMissionID = -1,
		CorrectLevel = -1,
	},
	{
		ID = 83510,
		TitleID = 188,
		MissionDescID  = 189,
		CharType  = -1,
		LevelRange  = {-1,-1},
		Promotion  = -1,
		InvalidMission  = {},
		InvalidCompleteMission  = {},
		Unique  = 0,
		Period  = -1,
		Submissions = {17, },
		NewChar  = 17,
		ChangeJob  = -1,
		GP  = 0,
		EXP  = -1,
		RewardItem = {{83510, -1, -1}, },
		SelectItem = {},
		ChainMissionID = -1,
		CorrectLevel = -1,
	},
	{
		ID = 83520,
		TitleID = 190,
		MissionDescID  = 191,
		CharType  = -1,
		LevelRange  = {-1,-1},
		Promotion  = -1,
		InvalidMission  = {},
		InvalidCompleteMission  = {},
		Unique  = 0,
		Period  = -1,
		Submissions = {18, },
		NewChar  = 18,
		ChangeJob  = -1,
		GP  = 0,
		EXP  = -1,
		RewardItem = {{83520, -1, -1}, },
		SelectItem = {},
		ChainMissionID = -1,
		CorrectLevel = -1,
	},
	{
		ID = 83530,
		TitleID = 192,
		MissionDescID  = 193,
		CharType  = -1,
		LevelRange  = {-1,-1},
		Promotion  = -1,
		InvalidMission  = {},
		InvalidCompleteMission  = {},
		Unique  = 0,
		Period  = -1,
		Submissions = {19, },
		NewChar  = 19,
		ChangeJob  = -1,
		GP  = 0,
		EXP  = -1,
		RewardItem = {{83530, -1, -1}, },
		SelectItem = {},
		ChainMissionID = -1,
		CorrectLevel = -1,
	},
	{
		ID = 30830,
		TitleID = 194,
		MissionDescID  = 195,
		CharType  = -1,
		LevelRange  = {-1,-1},
		Promotion  = -1,
		InvalidMission  = {},
		InvalidCompleteMission  = {},
		Unique  = 0,
		Period  = -1,
		Submissions = {20, },
		NewChar  = 1,
		ChangeJob  = -1,
		GP  = 0,
		EXP  = -1,
		RewardItem = {{83350, -1, -1}, },
		SelectItem = {},
		ChainMissionID = -1,
		CorrectLevel = -1,
	},
	{
		ID = 30840,
		TitleID = 196,
		MissionDescID  = 197,
		CharType  = -1,
		LevelRange  = {-1,-1},
		Promotion  = -1,
		InvalidMission  = {},
		InvalidCompleteMission  = {},
		Unique  = 0,
		Period  = -1,
		Submissions = {21, },
		NewChar  = 2,
		ChangeJob  = -1,
		GP  = 0,
		EXP  = -1,
		RewardItem = {{83360, -1, -1}, },
		SelectItem = {},
		ChainMissionID = -1,
		CorrectLevel = -1,
	},
	{
		ID = 30850,
		TitleID = 198,
		MissionDescID  = 199,
		CharType  = -1,
		LevelRange  = {-1,-1},
		Promotion  = -1,
		InvalidMission  = {},
		InvalidCompleteMission  = {},
		Unique  = 0,
		Period  = -1,
		Submissions = {22, },
		NewChar  = 3,
		ChangeJob  = -1,
		GP  = 0,
		EXP  = -1,
		RewardItem = {{83370, -1, -1}, },
		SelectItem = {},
		ChainMissionID = -1,
		CorrectLevel = -1,
	},
	{
		ID = 30860,
		TitleID = 200,
		MissionDescID  = 201,
		CharType  = -1,
		LevelRange  = {-1,-1},
		Promotion  = -1,
		InvalidMission  = {},
		InvalidCompleteMission  = {},
		Unique  = 0,
		Period  = -1,
		Submissions = {23, },
		NewChar  = 4,
		ChangeJob  = -1,
		GP  = 0,
		EXP  = -1,
		RewardItem = {{83380, -1, -1}, },
		SelectItem = {},
		ChainMissionID = -1,
		CorrectLevel = -1,
	},
	{
		ID = 30870,
		TitleID = 202,
		MissionDescID  = 203,
		CharType  = -1,
		LevelRange  = {-1,-1},
		Promotion  = -1,
		InvalidMission  = {},
		InvalidCompleteMission  = {},
		Unique  = 0,
		Period  = -1,
		Submissions = {24, },
		NewChar  = 5,
		ChangeJob  = -1,
		GP  = 0,
		EXP  = -1,
		RewardItem = {{83390, -1, -1}, },
		SelectItem = {},
		ChainMissionID = -1,
		CorrectLevel = -1,
	},
	{
		ID = 30880,
		TitleID = 204,
		MissionDescID  = 205,
		CharType  = -1,
		LevelRange  = {-1,-1},
		Promotion  = -1,
		InvalidMission  = {},
		InvalidCompleteMission  = {},
		Unique  = 0,
		Period  = -1,
		Submissions = {25, },
		NewChar  = 6,
		ChangeJob  = -1,
		GP  = 0,
		EXP  = -1,
		RewardItem = {{83400, -1, -1}, },
		SelectItem = {},
		ChainMissionID = -1,
		CorrectLevel = -1,
	},
	{
		ID = 30890,
		TitleID = 206,
		MissionDescID  = 207,
		CharType  = -1,
		LevelRange  = {-1,-1},
		Promotion  = -1,
		InvalidMission  = {},
		InvalidCompleteMission  = {},
		Unique  = 0,
		Period  = -1,
		Submissions = {26, },
		NewChar  = 7,
		ChangeJob  = -1,
		GP  = 0,
		EXP  = -1,
		RewardItem = {{83410, -1, -1}, },
		SelectItem = {},
		ChainMissionID = -1,
		CorrectLevel = -1,
	},
	{
		ID = 30900,
		TitleID = 208,
		MissionDescID  = 209,
		CharType  = -1,
		LevelRange  = {-1,-1},
		Promotion  = -1,
		InvalidMission  = {},
		InvalidCompleteMission  = {},
		Unique  = 0,
		Period  = -1,
		Submissions = {27, },
		NewChar  = 8,
		ChangeJob  = -1,
		GP  = 0,
		EXP  = -1,
		RewardItem = {{83420, -1, -1}, },
		SelectItem = {},
		ChainMissionID = -1,
		CorrectLevel = -1,
	},
	{
		ID = 30910,
		TitleID = 210,
		MissionDescID  = 211,
		CharType  = -1,
		LevelRange  = {-1,-1},
		Promotion  = -1,
		InvalidMission  = {},
		InvalidCompleteMission  = {},
		Unique  = 0,
		Period  = -1,
		Submissions = {28, },
		NewChar  = 9,
		ChangeJob  = -1,
		GP  = 0,
		EXP  = -1,
		RewardItem = {{83430, -1, -1}, },
		SelectItem = {},
		ChainMissionID = -1,
		CorrectLevel = -1,
	},
	{
		ID = 30920,
		TitleID = 212,
		MissionDescID  = 213,
		CharType  = -1,
		LevelRange  = {-1,-1},
		Promotion  = -1,
		InvalidMission  = {},
		InvalidCompleteMission  = {},
		Unique  = 0,
		Period  = -1,
		Submissions = {29, },
		NewChar  = 10,
		ChangeJob  = -1,
		GP  = 0,
		EXP  = -1,
		RewardItem = {{83440, -1, -1}, },
		SelectItem = {},
		ChainMissionID = -1,
		CorrectLevel = -1,
	},
	{
		ID = 30930,
		TitleID = 214,
		MissionDescID  = 215,
		CharType  = -1,
		LevelRange  = {-1,-1},
		Promotion  = -1,
		InvalidMission  = {},
		InvalidCompleteMission  = {},
		Unique  = 0,
		Period  = -1,
		Submissions = {30, },
		NewChar  = 11,
		ChangeJob  = -1,
		GP  = 0,
		EXP  = -1,
		RewardItem = {{83450, -1, -1}, },
		SelectItem = {},
		ChainMissionID = -1,
		CorrectLevel = -1,
	},
	{
		ID = 30940,
		TitleID = 216,
		MissionDescID  = 217,
		CharType  = -1,
		LevelRange  = {-1,-1},
		Promotion  = -1,
		InvalidMission  = {},
		InvalidCompleteMission  = {},
		Unique  = 0,
		Period  = -1,
		Submissions = {31, },
		NewChar  = 12,
		ChangeJob  = -1,
		GP  = 0,
		EXP  = -1,
		RewardItem = {{83460, -1, -1}, },
		SelectItem = {},
		ChainMissionID = -1,
		CorrectLevel = -1,
	},
	{
		ID = 30950,
		TitleID = 218,
		MissionDescID  = 219,
		CharType  = -1,
		LevelRange  = {-1,-1},
		Promotion  = -1,
		InvalidMission  = {},
		InvalidCompleteMission  = {},
		Unique  = 0,
		Period  = -1,
		Submissions = {32, },
		NewChar  = 13,
		ChangeJob  = -1,
		GP  = 0,
		EXP  = -1,
		RewardItem = {{83470, -1, -1}, },
		SelectItem = {},
		ChainMissionID = -1,
		CorrectLevel = -1,
	},
	{
		ID = 30960,
		TitleID = 220,
		MissionDescID  = 221,
		CharType  = -1,
		LevelRange  = {-1,-1},
		Promotion  = -1,
		InvalidMission  = {},
		InvalidCompleteMission  = {},
		Unique  = 0,
		Period  = -1,
		Submissions = {33, },
		NewChar  = 14,
		ChangeJob  = -1,
		GP  = 0,
		EXP  = -1,
		RewardItem = {{83480, -1, -1}, },
		SelectItem = {},
		ChainMissionID = -1,
		CorrectLevel = -1,
	},
	{
		ID = 30970,
		TitleID = 222,
		MissionDescID  = 223,
		CharType  = -1,
		LevelRange  = {-1,-1},
		Promotion  = -1,
		InvalidMission  = {},
		InvalidCompleteMission  = {},
		Unique  = 0,
		Period  = -1,
		Submissions = {34, },
		NewChar  = 15,
		ChangeJob  = -1,
		GP  = 0,
		EXP  = -1,
		RewardItem = {{83490, -1, -1}, },
		SelectItem = {},
		ChainMissionID = -1,
		CorrectLevel = -1,
	},
	{
		ID = 30980,
		TitleID = 224,
		MissionDescID  = 225,
		CharType  = -1,
		LevelRange  = {-1,-1},
		Promotion  = -1,
		InvalidMission  = {},
		InvalidCompleteMission  = {},
		Unique  = 0,
		Period  = -1,
		Submissions = {35, },
		NewChar  = 16,
		ChangeJob  = -1,
		GP  = 0,
		EXP  = -1,
		RewardItem = {{83500, -1, -1}, },
		SelectItem = {},
		ChainMissionID = -1,
		CorrectLevel = -1,
	},
	{
		ID = 30990,
		TitleID = 226,
		MissionDescID  = 227,
		CharType  = -1,
		LevelRange  = {-1,-1},
		Promotion  = -1,
		InvalidMission  = {},
		InvalidCompleteMission  = {},
		Unique  = 0,
		Period  = -1,
		Submissions = {36, },
		NewChar  = 17,
		ChangeJob  = -1,
		GP  = 0,
		EXP  = -1,
		RewardItem = {{83510, -1, -1}, },
		SelectItem = {},
		ChainMissionID = -1,
		CorrectLevel = -1,
	},
	{
		ID = 31000,
		TitleID = 228,
		MissionDescID  = 229,
		CharType  = -1,
		LevelRange  = {-1,-1},
		Promotion  = -1,
		InvalidMission  = {},
		InvalidCompleteMission  = {},
		Unique  = 0,
		Period  = -1,
		Submissions = {37, },
		NewChar  = 18,
		ChangeJob  = -1,
		GP  = 0,
		EXP  = -1,
		RewardItem = {{83520, -1, -1}, },
		SelectItem = {},
		ChainMissionID = -1,
		CorrectLevel = -1,
	},
	{
		ID = 31010,
		TitleID = 230,
		MissionDescID  = 231,
		CharType  = -1,
		LevelRange  = {-1,-1},
		Promotion  = -1,
		InvalidMission  = {},
		InvalidCompleteMission  = {},
		Unique  = 0,
		Period  = -1,
		Submissions = {38, },
		NewChar  = 19,
		ChangeJob  = -1,
		GP  = 0,
		EXP  = -1,
		RewardItem = {{83530, -1, -1}, },
		SelectItem = {},
		ChainMissionID = -1,
		CorrectLevel = -1,
	},
	{
		ID = 105240,
		TitleID = 232,
		MissionDescID  = 233,
		CharType  = -1,
		LevelRange  = {-1,-1},
		Promotion  = -1,
		InvalidMission  = {},
		InvalidCompleteMission  = {},
		Unique  = 0,
		Period  = -1,
		Submissions = {39, },
		NewChar  = 20,
		ChangeJob  = -1,
		GP  = 0,
		EXP  = -1,
		RewardItem = {{105240, -1, -1}, },
		SelectItem = {},
		ChainMissionID = -1,
		CorrectLevel = -1,
	},
	{
		ID = 31020,
		TitleID = 234,
		MissionDescID  = 235,
		CharType  = -1,
		LevelRange  = {-1,-1},
		Promotion  = -1,
		InvalidMission  = {},
		InvalidCompleteMission  = {},
		Unique  = 0,
		Period  = -1,
		Submissions = {40, },
		NewChar  = 20,
		ChangeJob  = -1,
		GP  = 0,
		EXP  = -1,
		RewardItem = {{105240, -1, -1}, },
		SelectItem = {},
		ChainMissionID = -1,
		CorrectLevel = -1,
	},
	{
		ID = 130880,
		TitleID = 236,
		MissionDescID  = 237,
		CharType  = -1,
		LevelRange  = {-1,-1},
		Promotion  = -1,
		InvalidMission  = {},
		InvalidCompleteMission  = {},
		Unique  = 0,
		Period  = -1,
		Submissions = {41, },
		NewChar  = 21,
		ChangeJob  = -1,
		GP  = 0,
		EXP  = -1,
		RewardItem = {{130880, -1, -1}, },
		SelectItem = {},
		ChainMissionID = -1,
		CorrectLevel = -1,
	},
	{
		ID = 31030,
		TitleID = 238,
		MissionDescID  = 239,
		CharType  = -1,
		LevelRange  = {-1,-1},
		Promotion  = -1,
		InvalidMission  = {},
		InvalidCompleteMission  = {},
		Unique  = 0,
		Period  = -1,
		Submissions = {42, },
		NewChar  = 21,
		ChangeJob  = -1,
		GP  = 0,
		EXP  = -1,
		RewardItem = {{130880, -1, -1}, },
		SelectItem = {},
		ChainMissionID = -1,
		CorrectLevel = -1,
	},
	{
		ID = 130890,
		TitleID = 240,
		MissionDescID  = 241,
		CharType  = -1,
		LevelRange  = {-1,-1},
		Promotion  = -1,
		InvalidMission  = {},
		InvalidCompleteMission  = {},
		Unique  = 0,
		Period  = -1,
		Submissions = {43, },
		NewChar  = 22,
		ChangeJob  = -1,
		GP  = 0,
		EXP  = -1,
		RewardItem = {{130890, -1, -1}, },
		SelectItem = {},
		ChainMissionID = -1,
		CorrectLevel = -1,
	},
	{
		ID = 31040,
		TitleID = 242,
		MissionDescID  = 243,
		CharType  = -1,
		LevelRange  = {-1,-1},
		Promotion  = -1,
		InvalidMission  = {},
		InvalidCompleteMission  = {},
		Unique  = 0,
		Period  = -1,
		Submissions = {44, },
		NewChar  = 22,
		ChangeJob  = -1,
		GP  = 0,
		EXP  = -1,
		RewardItem = {{130890, -1, -1}, },
		SelectItem = {},
		ChainMissionID = -1,
		CorrectLevel = -1,
	},
	{
		ID = 138910,
		TitleID = 244,
		MissionDescID  = 245,
		CharType  = -1,
		LevelRange  = {-1,-1},
		Promotion  = -1,
		InvalidMission  = {},
		InvalidCompleteMission  = {},
		Unique  = 0,
		Period  = -1,
		Submissions = {45, },
		NewChar  = 23,
		ChangeJob  = -1,
		GP  = 0,
		EXP  = -1,
		RewardItem = {{138910, -1, -1}, },
		SelectItem = {},
		ChainMissionID = -1,
		CorrectLevel = -1,
	},
	{
		ID = 31050,
		TitleID = 246,
		MissionDescID  = 247,
		CharType  = -1,
		LevelRange  = {-1,-1},
		Promotion  = -1,
		InvalidMission  = {},
		InvalidCompleteMission  = {},
		Unique  = 0,
		Period  = -1,
		Submissions = {46, },
		NewChar  = 23,
		ChangeJob  = -1,
		GP  = 0,
		EXP  = -1,
		RewardItem = {{138910, -1, -1}, },
		SelectItem = {},
		ChainMissionID = -1,
		CorrectLevel = -1,
	},
	{
		ID = 141730,
		TitleID = 248,
		MissionDescID  = 249,
		CharType  = -1,
		LevelRange  = {-1,-1},
		Promotion  = -1,
		InvalidMission  = {},
		InvalidCompleteMission  = {},
		Unique  = 0,
		Period  = -1,
		Submissions = {47, },
		NewChar  = 24,
		ChangeJob  = -1,
		GP  = 0,
		EXP  = -1,
		RewardItem = {{141730, -1, -1}, },
		SelectItem = {},
		ChainMissionID = -1,
		CorrectLevel = -1,
	},
	{
		ID = 34240,
		TitleID = 250,
		MissionDescID  = 251,
		CharType  = -1,
		LevelRange  = {-1,-1},
		Promotion  = -1,
		InvalidMission  = {},
		InvalidCompleteMission  = {},
		Unique  = 0,
		Period  = -1,
		Submissions = {48, },
		NewChar  = 24,
		ChangeJob  = -1,
		GP  = 0,
		EXP  = -1,
		RewardItem = {{141730, -1, -1}, },
		SelectItem = {},
		ChainMissionID = -1,
		CorrectLevel = -1,
	},
	{
		ID = 147720,
		TitleID = 252,
		MissionDescID  = 253,
		CharType  = -1,
		LevelRange  = {-1,-1},
		Promotion  = -1,
		InvalidMission  = {},
		InvalidCompleteMission  = {},
		Unique  = 0,
		Period  = -1,
		Submissions = {49, },
		NewChar  = 25,
		ChangeJob  = -1,
		GP  = 0,
		EXP  = -1,
		RewardItem = {{147720, -1, -1}, },
		SelectItem = {},
		ChainMissionID = -1,
		CorrectLevel = -1,
	},
	{
		ID = 34250,
		TitleID = 254,
		MissionDescID  = 255,
		CharType  = -1,
		LevelRange  = {-1,-1},
		Promotion  = -1,
		InvalidMission  = {},
		InvalidCompleteMission  = {},
		Unique  = 0,
		Period  = -1,
		Submissions = {50, },
		NewChar  = 25,
		ChangeJob  = -1,
		GP  = 0,
		EXP  = -1,
		RewardItem = {{147720, -1, -1}, },
		SelectItem = {},
		ChainMissionID = -1,
		CorrectLevel = -1,
	},
	{
		ID = 182870,
		TitleID = 256,
		MissionDescID  = 257,
		CharType  = -1,
		LevelRange  = {-1,-1},
		Promotion  = -1,
		InvalidMission  = {},
		InvalidCompleteMission  = {},
		Unique  = 0,
		Period  = -1,
		Submissions = {51, },
		NewChar  = 26,
		ChangeJob  = -1,
		GP  = 0,
		EXP  = -1,
		RewardItem = {{182870, -1, -1}, },
		SelectItem = {},
		ChainMissionID = -1,
		CorrectLevel = -1,
	},
	{
		ID = 182880,
		TitleID = 258,
		MissionDescID  = 259,
		CharType  = -1,
		LevelRange  = {-1,-1},
		Promotion  = -1,
		InvalidMission  = {},
		InvalidCompleteMission  = {},
		Unique  = 0,
		Period  = -1,
		Submissions = {52, },
		NewChar  = 26,
		ChangeJob  = -1,
		GP  = 0,
		EXP  = -1,
		RewardItem = {{182870, -1, -1}, },
		SelectItem = {},
		ChainMissionID = -1,
		CorrectLevel = -1,
	},
	{
		ID = 182890,
		TitleID = 260,
		MissionDescID  = 261,
		CharType  = -1,
		LevelRange  = {-1,-1},
		Promotion  = -1,
		InvalidMission  = {},
		InvalidCompleteMission  = {},
		Unique  = 0,
		Period  = -1,
		Submissions = {53, },
		NewChar  = 27,
		ChangeJob  = -1,
		GP  = 0,
		EXP  = -1,
		RewardItem = {{182890, -1, -1}, },
		SelectItem = {},
		ChainMissionID = -1,
		CorrectLevel = -1,
	},
	{
		ID = 182900,
		TitleID = 262,
		MissionDescID  = 263,
		CharType  = -1,
		LevelRange  = {-1,-1},
		Promotion  = -1,
		InvalidMission  = {},
		InvalidCompleteMission  = {},
		Unique  = 0,
		Period  = -1,
		Submissions = {54, },
		NewChar  = 27,
		ChangeJob  = -1,
		GP  = 0,
		EXP  = -1,
		RewardItem = {{182890, -1, -1}, },
		SelectItem = {},
		ChainMissionID = -1,
		CorrectLevel = -1,
	},
	{
		ID = 184620,
		TitleID = 264,
		MissionDescID  = 265,
		CharType  = -1,
		LevelRange  = {-1,-1},
		Promotion  = -1,
		InvalidMission  = {},
		InvalidCompleteMission  = {},
		Unique  = 0,
		Period  = -1,
		Submissions = {55, },
		NewChar  = 28,
		ChangeJob  = -1,
		GP  = 0,
		EXP  = -1,
		RewardItem = {{184620, -1, -1}, },
		SelectItem = {},
		ChainMissionID = -1,
		CorrectLevel = -1,
	},
	{
		ID = 184630,
		TitleID = 266,
		MissionDescID  = 267,
		CharType  = -1,
		LevelRange  = {-1,-1},
		Promotion  = -1,
		InvalidMission  = {},
		InvalidCompleteMission  = {},
		Unique  = 0,
		Period  = -1,
		Submissions = {56, },
		NewChar  = 28,
		ChangeJob  = -1,
		GP  = 0,
		EXP  = -1,
		RewardItem = {{184620, -1, -1}, },
		SelectItem = {},
		ChainMissionID = -1,
		CorrectLevel = -1,
	},
	{
		ID = 184640,
		TitleID = 268,
		MissionDescID  = 269,
		CharType  = -1,
		LevelRange  = {-1,-1},
		Promotion  = -1,
		InvalidMission  = {},
		InvalidCompleteMission  = {},
		Unique  = 0,
		Period  = -1,
		Submissions = {57, },
		NewChar  = 29,
		ChangeJob  = -1,
		GP  = 0,
		EXP  = -1,
		RewardItem = {{184640, -1, -1}, },
		SelectItem = {},
		ChainMissionID = -1,
		CorrectLevel = -1,
	},
	{
		ID = 184650,
		TitleID = 270,
		MissionDescID  = 271,
		CharType  = -1,
		LevelRange  = {-1,-1},
		Promotion  = -1,
		InvalidMission  = {},
		InvalidCompleteMission  = {},
		Unique  = 0,
		Period  = -1,
		Submissions = {58, },
		NewChar  = 29,
		ChangeJob  = -1,
		GP  = 0,
		EXP  = -1,
		RewardItem = {{184640, -1, -1}, },
		SelectItem = {},
		ChainMissionID = -1,
		CorrectLevel = -1,
	},
	{
		ID = 188500,
		TitleID = 272,
		MissionDescID  = 273,
		CharType  = -1,
		LevelRange  = {-1,-1},
		Promotion  = -1,
		InvalidMission  = {},
		InvalidCompleteMission  = {},
		Unique  = 0,
		Period  = -1,
		Submissions = {59, },
		NewChar  = 30,
		ChangeJob  = -1,
		GP  = 0,
		EXP  = -1,
		RewardItem = {{188500, -1, -1}, },
		SelectItem = {},
		ChainMissionID = -1,
		CorrectLevel = -1,
	},
	{
		ID = 188510,
		TitleID = 274,
		MissionDescID  = 275,
		CharType  = -1,
		LevelRange  = {-1,-1},
		Promotion  = -1,
		InvalidMission  = {},
		InvalidCompleteMission  = {},
		Unique  = 0,
		Period  = -1,
		Submissions = {60, },
		NewChar  = 30,
		ChangeJob  = -1,
		GP  = 0,
		EXP  = -1,
		RewardItem = {{188500, -1, -1}, },
		SelectItem = {},
		ChainMissionID = -1,
		CorrectLevel = -1,
	},
	{
		ID = 188520,
		TitleID = 276,
		MissionDescID  = 277,
		CharType  = -1,
		LevelRange  = {-1,-1},
		Promotion  = -1,
		InvalidMission  = {},
		InvalidCompleteMission  = {},
		Unique  = 0,
		Period  = -1,
		Submissions = {61, },
		NewChar  = 31,
		ChangeJob  = -1,
		GP  = 0,
		EXP  = -1,
		RewardItem = {{188520, -1, -1}, },
		SelectItem = {},
		ChainMissionID = -1,
		CorrectLevel = -1,
	},
	{
		ID = 188530,
		TitleID = 278,
		MissionDescID  = 279,
		CharType  = -1,
		LevelRange  = {-1,-1},
		Promotion  = -1,
		InvalidMission  = {},
		InvalidCompleteMission  = {},
		Unique  = 0,
		Period  = -1,
		Submissions = {62, },
		NewChar  = 31,
		ChangeJob  = -1,
		GP  = 0,
		EXP  = -1,
		RewardItem = {{188520, -1, -1}, },
		SelectItem = {},
		ChainMissionID = -1,
		CorrectLevel = -1,
	},
	{
		ID = 188540,
		TitleID = 280,
		MissionDescID  = 281,
		CharType  = -1,
		LevelRange  = {-1,-1},
		Promotion  = -1,
		InvalidMission  = {},
		InvalidCompleteMission  = {},
		Unique  = 0,
		Period  = -1,
		Submissions = {63, },
		NewChar  = 32,
		ChangeJob  = -1,
		GP  = 0,
		EXP  = -1,
		RewardItem = {{188540, -1, -1}, },
		SelectItem = {},
		ChainMissionID = -1,
		CorrectLevel = -1,
	},
	{
		ID = 188550,
		TitleID = 282,
		MissionDescID  = 283,
		CharType  = -1,
		LevelRange  = {-1,-1},
		Promotion  = -1,
		InvalidMission  = {},
		InvalidCompleteMission  = {},
		Unique  = 0,
		Period  = -1,
		Submissions = {64, },
		NewChar  = 32,
		ChangeJob  = -1,
		GP  = 0,
		EXP  = -1,
		RewardItem = {{188540, -1, -1}, },
		SelectItem = {},
		ChainMissionID = -1,
		CorrectLevel = -1,
	},
	{
		ID = 215670,
		TitleID = 284,
		MissionDescID  = 285,
		CharType  = -1,
		LevelRange  = {-1,-1},
		Promotion  = -1,
		InvalidMission  = {},
		InvalidCompleteMission  = {},
		Unique  = 0,
		Period  = -1,
		Submissions = {65, },
		NewChar  = 33,
		ChangeJob  = -1,
		GP  = 0,
		EXP  = -1,
		RewardItem = {{215670, -1, -1}, },
		SelectItem = {},
		ChainMissionID = -1,
		CorrectLevel = -1,
	},
	{
		ID = 34260,
		TitleID = 286,
		MissionDescID  = 287,
		CharType  = -1,
		LevelRange  = {-1,-1},
		Promotion  = -1,
		InvalidMission  = {},
		InvalidCompleteMission  = {},
		Unique  = 0,
		Period  = -1,
		Submissions = {66, },
		NewChar  = 33,
		ChangeJob  = -1,
		GP  = 0,
		EXP  = -1,
		RewardItem = {{215670, -1, -1}, },
		SelectItem = {},
		ChainMissionID = -1,
		CorrectLevel = -1,
	},
	{
		ID = 215680,
		TitleID = 288,
		MissionDescID  = 289,
		CharType  = -1,
		LevelRange  = {-1,-1},
		Promotion  = -1,
		InvalidMission  = {},
		InvalidCompleteMission  = {},
		Unique  = 0,
		Period  = -1,
		Submissions = {67, },
		NewChar  = 34,
		ChangeJob  = -1,
		GP  = 0,
		EXP  = -1,
		RewardItem = {{215680, -1, -1}, },
		SelectItem = {},
		ChainMissionID = -1,
		CorrectLevel = -1,
	},
	{
		ID = 34270,
		TitleID = 290,
		MissionDescID  = 291,
		CharType  = -1,
		LevelRange  = {-1,-1},
		Promotion  = -1,
		InvalidMission  = {},
		InvalidCompleteMission  = {},
		Unique  = 0,
		Period  = -1,
		Submissions = {68, },
		NewChar  = 34,
		ChangeJob  = -1,
		GP  = 0,
		EXP  = -1,
		RewardItem = {{215680, -1, -1}, },
		SelectItem = {},
		ChainMissionID = -1,
		CorrectLevel = -1,
	},
	{
		ID = 215690,
		TitleID = 292,
		MissionDescID  = 293,
		CharType  = -1,
		LevelRange  = {-1,-1},
		Promotion  = -1,
		InvalidMission  = {},
		InvalidCompleteMission  = {},
		Unique  = 0,
		Period  = -1,
		Submissions = {69, },
		NewChar  = 35,
		ChangeJob  = -1,
		GP  = 0,
		EXP  = -1,
		RewardItem = {{215690, -1, -1}, },
		SelectItem = {},
		ChainMissionID = -1,
		CorrectLevel = -1,
	},
	{
		ID = 34280,
		TitleID = 294,
		MissionDescID  = 295,
		CharType  = -1,
		LevelRange  = {-1,-1},
		Promotion  = -1,
		InvalidMission  = {},
		InvalidCompleteMission  = {},
		Unique  = 0,
		Period  = -1,
		Submissions = {70, },
		NewChar  = 35,
		ChangeJob  = -1,
		GP  = 0,
		EXP  = -1,
		RewardItem = {{215690, -1, -1}, },
		SelectItem = {},
		ChainMissionID = -1,
		CorrectLevel = -1,
	},
	{
		ID = 215700,
		TitleID = 296,
		MissionDescID  = 297,
		CharType  = -1,
		LevelRange  = {-1,-1},
		Promotion  = -1,
		InvalidMission  = {},
		InvalidCompleteMission  = {},
		Unique  = 0,
		Period  = -1,
		Submissions = {71, },
		NewChar  = 36,
		ChangeJob  = -1,
		GP  = 0,
		EXP  = -1,
		RewardItem = {{215700, -1, -1}, },
		SelectItem = {},
		ChainMissionID = -1,
		CorrectLevel = -1,
	},
	{
		ID = 34290,
		TitleID = 298,
		MissionDescID  = 299,
		CharType  = -1,
		LevelRange  = {-1,-1},
		Promotion  = -1,
		InvalidMission  = {},
		InvalidCompleteMission  = {},
		Unique  = 0,
		Period  = -1,
		Submissions = {72, },
		NewChar  = 36,
		ChangeJob  = -1,
		GP  = 0,
		EXP  = -1,
		RewardItem = {{215700, -1, -1}, },
		SelectItem = {},
		ChainMissionID = -1,
		CorrectLevel = -1,
	},
	{
		ID = 297350,
		TitleID = 300,
		MissionDescID  = 301,
		CharType  = -1,
		LevelRange  = {-1,-1},
		Promotion  = -1,
		InvalidMission  = {},
		InvalidCompleteMission  = {},
		Unique  = 0,
		Period  = -1,
		Submissions = {73, },
		NewChar  = 37,
		ChangeJob  = -1,
		GP  = 0,
		EXP  = -1,
		RewardItem = {{297350, -1, -1}, },
		SelectItem = {},
		ChainMissionID = -1,
		CorrectLevel = -1,
	},
	{
		ID = 34300,
		TitleID = 302,
		MissionDescID  = 303,
		CharType  = -1,
		LevelRange  = {-1,-1},
		Promotion  = -1,
		InvalidMission  = {},
		InvalidCompleteMission  = {},
		Unique  = 0,
		Period  = -1,
		Submissions = {74, },
		NewChar  = 37,
		ChangeJob  = -1,
		GP  = 0,
		EXP  = -1,
		RewardItem = {{297350, -1, -1}, },
		SelectItem = {},
		ChainMissionID = -1,
		CorrectLevel = -1,
	},
	{
		ID = 297360,
		TitleID = 304,
		MissionDescID  = 305,
		CharType  = -1,
		LevelRange  = {-1,-1},
		Promotion  = -1,
		InvalidMission  = {},
		InvalidCompleteMission  = {},
		Unique  = 0,
		Period  = -1,
		Submissions = {75, },
		NewChar  = 38,
		ChangeJob  = -1,
		GP  = 0,
		EXP  = -1,
		RewardItem = {{297360, -1, -1}, },
		SelectItem = {},
		ChainMissionID = -1,
		CorrectLevel = -1,
	},
	{
		ID = 34310,
		TitleID = 306,
		MissionDescID  = 307,
		CharType  = -1,
		LevelRange  = {-1,-1},
		Promotion  = -1,
		InvalidMission  = {},
		InvalidCompleteMission  = {},
		Unique  = 0,
		Period  = -1,
		Submissions = {76, },
		NewChar  = 38,
		ChangeJob  = -1,
		GP  = 0,
		EXP  = -1,
		RewardItem = {{297360, -1, -1}, },
		SelectItem = {},
		ChainMissionID = -1,
		CorrectLevel = -1,
	},
}


TitleList = {
    BroadcastCheck = TRUE, -- ÄªÈ£È¹µæ½Ã °øÁö¿©ºÎ
    TitleList = { 83340,83350,83360,83370,83380,83390,83400,83410,83420,83430,83440,83450,83460,83470,83480,83490,83500,83510,83520,83530,105240,130880,130890,138910,147720,141730,182870,182890,184620,184640,188500,188520, 188540, 215670,215680,215690,215700,297350,297360},
    TitleOrder = {},
}