#ifdef __NEVER_DEFINED_MACRO__
#define _ENUM(VAL) VAL,
enum
{
#endif
/* 브라질 NCash.
_ENUM( EVENT_NCASH_UNDEFINED, 0 )
_ENUM( EVENT_NCASH_INIT_REQ, 1100 )
_ENUM( EVENT_NCASH_HEART_BIT_REQ, 1200 )
_ENUM( EVENT_NCASH_CURRENT_MONEY_REQ, 1300 )
_ENUM( EVENT_NCASH_BUY_REQ, 1310 )
_ENUM( EVENT_NCASH_PRESENT_REQ, 1320 )
_ENUM( EVENT_NCASH_INIT_ACK, 2100 )
_ENUM( EVENT_NCASH_HEART_BIT_ACK, 2200 )
_ENUM( EVENT_NCASH_CURRENT_MONEY_ACK, 2300 )
_ENUM( EVENT_NCASH_BUY_ACK, 2310 )
_ENUM( EVENT_NCASH_PRESENT_ACK, 2320 )
_ENUM( EVENT_NCASH_ERROR_NOT, 2900 )
*/
// 남미 NCash.
_ENUM( EVENT_NCASH_UNDEFINED, 0 )
_ENUM( EVENT_NCASH_INIT_REQ, 1100 )
_ENUM( EVENT_NCASH_HEART_BIT_REQ, 1111 )
_ENUM( EVENT_NCASH_CURRENT_MONEY_REQ, 1200 )
_ENUM( EVENT_NCASH_BUY_REQ, 1300 )
_ENUM( EVENT_NCASH_PRESENT_REQ, 1400 )
_ENUM( EVENT_NCASH_INIT_ACK, 2100 )
_ENUM( EVENT_NCASH_HEART_BIT_ACK, 2111 )
_ENUM( EVENT_NCASH_CURRENT_MONEY_ACK, 2200 )
_ENUM( EVENT_NCASH_BUY_ACK, 2300 )
_ENUM( EVENT_NCASH_PRESENT_ACK, 2400 )
_ENUM( EVENT_NCASH_ERROR_NOT, 2900 )
#ifdef __NEVER_DEFINED_MACRO__
};
#undef _ENUM
#endif