#ifdef __NEVER_DEFINED_MACRO__
#define _ENUM(VAL) VAL,
enum
{
#endif

_ENUM( INPUT_VERIFICATION_REQ = 0 )

_ENUM( INPUT_VERIFICATION_FAIL )
_ENUM( INPUT_VERIFICATION_OK )
_ENUM( INPUT_EXIT_GAME_ACK )
_ENUM( INPUT_TO_CHANNELLOBBY )
_ENUM( INPUT_TO_CHANNEL )
_ENUM( INPUT_JOIN_ROOM )
_ENUM( INPUT_START_GAME_OK )
_ENUM( INPUT_END_GAME_OK )
_ENUM( INPUT_TO_SQUARE_JOIN )
_ENUM( INPUT_ENTER_SQUARE )
//_ENUM( INPUT_TO_JOINROOM_COLPLETE )
_ENUM( INPUT_CONNECT )
_ENUM( INPUT_START_MINIGAME )
_ENUM( INPUT_TO_MINIGAME )

_ENUM( INPUT_JOIN_ROOM_GUILD ) // 길드전 위한 상태 추가
_ENUM( INPUT_START_GAME_GUILD )
_ENUM( INPUT_END_GAME_GUILD )

_ENUM( INPUT_TO_AGIT_JOIN )
_ENUM( INPUT_ENTER_AGIT )

#ifdef __NEVER_DEFINED_MACRO__
};
#undef _ENUM
#endif