caption = {
	--	"ui_skillbox_main.stg",
	--	"ui_skillbox_sub.stg",
	--	"ui_skillbox_lock.stg",
	--	"ui_skillbox.stg",
	--	"ui_boxes.stg",
	{filename = "ui_scene_server.stg", caption = "서버선택 화면"},
	{filename = "ui_scene_square.stg", caption = "광장"},
	{filename = "ui_scene_worldmap.stg", caption = "월드맵"},
	{filename = "ui_scene_match.stg", caption = "대전"},
	{filename = "ui_square_overlayui.stg", caption = "광장 UI"},
	{filename = "ui_game_overlay_ui.stg", caption = "게임 UI"},
	{filename = "ui_agit_overlay.stg", caption = ""},	
	{filename = "ui_room_scene.stg", caption = "대기방"},
	{filename = "ui_worldmap_container.stg", caption = "월드맵"},
	{filename = "ui_shop_scene.stg", caption = "상점"},
	{filename = "ui_guild_scene.stg", caption = "길드"},
	{filename = "ui_my_info_scene.stg", caption = "장비"},
	{filename = "ui_coordi_shop_scene.stg", caption = "코디샵"},

	{filename = "ui_login_scene.stg", caption = "로그인"},	
	{filename = "ui_loading_scene.stg", caption = "로딩화면"},
	{filename = "ui_scene_common.stg", caption = ""},
	{filename = "ui_virtual_keyboard_dlg.stg", caption = "가상키"},	

	{filename = "ui_background_white.stg", caption = "흰색 백그라운드"},

	{filename = "ui_inventory_full_msg.stg", caption = "인벤토리 가득참 메시지"},
	{filename = "ui_ongamedlg.stg", caption = "게임 다이얼로그"},	
	{filename = "ui_option_tab.stg", caption = "게임옵션"},
	{filename = "ui_ranking_list.stg", caption = "랭킹"},

	{filename = "ui_msn_dlg.stg", caption = "친구 다이얼로그"},
	{filename = "ui_nateon_dlg.stg", caption = "채팅창"},
	{filename = "ui_tutorial_select_box.stg", caption = "연습모드 선택"},
	{filename = "ui_tutorial_select_box_new.stg", caption = "연습모드 선택 새버전"},
	{filename = "ui_collection_wnd.stg", caption = "콜렉션"},
	{filename = "ui_gc_mission_ui.stg", caption = "미션 유저인터페이스"},
	{filename = "ui_dungeon_room_list.stg", caption = "던전 방 리스트"},
	{filename = "ui_skilltree.stg", caption = "스킬트리"},

	{filename = "ui_new_enchant_main_dlg.stg", caption = "신강화(강화석) 다이얼로그"},
	{filename = "ui_gp_capsule.stg", caption = "캡슐"},
	{filename = "ui_gwc_donation_dlg.stg", caption = "기부 다이얼로그"},
	{filename = "ui_gwc_state_dlg.stg", caption = "GWC 국가"},
	{filename = "ui_coupon_npc_dlg.stg", caption = "쿠폰 이벤트"},	
	{filename = "ui_subscription_dlg.stg", caption = ""},
	{filename = "ui_subscription_box.stg", caption = ""},
	{filename = "ui_cooperation_event.stg", caption = "협동 이벤트"},
	{filename = "ui_item_socket_management_dlg.stg", caption = "아이템 소켓 다이얼로그"},
	{filename = "ui_monster_card_mix_dlg.stg", caption = "몬스터 카드 조합"},
	{filename = "ui_monster_card_book.stg", caption = "몬스터 카드집"},
	{filename = "ui_couple_viewer.stg", caption = "커플보기"},
	{filename = "ui_petcostume.stg", caption = "펫 코스튬"},
	{filename = "ui_clear_seal_bead.stg", caption = "구가챠"},
	{filename = "ui_clear_seal_bead_new.stg", caption = "신가챠"},
	{filename = "ui_event_rickoon_tornado.stg", caption = "미니게임 닉쿤 토네이도"},
	{filename = "ui_gift_item_box.stg", caption = "선물아이템 박스"},
	{filename = "ui_giveitem_dlg.stg", caption = "아이템주기"},
	{filename = "ui_npcmission_dlg.stg", caption = "NPC미션"},
	{filename = "ui_receiveitem_box.stg", caption = "아이템 획득 상자"},
	{filename = "ui_jin_event.stg", caption = "진 이벤트"},
	{filename = "ui_jin_event_msg.stg", caption = "진 이벤트 메세지"},
	{filename = "ui_happynewyear_dlg.stg", caption = "해피뉴이얼 다이얼로그"},
	{filename = "ui_valentineday_dlg.stg", caption = "발렌타인데이"},
	{filename = "ui_bingo.stg", caption = "미니게임 빙고"},
	{filename = "ui_quiz.stg", caption = "미니게임 퀴즈"},	
	{filename = "ui_puzzle.stg", caption = "미니게임 퍼즐"},	
	{filename = "ui_gawibawibo_game_box.stg", caption = "미니게임 가위바위보 게임"},
	{filename = "ui_socks_tree_dlg.stg", caption = "크리스마스양말트리"},
	{filename = "ui_contribution_dlg.stg", caption = "기부버튼 다이얼로그"},
	{filename = "ui_contribution_box.stg", caption = "기부상자"},
	{filename = "ui_vip_gacha_box.stg", caption = "VIP 가챠 박스"},
	{filename = "ui_square_loading_scene.stg", caption = "광장 로딩화면"},
	{filename = "ui_recommend_box.stg", caption = "친구추천 박스"},
	{filename = "ui_nickname_box.stg", caption = "닉네임 박스"},
	{filename = "ui_gem_exchange_box.stg", caption = "젬 교환 상자"},
	{filename = "ui_item_working_select_dlg.stg", caption = "제작/해제 선택 다이얼로그"},
	{filename = "ui_item_creation_dlg.stg", caption = "아이템 제작 다이얼로그"},
	{filename = "ui_item_breakup_dlg.stg", caption = "아이템 해제 다이얼로그"},
	{filename = "ui_enchant_box.stg", caption = "인첸트 다이얼로그"},
	{filename = "ui_bonus_charge_box.stg", caption = "보너스 충전 박스"},
	{filename = "ui_candidate_window.stg", caption = ""},
	{filename = "ui_replay_box.stg", caption = "리플레이 박스"},
	{filename = "ui_loading_box.stg", caption = "로딩 박스"},
	{filename = "ui_buy_cashitem_window.stg", caption = "캐쉬구매창"},
	{filename = "ui_friend_add_dlg.stg", caption = "친구추가 다이얼로그"},
	{filename = "ui_register_friend_dlg.stg", caption = "친구등록 다이얼로그"},
	{filename = "ui_friend_del_dlg.stg", caption = "친구삭제 다이얼로그"},
	{filename = "ui_event_box.stg", caption = "이벤트박스"},
	{filename = "ui_repetition_provide_event_box.stg", caption = "보급품 이벤트 박스"},
	{filename = "ui_pet_evolution_box.stg", caption = "펫 진화 박스"},
	{filename = "ui_pet_preview.stg", caption = "펫 미리보기"},
	{filename = "ui_cashitem_box.stg", caption = "캐쉬아이템박스"},
	{filename = "ui_select_pet_name_box.stg", caption = "펫이름 선택 박스"},
	{filename = "ui_attendance_calendar.stg", caption = "출석부"},
	{filename = "ui_perfect_attendance.stg", caption = "개근상"},
	{filename = "ui_guild_lobby_dlg.stg", caption = "길드로비"},
	{filename = "ui_create_room_box.stg", caption = "방 생성 박스"},
	{filename = "ui_change_room_title_box.stg", caption = "방제목 바꾸기 박스"},
	{filename = "ui_fairplay_report_box.stg", caption = ""},
	{filename = "ui_grade_wnd.stg", caption = "게임등급"},
	{filename = "ui_new_item_enchant_box.stg", caption = "아이템 인첸트"},
	{filename = "ui_welcome_back.stg", caption = "반갑다 친구야."},
	{filename = "ui_item_receive_box.stg", caption = "아이템 획득 목록 박스"},
	{filename = "ui_item_receive_box2.stg", caption = "아이템 획득 목록 박스2"},
	{filename = "ui_channel_list_box.stg", caption = "채널리스트"},
	{filename = "ui_create_dungeon_room_box.stg", caption = "던전방 생성 박스"},
	{filename = "ui_password_box.stg", caption = "패스워드 박스"},
	{filename = "ui_game_guide.stg", caption = "게임 가이드"},
	{filename = "ui_square_enter_ui.stg", caption = "광장 선택하기"},
	{filename = "ui_minigame_select_box.stg", caption = "미니게임 선택 박스"},
	{filename = "ui_guild_enter.stg", caption = "길드 들어가기 UI"},
	{filename = "ui_guild_dlg.stg", caption = "길드창"},
	{filename = "ui_guildmark_regist_dlg.stg", caption = "길드마크 등록"},
	{filename = "ui_job_change_guide.stg", caption = "직업 바꾸기 가이드"},
	{filename = "ui_invite_request_box.stg", caption = "파티 초대하기 박스"},
	{filename = "ui_invite_msg_box.stg", caption = "초대 메세지"},
	{filename = "ui_neonsign_select_box.stg", caption = "전광판 선택 박스"},
	{filename = "ui_neonsign_preview_box.stg", caption = "전광판 미리보기"},
	{filename = "ui_sell_item_box.stg", caption = "아이템 팔기 박스"},
	{filename = "ui_connect_msg.stg", caption = "접속 메세지"},
	{filename = "ui_treasure_item_box.stg", caption = "선물아이템 박스"},
	{filename = "ui_nateon_add_group_dlg.stg", caption = "친구목록 그룹추가"},
	{filename = "ui_nateon_add_friend_dlg.stg", caption = "친구목록 친구추가"},
	{filename = "ui_nateon_block_to_add_friend.stg", caption = "친구목록 차단하기"},
	{filename = "ui_emoticon_select.stg", caption = "이모티콘 선택박스"},
	{filename = "ui_rule_agreement.stg", caption = "약관동의"},
	{filename = "ui_gamble_box.stg", caption = "겜블아이템 박스"},
	{filename = "ui_magic_box.stg", caption = ""},
	{filename = "ui_message_box.stg", caption = "메세지박스"},
	{filename = "ui_lucky_day_receive_box.stg", caption = "출석부 럭키데이 아이템 지급 박스"},
	{filename = "ui_ask_use_virtualcash.stg", caption = "가상캐쉬 사용 묻는 UI"},
	{filename = "ui_color_box.stg", caption = "글자색 선택 박스"},
	{filename = "ui_recommend_list.stg", caption = "추천 리스트"},
	{filename = "ui_logout_box.stg", caption = "로그아웃 박스"},
	{filename = "ui_item_info_box.stg", caption = "아이템 정보 박스"},	
	{filename = "ui_coordi_item_change.stg", caption = "코디 아이템 교환"},
	{filename = "ui_coordi_viewer_dlg.stg", caption = "코디 복장 뷰어"},
	{filename = "ui_sell_count_item_dlg.stg", caption = "판매수량 정하기 다이얼로그"},
	{filename = "ui_item_information_box_pair.stg", caption = "아이템 정보 비교해서 보기"},
	{filename = "ui_gem_buy_box.stg", caption = "잼 구매 박스"},
	{filename = "ui_halloween_board.stg", caption = "미니게임 할로윈 주사위"},
	{filename = "ui_shadow_event_box.stg", caption = ""},
	{filename = "ui_guild_list.stg", caption = "길드 리스트"},
	{filename = "ui_guild_create_dlg.stg", caption = "길드 생성 다이얼로그"},

	{filename = "ui_guild_join_req_mbox.stg", caption = "길드 가입요청 메세지 박스"},
	{filename = "ui_guild_public_mbox.stg", caption = "길드창 메세지 박스"},

	{filename = "ui_item_property_select.stg", caption = ""},
	{filename = "ui_event_banner.stg", caption = "이벤트 배너"},
	{filename = "ui_guidebook.stg", caption = "가이드북"},

	{filename = "ui_tool_tip.stg", caption = "툴팁"},

	{filename = "ui_buy_cashitem_window.stg", caption = "캐쉬구매창"},

	--"ui_guild_parts.stg",
	{filename = "ui_hurryup.stg", caption = "재촉하기 메시지"},
	{filename = "ui_character_select_box.stg", caption = "캐릭터 선택 박스"},
	{filename = "ui_character_get_info.stg", caption = ""},
	{filename = "ui_hero_dungeon_dlg.stg", caption = "영웅던전"},
	{filename = "ui_missioncomplate_itemlist_box.stg", caption = ""},

	{filename = "ui_replay_rec.stg", caption = ""},
	{filename = "ui_replay_record.stg", caption = ""},
	{filename = "ui_replay_box_new.stg", caption = "리플레이 박스"},
	{filename = "ui_crafting_numbox.stg", caption = ""},
	{filename = "ui_mission_s4_dlg.stg", caption = "미션창"},
	{filename = "ui_weapon_change_box.stg", caption = "교체무기 선택창"},
	{filename = "ui_item_attribute_select.stg", caption = "아이템 속성 선택"},
	{filename = "ui_levelup_info_box.stg", caption = ""},
	{filename = "ui_guildshop.stg", caption = "길드샵"},
	{filename = "ui_event_sphinx_dlg.stg", caption = "미니게임 스핑크스"},

	--	"ui_chat_box_s4.stg",
	{filename = "ui_nickname_campaign_box.stg", caption = ""},
	{filename = "ui_event_plant_tree.stg", caption = ""},
	{filename = "ui_event_detail_view.stg", caption = ""},
	{filename = "ui_new_character_select.stg", caption = "첫 접속시 케릭터 및 이름 선택"},	
	{filename = "ui_choice_drop.stg", caption = "초이스 드랍"},	
	{filename = "ui_coordi_catalog_dlg.stg", caption = "코디 카탈로그"},
	{filename = "ui_vip_reward.stg", caption = ""},
	{filename = "ui_package_preview.stg", caption = "패키지 미리보기"},
	{filename = "ui_ItemBox.stg", caption = "아이템 박스"},
	{filename = "ui_event_minigame_list_box.stg", caption = "미니게임 선택 박스"},
	{filename = "ui_dota_shop.stg", caption = "점령전 상점"},
	{filename = "ui_DPointItemBox.stg", caption = "D포인트 박스"},
	{filename = "ui_agit_shop.stg", caption = ""},
	{filename = "ui_game_guide_azit.stg", caption = ""},
	{filename = "ui_party_dialogue.stg", caption = ""},
	{filename = "ui_party_list.stg", caption = ""},	

	{filename = "ui_mantis_report_dlg.stg", caption = ""},
}