#ifdef __NEVER_DEFINED_MACRO__
#define _ENUM(VAL) VAL,
enum
{
#endif

	_ENUM(EVENT_HEART_BIT = 0)
	_ENUM(EVENT_ACCEPT_CONNECTION_NOT = 1)
	//=================================================================================================

	// EAG = Event for Agent Server
	_ENUM(EAG_VERIFY_ACCOUNT_REQ)
	_ENUM(EAG_VERIFY_ACCOUNT_ACK)

	_ENUM(DB_EVENT_FIRST_INIT_REQ)
	_ENUM(DB_EVENT_SERVER_LIST_REQ)

	_ENUM(EAG_SERVER_RELAY_PACKET_REQ) // 패킷 전달 패킷
	_ENUM(EAG_SERVER_RELAY_PACKET_ACK)
	_ENUM(EAG_AGIT_RELAY_PACKET_REQ) // 아지트 전달 패킷
	_ENUM(EAG_AGIT_RELAY_PACKET_ACK)

	_ENUM(EAG_AGIT_ALL_CONFIG_REQ) // 아지트 모든 설정정보 요청
	_ENUM(EAG_AGIT_CONFIG_NOT) // 아지트 설정정보 전달
	_ENUM(EAG_AGIT_MAP_NOT) // 아지트 맵정보 전달
	_ENUM(EAG_AGIT_FLOWER_NOT) // 아지트 화분정보 전달
	_ENUM(EAG_AGIT_FAIRY_TREE_NOT) // 아지트 요정의나무 정보 전달
	_ENUM(EAG_AGIT_RANK_LIST_NOT) // 인기아지트 리스트 요청 (최초,일일)

	_ENUM(EAG_USER_CONNECT_NOT) // 유저접속 알림.
	_ENUM(EAG_USER_DISCONNECT_NOT) // 유저접속 알림.
	_ENUM(EAG_UPDATE_AGIT_VISITER_COUNT_NOT) // 아지트 방문자수 DB에 업데이트
	_ENUM(EAG_AGIT_VISITER_COUNT_BROAD) // 아지트접속인원에게 방문자수 알림

	_ENUM(EAG_ENTER_AGIT_REQ) // 아지트 입장요청
	_ENUM(EAG_ENTER_AGIT_ACK)
	_ENUM(EAG_ENTER_AGIT_BROAD) // 아지트 입장알림
	_ENUM(EAG_AGIT_LOADING_COMPLETE_REQ) // 아지트 로딩완료
	_ENUM(EAG_AGIT_LOADING_COMPLETE_ACK)
	_ENUM(EAG_LEAVE_AGIT_REQ) // 아지트 떠남.
	_ENUM(EAG_LEAVE_AGIT_ACK)
	_ENUM(EAG_LEAVE_AGIT_BROAD) // 아지트떠남 알림
	_ENUM(EAG_ENTER_AGIT_STAT_NOT) // 아지트 입장통계
	_ENUM(EAG_UPDATE_AGIT_USER_INFO_NOT) // 아지트유저정보 갱신 알림

	_ENUM(EAG_BUY_AGIT_MAP_REQ) // 아지트 맵 구매 요청
	_ENUM(EAG_BUY_AGIT_MAP_ACK)
	_ENUM(EAG_CHANGE_AGIT_MAP_BROAD) // 아지트 맵변경 알림
	_ENUM(EAG_SET_AGIT_OPTION_REQ) // 아지트 설정변경
	_ENUM(EAG_SET_AGIT_OPTION_ACK)

	_ENUM(EAG_SEED_FLOWER_POT_REQ) // 씨앗심기 요청
	_ENUM(EAG_SEED_FLOWER_POT_ACK)
	_ENUM(EAG_HARVEST_FLOWER_POT_REQ) // 수확하기 요청
	_ENUM(EAG_HARVEST_FLOWER_POT_ACK)
	_ENUM(EAG_CHANGE_FLOWER_POT_STATE_BROAD) // 화분상태 변경알림

	_ENUM(EAG_AGIT_CHAT_REQ) // 아지트 채팅
	_ENUM(EAG_AGIT_CHAT_ACK)
	_ENUM(EAG_AGIT_CHAT_BROAD) // 아지트채팅 알림

	_ENUM(EAG_AGIT_BAN_USER_REQ) // 아지트 추방
	_ENUM(EAG_AGIT_BAN_USER_ACK)
	_ENUM(EAG_AGIT_BAN_USER_NOT) // 아지트 추방알림

	_ENUM(EAG_SET_AGIT_OBJECT_POS_REQ) // 오브젝트 배치 요청
	_ENUM(EAG_SET_AGIT_OBJECT_POS_ACK)
	_ENUM(EAG_CHANGE_AGIT_OBJECT_POS_BROAD)

	_ENUM(EAG_AGIT_FRIEND_LIST_REQ) // 친구아지트 리스트
	_ENUM(EAG_AGIT_FRIEND_LIST_ACK)
	_ENUM(EAG_AGIT_TOP_RANK_LIST_REQ) // 인기아지트 리스트
	_ENUM(EAG_AGIT_TOP_RANK_LIST_ACK)
	_ENUM(EAG_AGIT_FAVORITE_LIST_REQ) // 아지트 즐겨찾기 리스트 요청
	_ENUM(EAG_AGIT_FAVORITE_LIST_ACK)
	_ENUM(EAG_AGIT_ADD_FAVORITE_REQ) // 아지트 즐겨찾기 추가
	_ENUM(EAG_AGIT_ADD_FAVORITE_ACK)
	_ENUM(EAG_AGIT_REMOVE_FAVORITE_REQ) // 아지트 즐겨찾기 제거
	_ENUM(EAG_AGIT_REMOVE_FAVORITE_ACK)

	_ENUM(EAG_REGISTER_AGIT_PAGE_REQ) // 아지트 페이지 등록
	_ENUM(DB_EAG_REGISTER_AGIT_PAGE_REQ)
	_ENUM(EAG_REGISTER_AGIT_PAGE_ACK)
	_ENUM(EAG_UNREGISTER_AGIT_PAGE_REQ) // 아지트 페이지 등록해제
	_ENUM(EAG_UNREGISTER_AGIT_PAGE_ACK)
	_ENUM(EAG_AGIT_PAGE_LIST_REQ) // 아지트 페이지리스트 요청
	_ENUM(EAG_AGIT_PAGE_LIST_ACK)

	_ENUM(EAG_EQUIP_BROWNIE_REQ) // 아지트 도우미아이템 장착요청
	_ENUM(EAG_EQUIP_BROWNIE_ACK)
	_ENUM(EAG_CHANGE_BROWNIE_BROAD) // 아지트 도우미 변경알림

	_ENUM(EAG_WATERING_FAIRY_TREE_REQ) // 요정의 나무 물주기
	_ENUM(EAG_WATERING_FAIRY_TREE_ACK)
	_ENUM(EAG_CHANGE_FAIRY_TREE_BROAD) // 요정의나무 상태 변경알림
	_ENUM(EAG_FAIRY_TREE_BUFF_NOT) // 유저접속시, 요정의나무 열매버프 알림
	_ENUM(EAG_USE_FAIRY_TREE_FRUIT_REQ) // 요정의나무 열매사용하기
	_ENUM(EAG_USE_FAIRY_TREE_FRUIT_ACK)
	_ENUM(EAG_UPDATE_FAIRY_TREE_REQ) // 요정의나무 상태갱신 요청(매 자정)
	_ENUM(EAG_UPDATE_FAIRY_TREE_ACK)

	_ENUM(EAG_ENTER_AGIT_SID_REQ) // 아지트 정보가 있는 에이전트서버ID요청
	_ENUM(EAG_ENTER_AGIT_SID_ACK)
	_ENUM(EAG_SET_AGIT_SID_BROAD) // 아지트 정보별 에이전트 서버ID 변경시 알림.
	_ENUM(EAG_LOAD_AGIT_INFO_NOT) // 아지트 정보 로드 요청
	_ENUM(EAG_CHANGE_AGIT_OPTION_BROAD) // 아지트 옵션변경 알림
	_ENUM(EAG_DELETE_FOR_AGIT_NOT) // 판매,삭제된 아지트 아이템 전달

	_ENUM(EAG_GUESTBOOK_PAGE_REQ) // 낙서장 리스트 요청
	_ENUM(EAG_GUESTBOOK_PAGE_ACK)
	_ENUM(EAG_GUESTBOOK_WRITE_REQ) // 낙서장 쓰기 요청
	_ENUM(EAG_GUESTBOOK_WRITE_ACK)
	_ENUM(EAG_GUESTBOOK_WRITE_BROAD) // 낙서장 새글 알림
	_ENUM(EAG_GUESTBOOK_DELETE_REQ) // 낙서장 글삭제 요청
	_ENUM(EAG_GUESTBOOK_DELETE_ACK)
	_ENUM(EAG_GUESTBOOK_DELETE_BROAD) // 낙서장 글삭제 알림

	_ENUM(EAG_USE_TRAINING_OBJ_REQ) // 훈련소 훈련하기 요청
	_ENUM(EAG_USE_TRAINING_OBJ_ACK)
	_ENUM(EAG_UPDATE_TRAINING_OBJ_REQ) // 훈련소 상태변경 요청
	_ENUM(EAG_UPDATE_TRAINING_OBJ_ACK)
	_ENUM(EAG_UPDATE_TRAINING_OBJ_BROAD) // 훈련소 상태변경 알림
	_ENUM(EAG_CHECK_TRAINING_OBJ_NOT) // 아지트별 훈련소 상태체크

	_ENUM(EAG_OPEN_AGIT_CHARACTER_REQ) // 캐릭터 배치 오픈요청
	_ENUM(EAG_OPEN_AGIT_CHARACTER_ACK)
	_ENUM(EAG_SET_AGIT_CHARACTER_POS_REQ) // 배치 설정.
	_ENUM(EAG_SET_AGIT_CHARACTER_POS_ACK)
	_ENUM(EAG_SET_AGIT_CHARACTER_MOTION_REQ) // 모션 설정.
	_ENUM(EAG_SET_AGIT_CHARACTER_MOTION_ACK)
	_ENUM(EAG_SET_AGIT_CHARACTER_COORDI_REQ) // 복장 설정.
	_ENUM(EAG_SET_AGIT_CHARACTER_COORDI_ACK)
	_ENUM(EAG_SET_AGIT_CHARACTER_SPEECH_REQ) // 대사 설정.
	_ENUM(EAG_SET_AGIT_CHARACTER_SPEECH_ACK)
	_ENUM(EAG_UPDATE_AGIT_CHARACTER_BROAD) // 아지트 배치캐릭터 변경 알림
	_ENUM(EAG_UPDATE_AGIT_CHARACTER_POS_BROAD) // 아지트 배치캐릭터 위치변경 알림

	//=================================================================================================

	// EAGS = Event for Agent Server Slave-Master
	_ENUM(EAGS_VERIFY_ACCOUNT_REQ)
	_ENUM(EAGS_VERIFY_ACCOUNT_ACK)

	// 아지트 정보
	_ENUM(EAGS_SET_AGIT_SID_REQ) // 유저 아지트 정보 생성 요청
	_ENUM(EAGS_SET_AGIT_SID_ACK)
	_ENUM(EAGS_SET_AGIT_SID_BROAD) // 아지트 정보별 에이전트 서버ID 변경시 알림.
	_ENUM(EAGS_CLEAR_AGIT_SID_NOT) // 유저 아지트정보 초기화 알림
	_ENUM(EAGS_UPDATE_SLAVE_STATE_NOT) // 에이전트 서버 아지트매니저 현재 가용상태 업데이트 전달
	_ENUM(EAGS_USER_CONNECT_NOT) // 유저접속 알림
	_ENUM(EAGS_USER_DISCONNECT_NOT) // 유저접속종료 알림
	_ENUM(EAGS_SET_DESTROY_AGIT_NOT) // 아지트정보 삭제할지 여부 마스터가 슬레이브로 전달

	_ENUM(EAGS_USER_CONNECT_STATUS_REQ) // 유저 접속유무 문의
	_ENUM(EAGS_USER_CONNECT_STATUS_ACK)

	_ENUM(EAGS_REMOVE_AGIT_INFO_NOT) // 아지트 정보 삭제 요청

	//패킷의 끝
	_ENUM(EVENT_EVENTID_SENTINEL) //패킷의 끝

#ifdef __NEVER_DEFINED_MACRO__
};
#undef _ENUM
#endif
