#pragma once
// [12/27/2007] breadceo. 광장에서 사용할 enum들

enum SQUARE_OBJ_TYPE
{
    SOT_INVALID = -1,
    SOT_PEOPLE,
	SOT_NEWSBOARD,	//게시판    
	SOT_NPC,
	SOT_PET,
    SOT_BUFF_GUAGE,
    SOT_BUFF_BEAD_ACTIVE,
    SOT_BUFF_BEAD_INACTIVE,
    SOT_NUM,
};

enum SQUARE_OBJ_SUBTYPE
{
    SOST_INVALID = -1,
    SOST_MINIGAME_NPC,
	SOST_NORMAL_NPC,
	SOST_CONTRIBUTION_NPC,
	SOST_HAPPYNEWYEAR_NPC,
	SOST_CHARACTER_NPC,
	SOST_GP_CAPSULE_NPC,
	SOST_COUPON_NPC,
	SOST_RAINBOW_NPC,
	SOST_SUBSCRIPTION_NPC,
	SOST_SUBSCRIPTION_NPC1,
	SOST_SUBSCRIPTION_NPC2,
	SOST_SUBSCRIPTION_NPC3,
	SOST_VOTE_NPC,
	SOST_GWC_NPC,
	SOST_GP_CAPSULE_NPC2,
	SOST_GUILD_JOIN_NPC,
	SOST_NEWYEAR_NPC,
    SOST_ITEM_WORKING_SELECT_NPC,
    SOST_NEW_ENCHANT_MAIN_DLG_NPC,
    SOST_ITEM_TRADE_NPC,
    SOST_NUM,
};
