//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by GCServerManager.rc
//
#define IDC_CLOSE_BUTTON                3
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   101
#define IDR_GCSERVTYPE                  102
#define IDD_SERVER_LIST                 103
#define IDD_ADD_SERVER_LIST             104
#define IDD_CHANNEL_LOBBY               105
#define IDD_CHANNEL                     106
#define IDD_DIALOG_NOTIFY               107
#define IDD_DIALOG_USER_INFO            108
#define IDD_DIALOG_ROOM_INFO            109
#define IDD_DIALOG_LOGIN                110
#define IDD_DIALOG_CHANGE_DB_INFO       111
#define IDD_DIALOG_BLACK_LIST           113
#define IDD_DIALOG_REASON               114
#define IDD_DIALOG_ADMIN_DB_ACCESS      115
#define IDD_ADMIN_INSERT_GP_NORMAL_ITEM_ 116
#define IDD_ADMIN_INSERT_GP_DURATION_ITEM_ 117
#define IDD_ADMIN_DEL_ITEM_             118
#define IDD_ADMIN_ITEM_IFNO_DATA        119
#define IDD_ADMIN_INSERT_CASH_DURATION_ITEM_ 120
#define IDD_ADMIN_INSERT_CASH_NORMAL_ITEM_ 121
#define IDD_DIALOG_NEWID                122
#define IDC_SERVER_LIST                 1000
#define IDC_ADD_LIST                    1001
#define IDC_REMOVE_LIST                 1002
#define IDC_SERVER_IPADDRESS            1003
#define IDC_SERVER_PORT                 1004
#define IDC_SERVER_VERSION              1005
#define IDC_CHANNEL_LIST                1006
#define IDC_SERVER_VERSION2             1006
#define IDC_SERVER_Name                 1006
#define IDC_LIST_ROOM                   1007
#define IDC_LIST_USER                   1008
#define IDC_LIST_CHAT                   1009
#define IDC_EDIT_ADMIN_CHAT             1010
#define IDC_EDIT_NORMAL_CHAT            1011
#define IDC_DEF_BTN_ADMIN               1012
#define IDC_RICHEDIT_CHAT               1013
#define IDC_BUTTON_USER_LIST_UPDATE     1014
#define IDC_BUTTON_ROOM_LIST_UPDATE     1015
#define IDC_BUTTON_CHAT_STOP            1016
#define IDC_EDIT_NOTIFY                 1017
#define IDC_EDIT_LOGIN_ID               1018
#define IDC_EDIT_LOGIN_PW               1019
#define IDC_EDIT_USER_LOGIN_ID          1020
#define IDC_EDIT_EXP0                   1021
#define IDC_EDIT_EXP1                   1022
#define IDC_EDIT_EXP2                   1023
#define IDC_EDIT_STATUS                 1024
#define IDC_EDIT_ZENDER                 1025
#define IDC_BUTTON_KICK                 1026
#define IDC_BUTTON_CHANGE_DB_INFO       1027
#define IDC_EDIT_ROOM_ID                1028
#define IDC_EDIT_ROOM_NAME              1029
#define IDC_EDIT_PUBLIC                 1030
#define IDC_EDIT_PASSWD                 1031
#define IDC_EDIT_USER_NUM               1032
#define IDC_EDIT_ROOM_STATUS            1033
#define IDC_EDIT_HOST_IP                1034
#define IDC_EDIT_USER_ID                1035
#define IDC_EDIT_DB_EXP0                1036
#define IDC_EDIT_DB_EXP1                1037
#define IDC_EDIT_DB_EXP2                1038
#define IDC_EDIT_DB_GP                  1039
#define IDC_EDIT_DB_BLESSING0           1040
#define IDC_EDIT_DB_BLESSING1           1041
#define IDC_EDIT_DB_BLESSING2           1042
#define IDC_COMBO_AUTH_LEVEL            1043
#define IDC_BUTTON_KICK_USER            1044
#define IDC_BUTTON_DROP_USER            1045
#define IDC_RADIO_CURSE                 1046
#define IDC_RADIO_PAPER                 1047
#define IDC_RADIO_IMPERSONATION         1048
#define IDC_LIST_BLACK_LIST             1049
#define IDC_BUTTON_REMOVE               1050
#define IDC_BUTTON_EXP_RESET            1051
#define IDC_EDIT_LIST                   1052
#define IDC_LIST1                       1053
#define IDC_SELECT_NORMAL_ITEM          1054
#define IDC_USER_NAME                   1055
#define IDC_LIST2                       1056
#define IDC_SELECT_DURATION_ITEM        1057
#define IDC_SELECT_DEL_NORMAL_ITEM      1058
#define IDC_NORMAL_ITEM_SAVE_TEXT       1059
#define IDC_STATIC_DURATION_LIST        1061
#define IDC_STATIC_NORMAL_LIST          1062
#define IDC_DURATION_ITEM_SAVE_TEXT     1064
#define IDC_DURATION_DEL_ITEM           1065
#define IDC_STATIC_ITEM_ID              1068
#define IDC_STATIC_ITEM_ID2             1069
#define IDC_STATIC_LOGIN                1070
#define IDC_INSERT_ITEM                 1071
#define IDC_DELETE_ITEM                 1072
#define IDC_INSERT_GP_DURATION_ITEM     1073
#define IDC_ADMIN_INSERT_NORMAL_ITEM_USER_NAME 1074
#define IDC_ADMIN_INSERT_NORMAL_ITEM_GOODSID 1075
#define IDC_ADMIN_INSERT_GP_NORMAL_ITEM 1076
#define IDC_ADMIN_INSERT_GP_DURATION_ITEM 1077
#define IDC_ADMIN_INSERT_DURATION_ITEM_GOODSID 1078
#define IDC_ADMIN_INSERT_DURATION_ITEM_USER_NAME 1079
#define IDC_ADMIN_DEL_ITEM_GOODSUID     1080
#define IDC_ADMIN_DEL_ITEM_USER_NAME    1081
#define IDC_ADMIN_DEL_ITEM_GOODSID      1082
#define IDC_ADMIN_DEL_ITEM              1083
#define IDC_SELECT_USER_DATA            1084
#define IDC_CHANGE_STRONG_ITEM_LIST     1085
#define IDC_ADMIN_ITEMINFO_DATA_BUTTON  1086
#define IDC_ITEM_GOODSID                1087
#define IDC_ITEM_SUB_NAME               1088
#define IDC_SELECT_ADMIN_ITEM_INFO_DATA 1089
#define IDC_ITEMINFOLIST                1090
#define IDC_CLOSE                       1091
#define IDC_INSERT_CASH_NORMAL_ITEM     1092
#define IDC_INSERT_CASH_DURATION_ITEM   1093
#define IDC_ADMIN_INSERT_CASH_NORMAL_ITEM 1095
#define IDC_ADMIN_INSERT_CASH_DURATION_ITEM 1096
#define IDC_LOGINID                     1097
#define IDC_NICKNAME                    1098
#define IDC_USERID                      1100
#define IDC_USERID2                     1101
#define IDC_STATIC_NOTE                 1101
#define IDC_STATIC_Warning              1102
#define IDC_EDIT_UserID                 1103
#define IDC_EDIT_NickName               1104
#define IDC_EDIT_LOSE                   1105
#define IDC_COMBO_PAGE                  1110
#define IDC_COMBO_GAMEMODE              1113
#define IDC_SCROLLBAR1                  1114
#define IDC_COMBO_GAMEMODE2             1114
#define IDC_COMBO_AREA                  1114
#define IDC_COMBO1                      1115
#define IDC_COMBO_USER_PAGE             1115
#define IDC_HOTKEY1                     1116
#define IDC_RADIO_ADMIN_CHAT            1118
#define IDC_RADIO_ADMIN_CHAT_S          1119
#define IDC_RADIO_SB_NOTICE_S           1120
#define IDC_RADIO_SB_NOTICE             1121
#define IDC_RADIO_SB_SERVER_S           1121
#define IDC_RADIO_SB_SERVER             1122
#define IDC_LIST_ROOM_MEMBERS           1122
#define IDC_RADIO_NORMAL_CHAT           1123
#define IDC_LIST_SQUARE                 1124
#define IDC_BUTTON_SQUARE_UPDATE        1125
#define IDC_LIST_SQUARE_USER            1126
#define IDC_COMBO_SQUARE_USER_INFO      1128
#define IDC_COMBO_SQUARE_USER_PAGE      1128
#define ID_MENU_NOTIFY_MSG              32771
#define ID_MENU_BLACK_LIST              32772

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        125
#define _APS_NEXT_COMMAND_VALUE         32773
#define _APS_NEXT_CONTROL_VALUE         1130
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
