#include "stdafx.h"

#include"HardDamageAmy3Special3.cpp"
#include"HardDamageAmy3UniqueSkill1.cpp"
#include"HardDamageAmyNoteSinFly.cpp"
#include"HardDamageArme1IceStrike.cpp"
// HardDamage 제거작업 시작
//#include"HardDamageArmeBigBoom.cpp"
// HardDamage 제거작업 끝
#include"HardDamageArmeSkillTest.cpp"
#include"HardDamageArmeSummonGorgos.cpp"
#include"HardDamageArmeWallOfIce.cpp"
#include"HardDamageArrow.cpp"
// HardDamage 제거작업 시작 
//#include"HardDamageAssassinRanger.cpp"
// HardDamage 제거작업 끝
#include"HardDamageBasiliskFire.cpp"
#include"HardDamageBermesiaFinalEarthQuake.cpp"
#include"HardDamageBigLightning.cpp"
#include"HardDamageBigLightningReady.cpp"
#include"HardDamageBigMeteo.cpp"
#include"HardDamageBigMeteoReady.cpp"
#include"HardDamageBigMeteoSolo.cpp"
#include"HardDamageBlockBuster.cpp"
#include"HardDamageBomb.cpp"
#include"HardDamageBomb2.cpp"
#include"HardDamageBombWave.cpp"
#include"HardDamageBreeding.cpp"
#include"HardDamageCannon.cpp"
#include"HardDamageChargedBolt.cpp"
#include"HardDamageCrabStone.cpp"
#include"HardDamageCriticalArrow.cpp"
#include"HardDamageDrillRock.cpp"
#include"HardDamageElectronBall.cpp"
#include"HardDamageElesis4DownAtk.cpp"
#include"HardDamageElesis4Special2.cpp"
#include"HardDamageElesis4Special2Shoot.cpp"
#include"HardDamageFire.cpp"
#include"HardDamageFireLance.cpp"
#include"HardDamageFireSpot.cpp"
#include"HardDamageFlingShield.cpp"
#include"HardDamageGas.cpp"
#include"HardDamageGorgosFire.cpp"
#include"HardDamageGuardianBall.cpp"
#include"HardDamageGuardianStrike.cpp"
#include"HardDamagehold.cpp"
#include"HardDamageHommingMissle.cpp"
#include"HardDamageIceBolt.cpp"
#include"HardDamageIcePixieIceStorm.cpp"
#include"HardDamageJinSpecial3Burnning.cpp"
#include"HardDamageKamikiLightning.cpp"
#include"HardDamageKazeazeDarkBall.cpp"
#include"HardDamageLas4BounceAtk.cpp"
#include"HardDamageLas4DownAtk.cpp"
#include"HardDamageLas4Special3Sword.cpp"
#include"HardDamageLightningBolt.cpp"
#include"HardDamageLightningGenerate1.cpp"
#include"HardDamageLightningGenerate2.cpp"
#include"HardDamageMagicMissile.cpp"
#include"HardDamageMagicStar.cpp"
#include"HardDamageManyFruit.cpp"
#include"HardDamageMeteo.cpp"
#include"HardDamageMine.cpp"
#include"HardDamageMonsterMine.cpp"
#include"HardDamageOctusWarcry.cpp"
#include"HardDamagePhoenixArrow.cpp"
#include"HardDamageRonan2MagicSpecial1.cpp"
#include"HardDamageRonan4MonoVolt.cpp"
#include"HardDamageRonan4SummonValkyrie.cpp"
#include"HardDamageRonan4SwordSpecial3.cpp"
#include"HardDamageRonanMagicSpecial1.cpp"
#include"HardDamageRonanMeteo.cpp"
#include"HardDamageSaintBreeding.cpp"
#include"HardDamageShotMagicCircle.cpp"
#include"HardDamageSiegeDeco.cpp"
#include"HardDamageSinFly.cpp"
#include"HardDamageStarDustRain.cpp"
#include"HardDamageStoneCurse.cpp"
#include"HardDamageSummonDragon.cpp"
#include"HardDamageSummonInstrument.cpp"
#include"HardDamageSummonTempest.cpp"
#include"HardDamageWaterPole.cpp"
#include"HardDamageWholeStageGas.cpp"
#include"KGCHardDamagePoisonBreath.cpp"
#include"KHardDamagePepeGas.cpp"
#include "HardDamageLasTradWarmPot.cpp"
#include "HardDamageTradWarmTrap.cpp"
#include "HardDamageRyanTotem.cpp"
#include "HardDamageRyanPoisonSpore.cpp"
#include "HardDamageRyanBloody.cpp"
#include "HardDamageAmy4.cpp"
#include "HardDamageXenia5MapDamage.cpp"
#include "HardDamagePeriot.cpp"
#include "HardDamageXenia7.cpp"
#include "HardDamageXenia8.cpp"
#include "HardDamageJin.cpp"
#include "HardDamageMermairing.cpp"
#include "HardDamageAmy1SkillTree.cpp"
#include "HardDamagePet.cpp"
#include "HardDamageMari.cpp"
#include "HardDamageMari2BuildLV2.cpp"
#include "HardDamageDesert4.cpp"
#include "HardDamageChaos2.cpp"
#include "HardDamageChaos3.cpp"
#include "HardDamageHero1.cpp"
#include "HardDamageSelion.cpp"
#include "HardDamageAstarot.cpp"
#include "HardDamageKindPet.cpp"
#include "HardDamageBlitchen.cpp"
#include"../Damage.cpp"
#include"../DamageManager.cpp"
#include "HardDamageBakunawa.cpp"
#include "HardDamageDevilion.cpp"
//#include "HardDamageUnoSpecial4.cpp"
#include "HardDamageShotMagicCircleDun.cpp"
#include "HardDamageRoseArrow.cpp"